using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region LOCarGroups
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:LOCarGroupsController
	//Created Date:10 Tháng Giêng 2013
	//-----------------------------------------------------------
	
	public class LOCarGroupsController:BaseBusinessController
	{
		public LOCarGroupsController()
		{
			dal= new DALBaseProvider("LOCarGroups",typeof(LOCarGroupsInfo));
		}
	}
	#endregion
}