using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region LOCarMaterials
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:LOCarMaterialsController
	//Created Date:Thursday, October 21, 2010
	//-----------------------------------------------------------
	
	public class LOCarMaterialsController:BaseBusinessController
	{
		public LOCarMaterialsController()
		{
			dal= new DALBaseProvider("LOCarMaterials",typeof(LOCarMaterialsInfo));
		}
	}
	#endregion
}