using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region LOPaymentDetails
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:LOPaymentDetailsController
	//Created Date:Saturday, February 21, 2009
	//-----------------------------------------------------------
	
	public class LOPaymentDetailsController:BaseBusinessController
	{
		public LOPaymentDetailsController()
		{
			dal= new DALBaseProvider("LOPaymentDetails",typeof(LOPaymentDetailsInfo));
		}
	}
	#endregion
}