using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ICUOMCalculators
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:ICUOMCalculatorsController
	//Created Date:Tuesday, April 14, 2015
	//-----------------------------------------------------------
	
	public class ICUOMCalculatorsController:BaseBusinessController
	{
		public ICUOMCalculatorsController()
		{
			dal= new DALBaseProvider("ICUOMCalculators",typeof(ICUOMCalculatorsInfo));
		}
	}
	#endregion
}