 using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ViewProductionCalendars
	//-----------------------------------------------------------
	//Generated By: SQLDBTools.NET - LINHCLH (v2.0.5)
	//Class: ViewProductionCalendarsController
	//Created Date: Tuesday, 20 Jun 2017
	//-----------------------------------------------------------
	
	public class ViewProductionCalendarsController : BaseBusinessController
	{
		public ViewProductionCalendarsController()
		{
			dal = new DALBaseProvider("ViewProductionCalendars",typeof(ViewProductionCalendarsInfo));
		}
	}
	#endregion
}