using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ViewLoanAgreements
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ViewLoanAgreementsController
	//Created Date:Tuesday, March 03, 2015
	//-----------------------------------------------------------
	
	public class ViewLoanAgreementsController:BaseBusinessController
	{
		public ViewLoanAgreementsController()
		{
			dal= new DALBaseProvider("ViewLoanAgreements",typeof(ViewLoanAgreementsInfo));
		}
        public DataSet ViewLoanAgreementDetail(DateTime dtFrom, DateTime dtTo, DateTime dtLastStartFiscalYear, string sAccountNo, int iBranchID = 0, int iLoanAgreementID = 0, int iLoanContractID = 0, int iAccountID = 0)
        {
            return SqlDatabaseHelper.RunStoredProcedure("sp_GetLoanAgreementDetails",dtFrom, dtTo, " (GLAccountNo LIKE '" + sAccountNo.Replace(",", "%' OR GLAccountNo LIKE '") + "%')", iBranchID, iLoanContractID, iLoanAgreementID, iAccountID);
        }
        public DataSet ViewLoanAgreementSummary(String strAccountNo, DateTime dtFrom, DateTime dtTo, DateTime dtLastStartFiscalYear, int iLevel, bool bNotKC911 = false, bool bKoButruSDTH = true, bool bDetailObj = false, bool bDelEmptyData = true, int iBranchID = 0)
        {
            //return CalcTrialBalanceOld(strAccountNo, dtFrom, dtTo, dtLastStartFiscalYear, iLevel);
            String strQuery = String.Format(
                @"
                    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
                        --BANG CAN DOI PHAT SINH
                        SET NOCOUNT ON
                        DECLARE @sAccountNo as nvarchar(50),
		                        @dStart as datetime,
		                        @dFrom as datetime,
		                        @dTo as datetime,
		                        @iViewLevel as int,
		                        @bViewObjects as bit,
		                        @bKoButru as bit,
                                @bNotKC911 as bit,
                                @bDelEmptyData as bit,
								@iBranchID as int

                        SET @sAccountNo = '{0}%'
                        SET @dStart = '{1}'
                        SET @dFrom = '{2}'
                        SET @dTo = '{3}'
                        SET @iViewLevel = {4}
                        SET @bNotKC911 = {5}
                        SET @bKoButru = {6}                        
                        SET @bViewObjects = {7}
                        SET @bDelEmptyData = {8}
						SET @iBranchID = {9}

                        DECLARE @FK_GECurrencyID int
                        SELECT TOP 1 @FK_GECurrencyID = FK_GECurrencyID 
	                        FROM CSCompanys
	                        WHERE AAStatus = 'Alive'

                        --(Loc du lieu ra de tang toc do truy van

                        SELECT GLAccountID, GLAccountNo, GLAccountName, 
                                GLAccountLevel, GLAccountBalanceCombo,FK_GLAccountParentID INTO #t311_341
                            FROM dbo.GLAccounts 
                            WHERE AAStatus = 'Alive' AND LEFT(GLAccountNo,3) = '311'
                        UNION ALL
                        SELECT GLAccountID, GLAccountNo, GLAccountName, 
                                GLAccountLevel, GLAccountBalanceCombo,FK_GLAccountParentID
                            FROM dbo.GLAccounts 
                            WHERE AAStatus = 'Alive' AND LEFT(GLAccountNo,3) = '341'

                        SELECT GLAccountID INTO #tGLAccountsNC
	                        FROM #t311_341
	                        WHERE GLAccountBalanceCombo = 'NC'

						SELECT GLAccountID INTO #tGLAccountsNotNC
	                        FROM #t311_341
	                        WHERE GLAccountBalanceCombo <> 'NC'

                        --(Dau nam tai chinh
                        SELECT	FK_GLDebitAccountID,FK_GLCreditAccountID,
		                        GLJournalAmt,
		                        GLJournalFAmt,
                                FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID
		                INTO #tSDDK
                        FROM dbo.GLJournals a
                            LEFT JOIN #t311_341 b ON a.FK_GLDebitAccountID = b.GLAccountID
                            LEFT JOIN #t311_341 c ON a.FK_GLCreditAccountID = c.GLAccountID
                        WHERE GLJournalPeriod = 0 AND GLJournalYear = Year(@dStart)
                                AND (FK_GLDebitAccountID > 0 OR FK_GLCreditAccountID > 0)
								AND (FK_BRBranchID = @iBranchID OR @iBranchID = 0)
                                AND (b.GLAccountID is not null OR c.GLAccountID is not null)
                        --)
                        --(PS tu dau nam
                        SELECT	FK_GLDebitAccountID,FK_GLCreditAccountID,
		                        GLJournalAmt,
		                        GLJournalFAmt,
                                FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID
		                INTO #tPSDK
                        FROM dbo.GLJournals a
                            LEFT JOIN #t311_341 b ON a.FK_GLDebitAccountID = b.GLAccountID
                            LEFT JOIN #t311_341 c ON a.FK_GLCreditAccountID = c.GLAccountID
                        WHERE GLJournalPeriod <> 0 
                            AND CONVERT(VARCHAR(20), GLJournalDate, 112) between CONVERT(VARCHAR(20),@dStart,112) and CONVERT(VARCHAR(20),@dFrom - 1,112)
							AND (FK_BRBranchID = @iBranchID OR @iBranchID = 0)
							AND (b.GLAccountID is not null OR c.GLAccountID is not null)
                        --)
                        --(PS Trong ky                   
                        SELECT	FK_GLDebitAccountID,FK_GLCreditAccountID,
		                        GLJournalAmt,
		                        GLJournalFAmt,
                                FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID
		                INTO #tPSTK
                        FROM dbo.GLJournals a
                            LEFT JOIN #t311_341 b ON a.FK_GLDebitAccountID = b.GLAccountID
                            LEFT JOIN #t311_341 c ON a.FK_GLCreditAccountID = c.GLAccountID                        
                        WHERE GLJournalPeriod <> 0 --AND GLJournalDate BETWEEN @dFrom AND @dTo
	                        AND CONVERT(VARCHAR(20), GLJournalDate, 112) between CONVERT(VARCHAR(20),@dFrom,112) and CONVERT(VARCHAR(20),@dTo,112)
	                        AND (FK_BRBranchID = @iBranchID OR @iBranchID = 0)
	                        AND (b.GLAccountID is not null OR c.GLAccountID is not null)
                        --)
                        
                        --(Tao bang du lieu chi tiet
                        --DuN dau nam tai chinh
                        SELECT	FK_GLDebitAccountID as FK_GLAccountID, 
		                        GLJournalAmt as DK_No0,
		                        0 as DK_Co0,
		                        0 as Ps_no0,
		                        0 as Ps_co0,
		                        0 as Ps_no,
		                        0 as Ps_co,
		                        GLJournalFAmt as DK_No0_NT,
		                        0 as DK_Co0_NT,
		                        0 as Ps_no0_NT,
		                        0 as Ps_co0_NT,
		                        0 as Ps_no_NT,
		                        0 as Ps_co_NT,
		                        FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                ISNULL(GLJournalAmt, 0) as DK_No0_VND,
                                0 as DK_Co0_VND,
                                0 as Ps_no0_VND,
                                0 as Ps_co0_VND,
                                0 as Ps_no_VND,
                                0 as Ps_co_VND
                        INTO #tData
                        FROM #tSDDK
                        WHERE FK_GLDebitAccountID > 0 AND FK_GLDebitAccountID is not null
                        UNION ALL
                        --DuC dau nam tai chinh
                        SELECT	FK_GLCreditAccountID, 
		                        0 as DK_No0,
		                        GLJournalAmt as DK_Co0,
		                        0 as Ps_no0,
		                        0 as Ps_co0,
		                        0 as Ps_no,
		                        0 as Ps_co,
		                        0 as DK_No0_NT,
		                        GLJournalFAmt as DK_Co0_NT,
		                        0 as Ps_no0_NT,
		                        0 as Ps_co0_NT,
		                        0 as Ps_no_NT,
		                        0 as Ps_co_NT,
		                        FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                0 as DK_No0_VND,
                                ISNULL(GLJournalAmt, 0) as DK_Co0_VND,
                                0 as Ps_no0_VND,
                                0 as Ps_co0_VND,
                                0 as Ps_no_VND,
                                0 as Ps_co_VND
                        FROM #tSDDK
                        WHERE FK_GLCreditAccountID > 0 AND FK_GLCreditAccountID is not null
                        UNION ALL
                        --PSN luy ke tu dau nam den dau ngay bao cao
                        SELECT	FK_GLDebitAccountID, 
		                        0 as DK_No0,
		                        0 as DK_Co0,
		                        GLJournalAmt as Ps_no0,
		                        0 as Ps_co0,
		                        0 as Ps_no,
		                        0 as Ps_co,
		                        0 as DK_No0_NT,
		                        0 as DK_Co0_NT,
		                        GLJournalFAmt as Ps_no0_NT,
		                        0 as Ps_co0_NT,
		                        0 as Ps_no_NT,
		                        0 as Ps_co_NT,
		                        FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                0 as DK_No0_VND,
                                0 as DK_Co0_VND,
                                ISNULL(GLJournalAmt, 0)  as Ps_no0_VND,
                                0 as Ps_co0_VND,
                                0 as Ps_no_VND,
                                0 as Ps_co_VND
                        FROM #tPSDK
                        UNION ALL
                        --PSC luy ke tu dau nam den dau ngay bao cao
                        SELECT	FK_GLCreditAccountID, 
		                        0 as DK_No0,
		                        0 as DK_Co0,
		                        0 as Ps_no0,
		                        GLJournalAmt as Ps_co0,
		                        0 as Ps_no,
		                        0 as Ps_co,
		                        0 as DK_No0_NT,
		                        0 as DK_Co0_NT,
		                        0 as Ps_no0_NT,
		                        GLJournalFAmt as Ps_co0_NT,
		                        0 as Ps_no_NT,
		                        0 as Ps_co_NT,
		                        FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                0 as DK_No0_VND,
                                0 as DK_Co0_VND,
                                0 as Ps_no0_VND,
                                ISNULL(GLJournalAmt, 0) as Ps_co0_VND,
                                0 as Ps_no_VND,
                                0 as Ps_co_VND
                        FROM #tPSDK
                        UNION ALL
                        --PSN trong ky bao cao
                        SELECT	FK_GLDebitAccountID, 
		                        0 as DK_No0,
		                        0 as DK_Co0,
		                        0 as Ps_no0,
		                        0 as Ps_co0,
		                        GLJournalAmt as Ps_no,
		                        0 as Ps_co,
		                        0 as DK_No0_NT,
		                        0 as DK_Co0_NT,
		                        0 as Ps_no0_NT,
		                        0 as Ps_co0_NT,
		                        GLJournalFAmt as Ps_no_NT,
		                        0 as Ps_co_NT,
		                        FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                0 as DK_No0_VND,
                                0 as DK_Co0_VND,
                                0 as Ps_no0_VND,
                                0 as Ps_co0_VND,
                                ISNULL(GLJournalAmt, 0) as Ps_no_VND,
                                0 as Ps_co_VND
                        FROM #tPSTK
                        UNION ALL
                        --PSC trong ky bao cao
                        SELECT	FK_GLCreditAccountID, 
		                        0 as DK_No0,
		                        0 as DK_Co0,
		                        0 as Ps_no0,
		                        0 as Ps_co0,
		                        0 as Ps_no,
		                        GLJournalAmt as Ps_co,
		                        0 as DK_No0_NT,
		                        0 as DK_Co0_NT,
		                        0 as Ps_no0_NT,
		                        0 as Ps_co0_NT,
		                        0 as Ps_no_NT,
		                        GLJournalFAmt as Ps_co_NT,
                                FK_GLLoanAgreementID,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                0 as DK_No0_VND,
                                0 as DK_Co0_VND,
                                0 as Ps_no0_VND,
                                0 as Ps_co0_VND,
                                0 as Ps_no_VND,
                                ISNULL(GLJournalAmt, 0) as Ps_co_VND
                        FROM #tPSTK
                        --)

                        UPDATE #tData
                            SET FK_GLBankID = b.FK_GLBankID
                            FROM #tData a 
                                INNER JOIN GLLoanAgreements b ON a.FK_GLLoanAgreementID = b.GLLoanAgreementID

                        --(Bo doi tuong cac tai khoan khong theo doi doi tuong
                        /*UPDATE #tData
                            set FK_ARCustomerID = 0,
	                            FK_APSupplierID = 0,
	                            FK_HREmployeeID = 0
                        FROM #tData a 
                        INNER JOIN #tGLAccountsNotNC b ON a.FK_GLAccountID = b.GLAccountID
                        */
                        --)

                        --(Tinh tong theo doi tuong
                        SELECT FK_GLAccountID,
		                        SUM(DK_No0) as DK_No0,
		                        SUM(DK_Co0) as DK_Co0,
		                        SUM(PS_no0) as PS_NO0,
		                        SUM(PS_co0) as PS_Co0,
		                        cast (0 as float) as Dk_No,
		                        cast (0 as float) as Dk_Co,
		                        SUM(PS_no) as PS_NO,
		                        SUM(PS_co) as PS_Co,
		                        cast (0 as float) as ck_No,
		                        cast (0 as float) as Ck_Co,
		                        SUM(DK_No0_NT) as DK_No0_NT,
		                        SUM(DK_Co0_NT) as DK_Co0_NT,
		                        SUM(PS_no0_NT) as PS_NO0_NT,
		                        SUM(PS_co0_NT) as PS_Co0_NT,
		                        cast (0 as float) as Dk_No_NT,
		                        cast (0 as float) as Dk_Co_NT,
		                        SUM(PS_no_NT) as PS_NO_NT,
		                        SUM(PS_co_NT) as PS_Co_NT,
		                        cast (0 as float) as ck_No_NT,
		                        cast (0 as float) as Ck_Co_NT,
		                        FK_GLBankID,
                                FK_GECurrencyID,
                                SUM(DK_No0_VND) as DK_No0_VND,
                                SUM(DK_Co0_VND) as DK_Co0_VND,
                                SUM(Ps_no0_VND) as Ps_no0_VND,
                                SUM(Ps_co0_VND) as Ps_co0_VND,
                                cast (0 as float) as Dk_No_VND,
		                        cast (0 as float) as Dk_Co_VND,
                                SUM(Ps_no_VND) as Ps_no_VND,
                                SUM(Ps_co_VND) as Ps_co_VND,
                                cast (0 as float) as ck_No_VND,
		                        cast (0 as float) as Ck_Co_VND
                        INTO #tKQ
                        FROM #tData a
                        INNER JOIN #t311_341 b ON a.FK_GLAccountID = b.GLAccountID 
                        GROUP BY	FK_GLAccountID,
			                        FK_GLBankID,
			                        FK_GECurrencyID
                        --)


                        --(Tinh lai so du dau nam va dau ky chi tiet dau nam tai chinh
                        UPDATE #tKQ set 
		                        dk_no0 = dk_no0 - dk_co0,
		                        dk_co0 = 0
	                        WHERE dk_co0 <> 0 AND dk_no0 >= dk_co0
	                    
	                    UPDATE #tKQ set 
		                        dk_no0_NT = dk_no0_NT - dk_co0_NT,
		                        dk_co0_NT = 0
	                        WHERE dk_co0_NT <> 0 AND dk_no0_NT >= dk_co0_NT

                        UPDATE #tKQ set 
		                        dk_co0 = dk_co0 - dk_no0,
		                        dk_no0 = 0
	                        WHERE dk_no0 <> 0 AND dk_co0 >= dk_no0
	                     
	                     UPDATE #tKQ set 
		                        dk_co0_NT = dk_co0_NT - dk_no0_NT,
		                        dk_no0_NT = 0
	                        WHERE dk_no0_NT <> 0 AND dk_co0_NT >= dk_no0_NT
                        ------
	                    UPDATE #tKQ set 
		                        dk_no0_VND = dk_no0_VND - dk_co0_VND,
		                        dk_co0_VND = 0
	                        WHERE dk_co0_VND <> 0 AND dk_no0_VND >= dk_co0_VND
	                    
                        UPDATE #tKQ set 
		                        dk_co0_VND = dk_co0_VND - dk_no0_VND,
		                        dk_no0_VND = 0
	                        WHERE dk_no0_VND <> 0 AND dk_co0_VND >= dk_no0_VND
	                     
						--)
						--(TInh so du dau ky
                        UPDATE #tKQ set 
		                        dk_no = dk_no0 - dk_co0 + ps_no0 - ps_co0
		                        
		                UPDATE #tKQ set 
		                        dk_no_NT = dk_no0_NT - dk_co0_NT + ps_no0_NT - ps_co0_NT
		
                        UPDATE #tKQ set 
		                        dk_co = ABS(dk_no),
		                        dk_no = 0
	                        WHERE dk_no < 0
	                    
	                    UPDATE #tKQ set 
		                        dk_co_NT = ABS(dk_no_NT),
		                        dk_no_NT = 0
	                        WHERE dk_no_NT < 0

	                    -------
	                    UPDATE #tKQ set 
		                        dk_no_VND = dk_no0_VND - dk_co0_VND + ps_no0_VND - ps_co0_VND
		                        
		
                        UPDATE #tKQ set 
		                        dk_co_VND = ABS(dk_no_VND),
		                        dk_no_VND = 0
	                        WHERE dk_no_VND < 0
	                    
                        --)
						--(TInh so du cuoi ky
                        UPDATE #tKQ set 
		                        ck_no = dk_no - dk_co + ps_no - ps_co
		
                        UPDATE #tKQ set 
		                        ck_no_NT = dk_no_NT - dk_co_NT + ps_no_NT - ps_co_NT
		                        
                        UPDATE #tKQ set 
		                        ck_co = ABS(ck_no),
		                        ck_no = 0
	                        WHERE ck_no < 0
	                    
	                    UPDATE #tKQ set 
		                        ck_co_NT = ABS(ck_no_NT),
		                        ck_no_NT = 0
	                        WHERE ck_no_NT < 0

                        -----------------
                        UPDATE #tKQ set 
		                        ck_no_VND = dk_no_VND - dk_co_VND + ps_no_VND - ps_co_VND
		
                      
                        UPDATE #tKQ set 
		                        ck_co_VND = ABS(ck_no_VND),
		                        ck_no_VND = 0
	                        WHERE ck_no_VND < 0
	                    
                        --)


                        --(Tinh tong cac tk theo doi chi tiet doi tuong
                        SELECT FK_GLAccountID,
		                        SUM(DK_No0) as DK_No0,
		                        SUM(DK_Co0) as DK_Co0,
		                        SUM(PS_no0) as PS_NO0,
		                        SUM(PS_co0) as PS_Co0,
		                        SUM(DK_No) as DK_No,
		                        SUM(DK_Co) as DK_Co,
		                        SUM(PS_no) as PS_NO,
		                        SUM(PS_co) as PS_Co,
		                        SUM(ck_No) as ck_No,
		                        SUM(ck_Co) as ck_Co,
		                        SUM(DK_No0_NT) as DK_No0_NT,
		                        SUM(DK_Co0_NT) as DK_Co0_NT,
		                        SUM(PS_no0_NT) as PS_NO0_NT,
		                        SUM(PS_co0_NT) as PS_Co0_NT,
		                        SUM(DK_No_NT) as DK_No_NT,
		                        SUM(DK_Co_NT) as DK_Co_NT,
		                        SUM(PS_no_NT) as PS_NO_NT,
		                        SUM(PS_co_NT) as PS_Co_NT,
		                        SUM(ck_No_NT) as ck_No_NT,
		                        SUM(ck_Co_NT) as ck_Co_NT,
		                        0 as FK_GLBankID,
		                        0 as FK_GECurrencyID,
		                        SUM(DK_No0_VND) as DK_No0_VND,
		                        SUM(DK_Co0_VND) as DK_Co0_VND,
		                        SUM(PS_no0_VND) as PS_NO0_VND,
		                        SUM(PS_co0_VND) as PS_Co0_VND,
		                        SUM(DK_No_VND) as DK_No_VND,
		                        SUM(DK_Co_VND) as DK_Co_VND,
		                        SUM(PS_no_VND) as PS_NO_VND,
		                        SUM(PS_co_VND) as PS_Co_VND,
		                        SUM(ck_No_VND) as ck_No_VND,
		                        SUM(ck_Co_VND) as ck_Co_VND
                        INTO #tKQCN
                        FROM #tKQ a
                        INNER JOIN #tGLAccountsNC b ON a.FK_GLAccountID = b.GLAccountID 
                        --WHERE b.GLAccountBalanceCombo = 'NC' --FK_ARCustomerID + FK_APSupplierID + FK_HREmployeeID > 0
                        GROUP BY	FK_GLAccountID

                        --)
                        --(Xoa du lieu ko phat sinh
                        if @bDelEmptyData = 1
                            DELETE FROM #tKQ 
                                WHERE   dk_no = 0 AND dk_co = 0 AND ps_no = 0 AND ps_co = 0 AND ck_no = 0 AND ck_co = 0 AND
                                        dk_no_nt = 0 AND dk_co_nt = 0 AND ps_no_nt = 0 AND ps_co_nt = 0 AND ck_no_nt = 0 AND ck_co_nt = 0
                        --)
                        --(CHi tiet doi tuong
						SELECT * INTO #tKQCTCN 
							FROM #tKQ a 
							--INNER JOIN #tGLAccountsNC b ON a.FK_GLAccountID = b.GLAccountID
							WHERE @bViewObjects = 1
                        --)
											
						DELETE FROM #tKQ 
							WHERE FK_GLAccountID IN (SELECT GLAccountID 
								FROM #tGLAccountsNC)
		
                        INSERT INTO #tKQ 
	                        SELECT * FROM #tKQCN

                        --(Tinh cac toai khoan cha
                        
                        DECLARE @iLevel as int
                        SELECT @iLevel = max(GLAccountLevel)
	                        FROM #t311_341 a INNER JOIN #tKQ b ON a.GLACCountID = b.FK_GLAccountID
	
                        WHILE @iLevel > 1
                        BEGIN

	                        SELECT c.GLAccountID,
		                        SUM(DK_No0) as DK_No0,
		                        SUM(DK_Co0) as DK_Co0,
		                        SUM(PS_NO0) as PS_NO0,
		                        SUM(PS_Co0) as PS_Co0,
		                        SUM(DK_No) as DK_No,
		                        SUM(DK_Co) as DK_Co,
		                        SUM(PS_NO) as PS_NO,
		                        SUM(PS_Co) as PS_Co,
		                        SUM(CK_No) as CK_No,
		                        SUM(CK_Co) as CK_Co,
		                        SUM(DK_No0_NT) as DK_No0_NT,
		                        SUM(DK_Co0_NT) as DK_Co0_NT,
		                        SUM(PS_NO0_NT) as PS_NO0_NT,
		                        SUM(PS_Co0_NT) as PS_Co0_NT,
		                        SUM(DK_No_NT) as DK_No_NT,
		                        SUM(DK_Co_NT) as DK_Co_NT,
		                        SUM(PS_NO_NT) as PS_NO_NT,
		                        SUM(PS_Co_NT) as PS_Co_NT,
		                        SUM(CK_No_NT) as CK_No_NT,
		                        SUM(CK_Co_NT) as CK_Co_NT,
		                        0 as FK_GLBankID,
		                        0 as FK_GECurrencyID,
		                        SUM(DK_No0_VND) as DK_No0_VND,
		                        SUM(DK_Co0_VND) as DK_Co0_VND,
		                        SUM(PS_no0_VND) as PS_NO0_VND,
		                        SUM(PS_co0_VND) as PS_Co0_VND,
		                        SUM(DK_No_VND) as DK_No_VND,
		                        SUM(DK_Co_VND) as DK_Co_VND,
		                        SUM(PS_no_VND) as PS_NO_VND,
		                        SUM(PS_co_VND) as PS_Co_VND,
		                        SUM(ck_No_VND) as ck_No_VND,
		                        SUM(ck_Co_VND) as ck_Co_VND
	                        into #tAppend
	                        FROM #tKQ a INNER JOIN #t311_341 b ON a.FK_GLAccountID = b.GLAccountID
		                        INNER JOIN #t311_341 c ON b.FK_GLAccountParentID = c.GLAccountID
	                        WHERE b.GLAccountLevel = @iLevel
	                        GROUP BY c.GLAccountID
	
	                        if @bKoButru = 0
	                        BEGIN
		                        UPDATE #tAppend SET 
				                        dk_no0 = dk_no0 - dk_co0,
				                        dk_co0 = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_co0 <> 0 AND dk_no0 >= dk_co0
			
		                        UPDATE #tAppend SET 
				                        dk_co0 = dk_co0 - dk_no0,
				                        dk_no0 = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_no0 <> 0 AND dk_co0 >= dk_no0
			                        		
		                        UPDATE #tAppend SET 
				                        dk_no = dk_no - dk_co,
				                        dk_co = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_co <> 0 AND dk_no >= dk_co

		                        UPDATE #tAppend set 
				                        dk_co = dk_co - dk_no,
				                        dk_no = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_no <> 0 AND dk_co >= dk_no
		                        --)

		                        --(Tinh lai so du dau ky va cuoi ky chi tiet 

		                        UPDATE #tAppend SET 
				                        ck_no = ck_no - ck_co,
				                        ck_co = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE ck_co <> 0 AND ck_no >= ck_co			                        

		                        UPDATE #tAppend SET 
				                        ck_co = ck_co - ck_no,
				                        ck_no = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE ck_no <> 0 AND ck_co >= ck_no

		                        --)		
		                        
		                        
		                        --(NT
		                        UPDATE #tAppend SET 
				                        dk_no0_NT = dk_no0_NT - dk_co0_NT,
				                        dk_co0_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_co0_NT <> 0 AND dk_no0_NT >= dk_co0_NT

		                        UPDATE #tAppend SET 
				                        dk_co0_NT = dk_co0_NT - dk_no0_NT,
				                        dk_no0_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_no0_NT <> 0 AND dk_co0_NT >= dk_no0_NT
		
		                        UPDATE #tAppend SET 
				                        dk_no_NT = dk_no_NT - dk_co_NT,
				                        dk_co_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_co_NT <> 0 AND dk_no_NT >= dk_co_NT

		                        UPDATE #tAppend SET 
				                        dk_co_NT = dk_co_NT - dk_no_NT,
				                        dk_no_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE dk_no_NT <> 0 AND dk_co_NT >= dk_no_NT
		                        --)

		                        --(Tinh lai so du dau ky va cuoi ky chi tiet 

		                        UPDATE #tAppend SET 
				                        ck_no_NT = ck_no_NT - ck_co_NT,
				                        ck_co_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE ck_co_NT <> 0 AND ck_no_NT >= ck_co_NT

		                        UPDATE #tAppend SET 
				                        ck_co_NT = ck_co_NT - ck_no_NT,
				                        ck_no_NT = 0
				                    FROM #tAppend a INNER JOIN #tGLAccountsNotNC b ON a.GLAccountID = b.GLAccountID
			                        WHERE ck_no_NT <> 0 AND ck_co_NT >= ck_no_NT
		                        --)		
		                        
		                        
	                        END
	                        INSERT INTO #tKQ 
		                        SELECT * FROM #tAppend
	                        DROP TABLE #tAppend
	                        SET @iLevel = @iLevel - 1			
                        END

                        --(TInh tong cong
                        SELECT 
		                        0 as GLAccountID,
		                        'Total' as GLAccountNo,
		                        'Total' as GLAccountName,
		                        0 as GLAccountLevel,
		                        SUM(DK_No0) as DK_No0,
		                        SUM(DK_Co0) as DK_Co0,
		                        SUM(PS_NO0) as PS_NO0,
		                        SUM(PS_Co0) as PS_Co0,
		                        SUM(DK_No) as DK_No,
		                        SUM(DK_Co) as DK_Co,
		                        SUM(PS_NO) as PS_NO,
		                        SUM(PS_Co) as PS_Co,
		                        SUM(CK_No) as CK_No,
		                        SUM(CK_Co) as CK_Co,
		                        SUM(DK_No0_NT) as DK_No0_NT,
		                        SUM(DK_Co0_NT) as DK_Co0_NT,
		                        SUM(PS_NO0_NT) as PS_NO0_NT,
		                        SUM(PS_Co0_NT) as PS_Co0_NT,
		                        SUM(DK_No_NT) as DK_No_NT,
		                        SUM(DK_Co_NT) as DK_Co_NT,
		                        SUM(PS_NO_NT) as PS_NO_NT,
		                        SUM(PS_Co_NT) as PS_Co_NT,
		                        SUM(CK_No_NT) as CK_No_NT,
		                        SUM(CK_Co_NT) as CK_Co_NT,
		                        0 as FK_GLBankID,
		                        0 as FK_GECurrencyID,
		                        SUM(DK_No0_VND) as DK_No0_VND,
		                        SUM(DK_Co0_VND) as DK_Co0_VND,
		                        SUM(PS_no0_VND) as PS_NO0_VND,
		                        SUM(PS_co0_VND) as PS_Co0_VND,
		                        SUM(DK_No_VND) as DK_No_VND,
		                        SUM(DK_Co_VND) as DK_Co_VND,
		                        SUM(PS_no_VND) as PS_NO_VND,
		                        SUM(PS_co_VND) as PS_Co_VND,
		                        SUM(ck_No_VND) as ck_No_VND,
		                        SUM(ck_Co_VND) as ck_Co_VND
                        INTO #tTotal
                        FROM #tKQ a
                        INNER JOIN #t311_341 b ON a.FK_GLAccountID = b.GLAccountID
                        WHERE b.GLAccountLevel = 1
                        --)

                        --(Ket qua cuoi cung
                        SELECT *
FROM (
                        SELECT 
	                        b.GLAccountID as FK_GLAccountID,
	                        b.GLAccountNo,
	                        b.GLAccountName,
	                        b.GLAccountLevel,
	                        DK_No0 as GLAccountBeginFYDebitAmt,
	                        DK_Co0 as GLAccountBeginFYCreditAmt,
	                        PS_NO0 as GLAccountAccumDebitAmt,
	                        PS_Co0 as GLAccountAccumCreditAmt,
	                        DK_No as GLAccountBeginDebitAmt,
	                        DK_Co as ViewLoanAgreementBeginSumAmt,
	                        PS_No as ViewLoanAgreementSumAmtPmt,
	                        PS_Co as ViewLoanAgreementSumAmtRcpt,
	                        CK_No as GLAccountEndCreditAmt,
	                        CK_Co as ViewLoanAgreementEndSumAmt,
	                        
	                        DK_No0_NT as GLAccountBeginFYDebitFAmt,
	                        DK_Co0_NT as GLAccountBeginFYCreditFAmt,
	                        PS_NO0_NT as PS_NO0_NT,
	                        PS_Co0_NT as PS_Co0_NT,
	                        DK_No_NT as GLAccountBeginDebitFAmt,
	                        DK_Co_NT as ViewLoanAgreementBeginFAmt,
	                        PS_NO_NT as ViewLoanAgreementFAmtPmt,
	                        PS_Co_NT as ViewLoanAgreementFAmtRcpt,
	                        CK_No_NT as GLAccountEndCreditFAmt,
	                        CK_Co_NT as ViewLoanAgreementEndFAmt,
	                        FK_GLBankID,
		                    0 as FK_GECurrencyID,
		                    DK_No0_VND as DK_No0_VND,
		                    DK_Co0_VND as DK_Co0_VND,
		                    PS_no0_VND as PS_NO0_VND,
		                    PS_co0_VND as PS_Co0_VND,
		                    DK_No_VND as DK_No_VND,
		                    DK_Co_VND as ViewLoanAgreementBeginAmt,
		                    PS_no_VND as ViewLoanAgreementAmtPmt,
		                    PS_co_VND as ViewLoanAgreementAmtRcpt,
		                    ck_No_VND as ck_No_VND,
		                    ck_Co_VND as ViewLoanAgreementEndAmt
                        FROM #tKQ a
                        INNER JOIN #t311_341 b ON a.FK_GLAccountID = GLAccountID
                        WHERE (@iViewLevel = 0 OR b.GLAccountLevel <= @iViewLevel)
                        
                        UNION ALL 
                        --(CHi tiet doi tuong
						SELECT b.GLAccountID,
								b.GLAccountNo + '.' + CASE WHEN a.FK_GLBankID > 0 AND c.AAStatus = 'Alive' THEN c.GLBankNo 
									ELSE '<NULL>' END as GLAccountNo,
								CASE WHEN a.FK_GLBankID > 0 THEN c.GLBankName 
									ELSE '<NULL>' END as GLAccountName,
								b.GLAccountLevel + 1,
								DK_No0 as GLAccountBeginFYDebitAmt,
	                        DK_Co0 as GLAccountBeginFYCreditAmt,
	                        PS_NO0 as GLAccountAccumDebitAmt,
	                        PS_Co0 as GLAccountAccumCreditAmt,
	                        DK_No as GLAccountBeginDebitAmt,
	                        DK_Co as ViewLoanAgreementBeginSumAmt,
	                        PS_No as ViewLoanAgreementSumAmtPmt,
	                        PS_Co as ViewLoanAgreementSumAmtRcpt,
	                        CK_No as CK_No,
	                        CK_Co as ViewLoanAgreementEndSumAmt,
	                        
	                        DK_No0_NT as GLAccountBeginFYDebitFAmt,
	                        DK_Co0_NT as GLAccountBeginFYCreditFAmt,
	                        PS_NO0_NT as PS_NO0_NT,
	                        PS_Co0_NT as PS_Co0_NT,
	                        DK_No_NT as GLAccountBeginDebitFAmt,
	                        DK_Co_NT as ViewLoanAgreementBeginFAmt,
	                        PS_NO_NT as ViewLoanAgreementFAmtPmt,
	                        PS_Co_NT as ViewLoanAgreementFAmtRcpt,
	                        CK_No_NT as GLAccountEndDebitFAmt,
	                        CK_Co_NT as ViewLoanAgreementEndFAmt,
	                        FK_GLBankID,
		                    0 as FK_GECurrencyID,
		                    DK_No0_VND as DK_No0_VND,
		                    DK_Co0_VND as DK_Co0_VND,
		                    PS_no0_VND as PS_NO0_VND,
		                    PS_co0_VND as PS_Co0_VND,
		                    DK_No_VND as DK_No_VND,
		                    DK_Co_VND as ViewLoanAgreementBeginAmt,
		                    PS_no_VND as ViewLoanAgreementAmtPmt,
		                    PS_co_VND as ViewLoanAgreementAmtRcpt,
		                    ck_No_VND as ck_No_VND,
		                    ck_Co_VND as ViewLoanAgreementEndAmt
							FROM #tKQCTCN a 
								INNER JOIN #t311_341 b ON a.FK_GLAccountID = b.GLAccountID
								LEFT JOIN GLBanks c ON a.FK_GLBankID = c.GLBankID
                        --)
                        UNION ALL SELECT * FROM #tToTal
                        ) as a
                        ORDER BY GLAccountNo
                        --)                    
", strAccountNo, dtLastStartFiscalYear.ToString("yyyyMMdd"), dtFrom.ToString("yyyyMMdd"), dtTo.ToString("yyyyMMdd"), iLevel
 , Convert.ToSByte(bNotKC911), Convert.ToSByte(bKoButruSDTH), Convert.ToSByte(bDetailObj), Convert.ToSByte(bDelEmptyData)
 , iBranchID);

            DataSet ds = new DataSet();
            ds = GetDataSet(strQuery);

            return ds;
        }
        public DataSet ViewLoanAgreementCalculator(int iLoanAgreementID, DateTime dt)
        {
            string strQuery = string.Format(@"
    SELECT  
        ViewDate ViewLoanAgreementDate,
        ViewRate ViewLoanAgreementRate,
        ViewDesc ViewLoanAgreementDesc,
        ViewAmt ViewLoanAgreementFAmtPmt,
        ViewBalance ViewLoanAgreementBalance,
        ViewAmtRate ViewLoanAgreementAmtRate,
        ViewOldDay ViewLoanAgreementDay
    FROM Fnc_GetLoanAgreementCalculator({0}, '{1}')", iLoanAgreementID, dt.ToString("yyyy-MM-dd"));
            return GetDataSet(strQuery);
        }
        public DataSet ViewLoanAgreements(DateTime dt)
        {
            string strQuery = string.Format(@"
SELECT GLLoanAgreementID AS FK_GLLoanAgreementID,FK_GLBankID AS FK_GLBankID,
    GLLoanAgreementFAmt AS ViewLoanAgreementBeginFAmt,
    GLLoanAgreementRate AS ViewLoanAgreementRate,
    GLLoanAgreementOverRate AS ViewLoanAgreementOverRate,
    GLLoanAgreementFAmt - 
	(SELECT SUM(ViewAmt) FROM Fnc_GetLoanAgreementCalculator(GLLoanAgreementID, '{2}')) ViewLoanAgreementBalance,
	(SELECT SUM(ViewAmt) FROM Fnc_GetLoanAgreementCalculator(GLLoanAgreementID, '{2}')) ViewLoanAgreementFAmtPmt,
    (SELECT SUM(ViewAmtRate) FROM Fnc_GetLoanAgreementCalculator(GLLoanAgreementID, '{2}')) ViewLoanAgreementSumAmtRate,
    (SELECT SUM(ViewAmtRate) FROM Fnc_GetLoanAgreementCalculator(GLLoanAgreementID, '{2}') WHERE MONTH(ViewDate) = {0} AND YEAR(ViewDate) = {1}) ViewLoanAgreementSumRate
FROM GLLoanAgreements WHERE AAStatus = 'Alive'", dt.Month, dt.Year, dt.ToString("yyyy-MM-dd"));
            return GetDataSet(strQuery);
        }
        public DataSet ViewLoanAgreementStatisticSummary(string sBankNo, DateTime dtFrom, DateTime dtTo, int iBranchID = 0, int iLoanAgreementID = 0, int iLoanContractID = 0, int iAccountID = 0)
        {
            return SqlDatabaseHelper.RunStoredProcedure("sp_GetLoanAgreementStatisticSummary", dtFrom, dtTo, iBranchID, iLoanContractID, iLoanAgreementID, iAccountID);
        }
        public DataSet ViewLoanAgreementStatisticDetail(DateTime dtLastStartFiscalYear, DateTime dtFrom, DateTime dtTo, int iLoanAgreementID = 0, int iLoanContractID = 0, int iAccountID = 0)
        {
            return SqlDatabaseHelper.RunStoredProcedure("sp_GetLoanAgreementStatictisDetails", dtLastStartFiscalYear, dtFrom, dtTo, iLoanAgreementID, iLoanContractID, iAccountID);
        }
    }
	#endregion
}