using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ViewConvertLeads
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ViewConvertLeadsController
	//Created Date:24 Tháng Bảy 2012
	//-----------------------------------------------------------
	
	public class ViewConvertLeadsController:BaseBusinessController
	{
		public ViewConvertLeadsController()
		{
			dal= new DALBaseProvider("ViewConvertLeads",typeof(ViewConvertLeadsInfo));
		}
	}
	#endregion
}