using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ARSODocs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ARSODocsController
	//Created Date:23 Tháng Tư 2012
	//-----------------------------------------------------------
	
	public class ARSODocsController:BaseBusinessController
	{
		public ARSODocsController()
		{
			dal= new DALBaseProvider("ARSODocs",typeof(ARSODocsInfo));
		}
	}
	#endregion
}