using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region GLRecurringVoucherItems
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:GLRecurringVoucherItemsInfo
	//Created Date:19 Tháng Tư 2012
	//-----------------------------------------------------------
	
	public class GLRecurringVoucherItemsInfo:BusinessObject
	{
		public GLRecurringVoucherItemsInfo()
		{
		}
		#region Variables
		protected int _gLRecurringVoucherItemID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected int _fK_GLRecurringVoucherID;
		protected int _fK_BRBranchID;
		protected int _fK_BRFBranchID;
		protected int _fK_BRAgentID;
		protected int _fK_ICBrandID;
		protected int _fK_GLCostCenterID;
		protected int _fK_GLDebitAccountID;
		protected int _fK_GLCreditAccountID;
		protected int _fK_GLCreditVATAccountID;
		protected int _fK_GLDebitVATAccountID;
		protected String _gLRecurringVoucherItemDesc=String.Empty;
		protected double _gLRecurringVoucherItemCAmt;
		protected double _gLRecurringVoucherItemAmt;
		protected int _fK_ARCustomerID;
		protected int _fK_APSupplierID;
		protected String _gLRecurringVoucherItemObjectTypeCombo=String.Empty;
		protected int _fK_HREmployeeID;
		protected int _fK_GLJobID;
		protected String _gLRecurringVoucherItemInvNo=String.Empty;
		protected String _gLRecurringVoucherItemInvSeries=String.Empty;
		protected Nullable<DateTime> _gLRecurringVoucherItemInvDate;
		protected String _gLRecurringVoucherItemObjectName=String.Empty;
		protected String _gLRecurringVoucherItemObjectAdd=String.Empty;
		protected int _fK_ICProductID;
		protected int _fK_ICProductGroupID;
		protected int _fK_HRDepartmentID;
		protected int _fK_GLBankID;
		protected double _gLRecurringVoucherItemTaxAmtTot;
		protected int _fK_TXTaxCodeID;
		protected double _gLRecurringVoucherItemTaxCAmtTot;
		protected int _fK_GLObjectID;
		#endregion

		#region Public properties
		public int GLRecurringVoucherItemID
		{
			get{return _gLRecurringVoucherItemID;}
			set
			{
				if (value != this._gLRecurringVoucherItemID)
				{
				_gLRecurringVoucherItemID=value;
				NotifyChanged("GLRecurringVoucherItemID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public int FK_GLRecurringVoucherID
		{
			get{return _fK_GLRecurringVoucherID;}
			set
			{
				if (value != this._fK_GLRecurringVoucherID)
				{
				_fK_GLRecurringVoucherID=value;
				NotifyChanged("FK_GLRecurringVoucherID");
				}
			}
		}
		public int FK_BRBranchID
		{
			get{return _fK_BRBranchID;}
			set
			{
				if (value != this._fK_BRBranchID)
				{
				_fK_BRBranchID=value;
				NotifyChanged("FK_BRBranchID");
				}
			}
		}
		public int FK_BRFBranchID
		{
			get{return _fK_BRFBranchID;}
			set
			{
				if (value != this._fK_BRFBranchID)
				{
				_fK_BRFBranchID=value;
				NotifyChanged("FK_BRFBranchID");
				}
			}
		}
		public int FK_BRAgentID
		{
			get{return _fK_BRAgentID;}
			set
			{
				if (value != this._fK_BRAgentID)
				{
				_fK_BRAgentID=value;
				NotifyChanged("FK_BRAgentID");
				}
			}
		}
		public int FK_ICBrandID
		{
			get{return _fK_ICBrandID;}
			set
			{
				if (value != this._fK_ICBrandID)
				{
				_fK_ICBrandID=value;
				NotifyChanged("FK_ICBrandID");
				}
			}
		}
		public int FK_GLCostCenterID
		{
			get{return _fK_GLCostCenterID;}
			set
			{
				if (value != this._fK_GLCostCenterID)
				{
				_fK_GLCostCenterID=value;
				NotifyChanged("FK_GLCostCenterID");
				}
			}
		}
		public int FK_GLDebitAccountID
		{
			get{return _fK_GLDebitAccountID;}
			set
			{
				if (value != this._fK_GLDebitAccountID)
				{
				_fK_GLDebitAccountID=value;
				NotifyChanged("FK_GLDebitAccountID");
				}
			}
		}
		public int FK_GLCreditAccountID
		{
			get{return _fK_GLCreditAccountID;}
			set
			{
				if (value != this._fK_GLCreditAccountID)
				{
				_fK_GLCreditAccountID=value;
				NotifyChanged("FK_GLCreditAccountID");
				}
			}
		}
		public int FK_GLCreditVATAccountID
		{
			get{return _fK_GLCreditVATAccountID;}
			set
			{
				if (value != this._fK_GLCreditVATAccountID)
				{
				_fK_GLCreditVATAccountID=value;
				NotifyChanged("FK_GLCreditVATAccountID");
				}
			}
		}
		public int FK_GLDebitVATAccountID
		{
			get{return _fK_GLDebitVATAccountID;}
			set
			{
				if (value != this._fK_GLDebitVATAccountID)
				{
				_fK_GLDebitVATAccountID=value;
				NotifyChanged("FK_GLDebitVATAccountID");
				}
			}
		}
		public String GLRecurringVoucherItemDesc
		{
			get{return _gLRecurringVoucherItemDesc;}
			set
			{
				if (value != this._gLRecurringVoucherItemDesc)
				{
				_gLRecurringVoucherItemDesc=value;
				NotifyChanged("GLRecurringVoucherItemDesc");
				}
			}
		}
		public double GLRecurringVoucherItemCAmt
		{
			get{return _gLRecurringVoucherItemCAmt;}
			set
			{
				if (value != this._gLRecurringVoucherItemCAmt)
				{
				_gLRecurringVoucherItemCAmt=value;
				NotifyChanged("GLRecurringVoucherItemCAmt");
				}
			}
		}
		public double GLRecurringVoucherItemAmt
		{
			get{return _gLRecurringVoucherItemAmt;}
			set
			{
				if (value != this._gLRecurringVoucherItemAmt)
				{
				_gLRecurringVoucherItemAmt=value;
				NotifyChanged("GLRecurringVoucherItemAmt");
				}
			}
		}
		public int FK_ARCustomerID
		{
			get{return _fK_ARCustomerID;}
			set
			{
				if (value != this._fK_ARCustomerID)
				{
				_fK_ARCustomerID=value;
				NotifyChanged("FK_ARCustomerID");
				}
			}
		}
		public int FK_APSupplierID
		{
			get{return _fK_APSupplierID;}
			set
			{
				if (value != this._fK_APSupplierID)
				{
				_fK_APSupplierID=value;
				NotifyChanged("FK_APSupplierID");
				}
			}
		}
		public String GLRecurringVoucherItemObjectTypeCombo
		{
			get{return _gLRecurringVoucherItemObjectTypeCombo;}
			set
			{
				if (value != this._gLRecurringVoucherItemObjectTypeCombo)
				{
				_gLRecurringVoucherItemObjectTypeCombo=value;
				NotifyChanged("GLRecurringVoucherItemObjectTypeCombo");
				}
			}
		}
		public int FK_HREmployeeID
		{
			get{return _fK_HREmployeeID;}
			set
			{
				if (value != this._fK_HREmployeeID)
				{
				_fK_HREmployeeID=value;
				NotifyChanged("FK_HREmployeeID");
				}
			}
		}
		public int FK_GLJobID
		{
			get{return _fK_GLJobID;}
			set
			{
				if (value != this._fK_GLJobID)
				{
				_fK_GLJobID=value;
				NotifyChanged("FK_GLJobID");
				}
			}
		}
		public String GLRecurringVoucherItemInvNo
		{
			get{return _gLRecurringVoucherItemInvNo;}
			set
			{
				if (value != this._gLRecurringVoucherItemInvNo)
				{
				_gLRecurringVoucherItemInvNo=value;
				NotifyChanged("GLRecurringVoucherItemInvNo");
				}
			}
		}
		public String GLRecurringVoucherItemInvSeries
		{
			get{return _gLRecurringVoucherItemInvSeries;}
			set
			{
				if (value != this._gLRecurringVoucherItemInvSeries)
				{
				_gLRecurringVoucherItemInvSeries=value;
				NotifyChanged("GLRecurringVoucherItemInvSeries");
				}
			}
		}
		public Nullable<DateTime> GLRecurringVoucherItemInvDate
		{
			get{return _gLRecurringVoucherItemInvDate;}
			set
			{
				if (value != this._gLRecurringVoucherItemInvDate)
				{
				_gLRecurringVoucherItemInvDate=value;
				NotifyChanged("GLRecurringVoucherItemInvDate");
				}
			}
		}
		public String GLRecurringVoucherItemObjectName
		{
			get{return _gLRecurringVoucherItemObjectName;}
			set
			{
				if (value != this._gLRecurringVoucherItemObjectName)
				{
				_gLRecurringVoucherItemObjectName=value;
				NotifyChanged("GLRecurringVoucherItemObjectName");
				}
			}
		}
		public String GLRecurringVoucherItemObjectAdd
		{
			get{return _gLRecurringVoucherItemObjectAdd;}
			set
			{
				if (value != this._gLRecurringVoucherItemObjectAdd)
				{
				_gLRecurringVoucherItemObjectAdd=value;
				NotifyChanged("GLRecurringVoucherItemObjectAdd");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_ICProductGroupID
		{
			get{return _fK_ICProductGroupID;}
			set
			{
				if (value != this._fK_ICProductGroupID)
				{
				_fK_ICProductGroupID=value;
				NotifyChanged("FK_ICProductGroupID");
				}
			}
		}
		public int FK_HRDepartmentID
		{
			get{return _fK_HRDepartmentID;}
			set
			{
				if (value != this._fK_HRDepartmentID)
				{
				_fK_HRDepartmentID=value;
				NotifyChanged("FK_HRDepartmentID");
				}
			}
		}
		public int FK_GLBankID
		{
			get{return _fK_GLBankID;}
			set
			{
				if (value != this._fK_GLBankID)
				{
				_fK_GLBankID=value;
				NotifyChanged("FK_GLBankID");
				}
			}
		}
		public double GLRecurringVoucherItemTaxAmtTot
		{
			get{return _gLRecurringVoucherItemTaxAmtTot;}
			set
			{
				if (value != this._gLRecurringVoucherItemTaxAmtTot)
				{
				_gLRecurringVoucherItemTaxAmtTot=value;
				NotifyChanged("GLRecurringVoucherItemTaxAmtTot");
				}
			}
		}
		public int FK_TXTaxCodeID
		{
			get{return _fK_TXTaxCodeID;}
			set
			{
				if (value != this._fK_TXTaxCodeID)
				{
				_fK_TXTaxCodeID=value;
				NotifyChanged("FK_TXTaxCodeID");
				}
			}
		}
		public double GLRecurringVoucherItemTaxCAmtTot
		{
			get{return _gLRecurringVoucherItemTaxCAmtTot;}
			set
			{
				if (value != this._gLRecurringVoucherItemTaxCAmtTot)
				{
				_gLRecurringVoucherItemTaxCAmtTot=value;
				NotifyChanged("GLRecurringVoucherItemTaxCAmtTot");
				}
			}
		}
		public int FK_GLObjectID
		{
			get{return _fK_GLObjectID;}
			set
			{
				if (value != this._fK_GLObjectID)
				{
				_fK_GLObjectID=value;
				NotifyChanged("FK_GLObjectID");
				}
			}
		}
		#endregion
	}
	#endregion
}