using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ARPkgPlns
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:ARPkgPlnsController
	//Created Date:Monday, November 19, 2012
	//-----------------------------------------------------------
	
	public class ARPkgPlnsController:BaseBusinessController
	{
		public ARPkgPlnsController()
		{
			dal= new DALBaseProvider("ARPkgPlns",typeof(ARPkgPlnsInfo));
		}
	}
	#endregion
}