using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region GEMemoObjections
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:GEMemoObjectionsController
	//Created Date:Thursday, December 25, 2014
	//-----------------------------------------------------------
	
	public class GEMemoObjectionsController:BaseBusinessController
	{
		public GEMemoObjectionsController()
		{
			dal= new DALBaseProvider("GEMemoObjections",typeof(GEMemoObjectionsInfo));
		}
	}
	#endregion
}