using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;


namespace ExpertERP.BusinessEntities
{
	#region A1CompanyConfigs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:A1CompanyConfigsController
	//Created Date:Samstag, 7. Juli 2007
	//-----------------------------------------------------------
	
	public class A1CompanyConfigsController:BaseBusinessController
	{
		public A1CompanyConfigsController()
		{
			dal= new DALBaseProvider("A1CompanyConfigs",typeof(A1CompanyConfigsInfo));
		}
	}
	#endregion
}