using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPCostCenterSteps
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPCostCenterStepsController
	//Created Date:26 Tháng Mười Một 2014
	//-----------------------------------------------------------
	
	public class PPCostCenterStepsController:BaseBusinessController
	{
		public PPCostCenterStepsController()
		{
			dal= new DALBaseProvider("PPCostCenterSteps",typeof(PPCostCenterStepsInfo));
		}

        public DataSet GetAllDataBySortOrder()
        {
            String str = String.Format(@"SELECT * FROM dbo.PPCostCenterSteps
                                        ORDER BY PPCostCenterStepOrder ASC"
                                        );
            return dal.GetDataSet(str);
        }

        public int LayThuTuLonNhatHienCo(int pPPCostCenterStepParentID)
        {
            String str = String.Format(@"SELECT MAX(PPCostCenterStepOrder) FROM PPCostCenterSteps WHERE FK_PPCostCenterStepParentID='{0}'", pPPCostCenterStepParentID);
            DataSet ds = dal.GetDataSet(str);
            if(ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
            {
                return Convert.ToInt32(ds.Tables[0].Rows[0][0]);
            }
            return 0;
        }

        public PPCostCenterStepsInfo GetDataByPPCostCenter(int iPPCostCenterID)
        {
            String str = String.Format(@"SELECT * FROM dbo.PPCostCenterSteps
                                        WHERE FK_PPCostCenterID = {0}"
                                        , iPPCostCenterID);
            DataSet ds = dal.GetDataSet(str);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                return (PPCostCenterStepsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            }
            return null;
        }

        public PPCostCenterStepsInfo GetDataByOrder(int iOrder)
        {
            String str = String.Format(@"SELECT * FROM dbo.PPCostCenterSteps
                                        WHERE PPCostCenterStepOrder = {0}"
                                        , iOrder);
            DataSet ds = dal.GetDataSet(str);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                return (PPCostCenterStepsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            }
            return null;
        }

        #region H.Việt - Lấy những Cost center tồn tại trong phân bổ giá thành - 2017.02.08
        public DataSet GetAllPPCostCenterStepByCostCenterID(int iPeriod, int iYear, string typeCombo, int pPPcostCenterStepParentID)
        {
            string strQuery = string.Format(@"
                                            SELECT * FROM dbo.PPCostCenterSteps
                                            WHERE FK_PPCostCenterID IN (
                                                                        SELECT  FK_PPCostCenterID 
                                                                        FROM    PPCostAllocationItems
                                                                        WHERE   AAStatus = 'Alive'
                                                                        AND FK_PPCostAllocationID IN ( SELECT    PPCostAllocationID
                                                                                                      FROM      dbo.PPCostAllocations
                                                                                                      WHERE     PPPeriod = '{0}'
                                                                                                                AND PPYear = '{1}'
                                                                                                                AND AAStatus = 'Alive'
                                                                                                    )
                                                                        AND PPCostFactorAllocateMthCombo = '{2}'                                                 
                                                                        )			
                                                AND FK_PPCostCenterStepParentID = '{3}'
                                            ORDER BY PPCostCenterStepOrder ASC									
                                            ", iPeriod, iYear, typeCombo,pPPcostCenterStepParentID);
            return GetDataSet(strQuery);
        }
        #endregion

        public DataSet GetAllDataBySortOrder(int iPPCostCenterStepParentID)
        {
            String str = String.Format(@"SELECT * FROM dbo.PPCostCenterSteps
                                        WHERE FK_PPCostCenterStepParentID={0}
                                        ORDER BY PPCostCenterStepOrder ASC"
                                        , iPPCostCenterStepParentID);
            return dal.GetDataSet(str);
        }

    }
	#endregion
}