using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPPeriodColorCfgs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPPeriodColorCfgsController
	//Created Date:27 Tháng Mười Một 2012
	//-----------------------------------------------------------
	
	public class PPPeriodColorCfgsController:BaseBusinessController
	{
		public PPPeriodColorCfgsController()
		{
			dal= new DALBaseProvider("PPPeriodColorCfgs",typeof(PPPeriodColorCfgsInfo));
		}
	}
	#endregion
}