using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPProductionOrgCharts
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPProductionOrgChartsController
	//Created Date:Tuesday, August 19, 2014
	//-----------------------------------------------------------
	
	public class PPProductionOrgChartsController:BaseBusinessController
	{
		public PPProductionOrgChartsController()
		{
			dal= new DALBaseProvider("PPProductionOrgCharts",typeof(PPProductionOrgChartsInfo));
		}

        #region Lấy tất cả dữ liệu theo ProductionOrgCharts --Hiệp

        public DataSet GetAllDataByProductionOrgCharts(int iPPProductionOrgChartID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionOrgCharts
                                            WHERE AAStatus = 'Alive'
                                            AND FK_PPProductionOrgChartParentID = {0}
                                            ", iPPProductionOrgChartID);
            return dal.GetDataSet(str);
        }

        public PPProductionOrgChartsInfo LayCapSanXuatCuoi(int iPPProductionOrgChartID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionOrgCharts
                                            WHERE PPProductionOrgChartID in(
									                                        SELECT FK_PPProductionOrgChartParentID
									                                        FROM dbo.PPProductionOrgCharts
									                                        WHERE FK_PPProductionOrgChartParentID={0}
									                                        AND FK_PPWorkCenterID=0
                                                                            AND AAStatus='Alive'
											)
                                            ", iPPProductionOrgChartID);
            DataSet ds = GetDataSet(str);

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return (PPProductionOrgChartsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return null;
        }

        public PPProductionOrgChartsInfo LayCapSanXuatCuoiCoBoPhan(int iPPProductionOrgChartID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionOrgCharts
                                            WHERE PPProductionOrgChartID in(
									                                        SELECT FK_PPProductionOrgChartParentID
									                                        FROM dbo.PPProductionOrgCharts
									                                        WHERE FK_PPProductionOrgChartParentID={0}
									                                        AND FK_PPWorkCenterID<>0
                                                                            AND AAStatus='Alive'
											)
                                            ", iPPProductionOrgChartID);
            DataSet ds = GetDataSet(str);

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return (PPProductionOrgChartsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return null;
        }

        public PPProductionOrgChartsInfo LayBoPhanCuaCapSanXuat(int iPPProductionOrgChartID, int iPPWordCenterID)
        {
             String str = String.Format(@"   SELECT * FROM dbo.PPProductionOrgCharts
                                             WHERE FK_PPWorkCenterID={1} 
                                             AND FK_PPProductionOrgChartParentID={0}
                                             AND AAStatus='Alive'
                                            ", iPPProductionOrgChartID, iPPWordCenterID);
            DataSet ds = GetDataSet(str);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return (PPProductionOrgChartsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return null;
        }
        #endregion
	}
	#endregion
}