using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPProductionCostCenterActives
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPProductionCostCenterActivesController
	//Created Date:28 Tháng Mười Một 2014
	//-----------------------------------------------------------
	
	public class PPProductionCostCenterActivesController:BaseBusinessController
	{
		public PPProductionCostCenterActivesController()
		{
			dal= new DALBaseProvider("PPProductionCostCenterActives",typeof(PPProductionCostCenterActivesInfo));
		}

        public void DeleteAllDataByYearANDPeriod(int iYear, int iPeriod)
        {
            String str = String.Format(@"   DELETE dbo.PPProductionCostCenterActives
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}"
                                            , iYear, iPeriod);
            dal.GetDataSet(str);
        }

        public DataSet GetAllDataByYearANDPeriod(int iYear, int iPeriod)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostCenterActives
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}"
                                            , iYear, iPeriod);
            return dal.GetDataSet(str);
        }

        public DataSet GetAllDataByYearANDPeriod(int iYear, int iPeriod, int iPPCostCenterID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostCenterActives
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}
                                            AND FK_PPCostCenterID = {2}"
                                            , iYear, iPeriod, iPPCostCenterID);
            return dal.GetDataSet(str);
        }

        public int GetMaxOrderByYearANDPeriod(int iYear, int iPeriod)
        {
            String str = String.Format(@"   SELECT MAX(PPProductionCostCenterActiveOrder) FROM dbo.PPProductionCostCenterActives
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}"
                                            , iYear, iPeriod);
            DataSet ds = dal.GetDataSet(str);
            if(ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
            {
                return Convert.ToInt32(ds.Tables[0].Rows[0][0]);
            }

            return 0;
        }
	}
	#endregion
}