using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPProductionCostStatisticItems
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPProductionCostStatisticItemsController
	//Created Date:24 Tháng Mười Một 2014
	//-----------------------------------------------------------
	
	public class PPProductionCostStatisticItemsController:BaseBusinessController
	{
		public PPProductionCostStatisticItemsController()
		{
			dal= new DALBaseProvider("PPProductionCostStatisticItems",typeof(PPProductionCostStatisticItemsInfo));
		}

        public void DeleteAllDataByYearANDPeriod(int iYear, int iPeriod)
        {
            String str = String.Format(@"   DELETE dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}"
                                            , iYear, iPeriod);
            dal.GetDataSet(str);
        }

        public void DeleteAllDataByYearANDPeriod(int iYear, int iPeriod, int iPPProductionCostCenterID)
        {
            String str = String.Format(@"   DELETE dbo.PPProductionCostStatisticItems
                                            WHERE   PPYear = {0}
                                                    AND PPPeriod = {1}
                                                    AND FK_PPProductionCostStatisticID IN (
                                                                                            SELECT  PPProductionCostStatisticID
                                                                                            FROM    dbo.PPProductionCostStatistics
                                                                                            WHERE   PPYear = {0}
                                                                                                    AND PPPeriod = {1}
                                                                                                    AND FK_PPProductionCostCenterID = {2} 
                                                                                          )"
                                            , iYear, iPeriod, iPPProductionCostCenterID);
            dal.GetDataSet(str);
        }

        public void DeleteAllDataByYearANDPeriod(int iYear, int iPeriod, String strTypeCombo)
        {
            String str = String.Format(@"   DELETE dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}
                                            AND PPProductionCostStatisticItemTypeCombo = '{2}'"
                                            , iYear, iPeriod, strTypeCombo);
            dal.GetDataSet(str);
        }
        
        public void DeleteAllDataByYearANDPeriod(int iYear, int iPeriod, int iPPProductionCostCenterID, String strTypeCombo)
        {
            String str = String.Format(@"   DELETE dbo.PPProductionCostStatisticItems
                                            WHERE   PPYear = {0}
                                                    AND PPPeriod = {1}
                                                    AND PPProductionCostStatisticItemTypeCombo = '{2}'
                                                    AND FK_PPProductionCostStatisticID IN (
                                                                                            SELECT  PPProductionCostStatisticID
                                                                                            FROM    dbo.PPProductionCostStatistics
                                                                                            WHERE   PPYear = {0}
                                                                                                    AND PPPeriod = {1}
                                                                                                    AND FK_PPProductionCostCenterID = {3} 
                                                                                          )"
                                            , iYear, iPeriod, strTypeCombo, iPPProductionCostCenterID);
            dal.GetDataSet(str);
        }

        public DataSet GetAllDataByYearANDPeriod(int iYear, int iPeriod, int iPPProductionCostCenterID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostStatisticItems
                                            WHERE   PPYear = {0}
                                                    AND PPPeriod = {1}
                                                    AND FK_PPProductionCostStatisticID IN (
                                                                                            SELECT  PPProductionCostStatisticID
                                                                                            FROM    dbo.PPProductionCostStatistics
                                                                                            WHERE   PPYear = {0}
                                                                                                    AND PPPeriod = {1}
                                                                                                    AND FK_PPProductionCostCenterID = {2}
                                                                                          )"
                                            , iYear, iPeriod, iPPProductionCostCenterID);
            return dal.GetDataSet(str);
        }

        public DataSet GetAllDataByYearANDPeriod(int iYear, int iPeriod)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}"
                                            , iYear, iPeriod);
            return dal.GetDataSet(str);
        }
        public DataSet GetAllDataByYearANDPeriod(int iYear, int iPeriod, String strTypeCombo)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}
                                            AND PPProductionCostStatisticItemTypeCombo = '{2}'"
                                            , iYear, iPeriod, strTypeCombo);
            return dal.GetDataSet(str);
        }
        public DataSet GetAllDataCostStatisticByYearANDPeriod(int iYear, int iPeriod, int iPPProductionCostStatisticID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}
                                            AND FK_PPProductionCostStatisticID = {2}"
                                            , iYear, iPeriod, iPPProductionCostStatisticID);
            return dal.GetDataSet(str);
        }

        public Boolean CheckDataInYearANDPeriod(int iYear, int iPeriod, String strTypeCombo = "")
        {
            DataSet ds = null;
            if (String.IsNullOrEmpty(strTypeCombo))
                ds = GetAllDataByYearANDPeriod(iYear, iPeriod);
            else
                ds = GetAllDataByYearANDPeriod(iYear, iPeriod, strTypeCombo);

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0) return true;

            return false;
        }

        public Boolean CheckDataInYearANDPeriod(int iYear, int iPeriod, int iPPProductionCostCenterID)
        {
            DataSet ds = GetAllDataByYearANDPeriod(iYear, iPeriod, iPPProductionCostCenterID);

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0) return true;

            return false;
        }

        public DataSet LayTatCaYTCPCoPhanBoTrongKy(int iYear, int iPeriod, String strPPProductionCostFactorTypeCombo)
        {
            String str = String.Format(@"SELECT DISTINCT dbo.PPProductionCostFactors.*
                                        FROM    dbo.PPProductionCostStatisticItems
                                                INNER JOIN dbo.PPProductionCostFactors ON ( PPProductionCostFactors.PPProductionCostFactorID = PPProductionCostStatisticItems.FK_PPProductionCostFactorID
                                                                                            AND PPProductionCostFactors.PPYear = PPProductionCostStatisticItems.PPYear
                                                                                            AND PPProductionCostFactors.PPPeriod = PPProductionCostStatisticItems.PPPeriod
                                                                                          )
                                        WHERE   PPProductionCostStatisticItems.PPYear = {0}
                                                AND PPProductionCostStatisticItems.PPPeriod = {1}
                                                AND PPProductionCostFactorTypeCombo = '{2}'"
                                        , iYear, iPeriod, strPPProductionCostFactorTypeCombo);
            return dal.GetDataSet(str);
        }

        public double LayTongSoTienCuaThongKeSanXuat(int iYear, int iPeriod, int iPPProductionCostStatisticID)
        {
            String str = String.Format(@"SELECT SUM(PPProductionCostStatisticItemAmt) FROM dbo.PPProductionCostStatisticItems
                                            WHERE PPYear = {0}
                                            AND PPPeriod = {1}
                                            AND FK_PPProductionCostStatisticID = {2}"
                                        , iYear, iPeriod, iPPProductionCostStatisticID);
            DataSet ds = dal.GetDataSet(str);
            if(ds!= null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
            {
                return Convert.ToDouble(ds.Tables[0].Rows[0][0]);
            }
            return 0;
        }
        
        public double LayTongSoTienCuaThongKeSanXuat(int iYear, int iPeriod, int iPPProductionCostStatisticID, String strFactorTypeCombo)
        {
            String str = String.Format(@"SELECT  SUM(PPProductionCostStatisticItemAmt) AS PPProductionCostStatisticItemAmt
                                        FROM    dbo.PPProductionCostStatisticItems
                                                INNER JOIN dbo.PPProductionCostStatistics ON ( PPProductionCostStatistics.PPProductionCostStatisticID = PPProductionCostStatisticItems.FK_PPProductionCostStatisticID
                                                                                               AND PPProductionCostStatistics.PPPeriod = PPProductionCostStatisticItems.PPPeriod
                                                                                               AND PPProductionCostStatistics.PPYear = PPProductionCostStatisticItems.PPYear
                                                                                               AND PPProductionCostStatistics.PPYear = {0}
                                                                                               AND PPProductionCostStatistics.PPPeriod = {1}
                                                                                               AND PPProductionCostStatistics.PPProductionCostStatisticID = {2}
                                                                                             )
                                                INNER JOIN dbo.PPProductionCostFactors ON ( PPProductionCostFactors.PPProductionCostFactorID = PPProductionCostStatisticItems.FK_PPProductionCostFactorID
                                                                                            AND PPProductionCostFactors.FK_PPCostFactorID = PPProductionCostStatisticItems.FK_PPCostFactorID
                                                                                            AND PPProductionCostFactors.PPPeriod = PPProductionCostStatistics.PPPeriod
                                                                                            AND PPProductionCostFactors.PPYear = PPProductionCostStatistics.PPYear
                                                                                            AND PPProductionCostFactorTypeCombo = '{3}'
                                                                                          )"
                                        , iYear, iPeriod, iPPProductionCostStatisticID, strFactorTypeCombo);
            DataSet ds = dal.GetDataSet(str);
            if(ds!= null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
            {
                return Convert.ToDouble(ds.Tables[0].Rows[0][0]);
            }
            return 0;
        }
	}
	#endregion
}