using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
    #region ViewApprovalComments
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:ViewApprovalCommentsInfo
    //Created Date:03 Tháng Mười Hai 2012
    //-----------------------------------------------------------

    public class ViewApprovalCommentsInfo : BusinessObject
    {
        public ViewApprovalCommentsInfo()
        {
        }
        #region Variables
        protected int _viewApprovalCommentID;
        protected int _fK_GLVoucherID;
        protected String _user1 = String.Empty;
        protected String _comment1 = String.Empty;
        protected String _user2 = String.Empty;
        protected String _comment2 = String.Empty;
        protected String _user3 = String.Empty;
        protected String _comment3 = String.Empty;
        protected String _user4 = String.Empty;
        protected String _comment4 = String.Empty;
        protected String _employee1 = String.Empty;
        protected String _employee2 = String.Empty;
        protected String _employee3 = String.Empty;
        protected String _employee4 = String.Empty;
        #endregion

        #region Public properties
        public int ViewApprovalCommentID
        {
            get { return _viewApprovalCommentID; }
            set
            {
                if (value != this._viewApprovalCommentID)
                {
                    _viewApprovalCommentID = value;
                    NotifyChanged("ViewApprovalCommentID");
                }
            }
        }
        public int FK_GLVoucherID
        {
            get { return _fK_GLVoucherID; }
            set
            {
                if (value != this._fK_GLVoucherID)
                {
                    _fK_GLVoucherID = value;
                    NotifyChanged("FK_GLVoucherID");
                }
            }
        }
        public String User1
        {
            get { return _user1; }
            set
            {
                if (value != this._user1)
                {
                    _user1 = value;
                    NotifyChanged("User1");
                }
            }
        }
        public String Comment1
        {
            get { return _comment1; }
            set
            {
                if (value != this._comment1)
                {
                    _comment1 = value;
                    NotifyChanged("Comment1");
                }
            }
        }
        public String User2
        {
            get { return _user2; }
            set
            {
                if (value != this._user2)
                {
                    _user2 = value;
                    NotifyChanged("User2");
                }
            }
        }
        public String Comment2
        {
            get { return _comment2; }
            set
            {
                if (value != this._comment2)
                {
                    _comment2 = value;
                    NotifyChanged("Comment2");
                }
            }
        }
        public String User3
        {
            get { return _user3; }
            set
            {
                if (value != this._user3)
                {
                    _user3 = value;
                    NotifyChanged("User3");
                }
            }
        }
        public String Comment3
        {
            get { return _comment3; }
            set
            {
                if (value != this._comment3)
                {
                    _comment3 = value;
                    NotifyChanged("Comment3");
                }
            }
        }
        public String User4
        {
            get { return _user4; }
            set
            {
                if (value != this._user4)
                {
                    _user4 = value;
                    NotifyChanged("User4");
                }
            }
        }
        public String Comment4
        {
            get { return _comment4; }
            set
            {
                if (value != this._comment4)
                {
                    _comment4 = value;
                    NotifyChanged("Comment4");
                }
            }
        }
        public String Employee1
        {
            get { return _employee1; }
            set
            {
                if (value != this._employee1)
                {
                    _employee1 = value;
                    NotifyChanged("Employee1");
                }
            }
        }
        public String Employee2
        {
            get { return _employee2; }
            set
            {
                if (value != this._employee2)
                {
                    _employee2 = value;
                    NotifyChanged("Employee2");
                }
            }
        }
        public String Employee3
        {
            get { return _employee3; }
            set
            {
                if (value != this._employee3)
                {
                    _employee3 = value;
                    NotifyChanged("Employee3");
                }
            }
        }
        public String Employee4
        {
            get { return _employee4; }
            set
            {
                if (value != this._employee4)
                {
                    _employee4 = value;
                    NotifyChanged("Employee4");
                }
            }
        }
        #endregion
    }
    #endregion
}