using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ViewDocumentComments
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ViewDocumentCommentsInfo
	//Created Date:09 Tháng Tám 2012
	//-----------------------------------------------------------
	
	public class ViewDocumentCommentsInfo:BusinessObject
	{
		public ViewDocumentCommentsInfo()
		{
		}
		#region Variables
		protected int _viewDocumentCommentID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected int _fK_ARInvoiceID;
		protected String _action=String.Empty;
		protected int _fK_ADUserID;
		protected Nullable<DateTime> _issueDate;
		protected String _commentRemark=String.Empty;
		protected int _fK_ADApprovalProcID;
		protected int _fK_ADApprovalProcStepID;
		protected String _docNo=String.Empty;
		protected String _docType=String.Empty;
		protected String _docStatusCombo=DefaultStatus;
		#endregion

		#region Public properties
		public int ViewDocumentCommentID
		{
			get{return _viewDocumentCommentID;}
			set
			{
				if (value != this._viewDocumentCommentID)
				{
				_viewDocumentCommentID=value;
				NotifyChanged("ViewDocumentCommentID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public int FK_ARInvoiceID
		{
			get{return _fK_ARInvoiceID;}
			set
			{
				if (value != this._fK_ARInvoiceID)
				{
				_fK_ARInvoiceID=value;
				NotifyChanged("FK_ARInvoiceID");
				}
			}
		}
		public String Action
		{
			get{return _action;}
			set
			{
				if (value != this._action)
				{
				_action=value;
				NotifyChanged("Action");
				}
			}
		}
		public int FK_ADUserID
		{
			get{return _fK_ADUserID;}
			set
			{
				if (value != this._fK_ADUserID)
				{
				_fK_ADUserID=value;
				NotifyChanged("FK_ADUserID");
				}
			}
		}
		public Nullable<DateTime> IssueDate
		{
			get{return _issueDate;}
			set
			{
				if (value != this._issueDate)
				{
				_issueDate=value;
				NotifyChanged("IssueDate");
				}
			}
		}
		public String CommentRemark
		{
			get{return _commentRemark;}
			set
			{
				if (value != this._commentRemark)
				{
				_commentRemark=value;
				NotifyChanged("CommentRemark");
				}
			}
		}
		public int FK_ADApprovalProcID
		{
			get{return _fK_ADApprovalProcID;}
			set
			{
				if (value != this._fK_ADApprovalProcID)
				{
				_fK_ADApprovalProcID=value;
				NotifyChanged("FK_ADApprovalProcID");
				}
			}
		}
		public int FK_ADApprovalProcStepID
		{
			get{return _fK_ADApprovalProcStepID;}
			set
			{
				if (value != this._fK_ADApprovalProcStepID)
				{
				_fK_ADApprovalProcStepID=value;
				NotifyChanged("FK_ADApprovalProcStepID");
				}
			}
		}
		public String DocNo
		{
			get{return _docNo;}
			set
			{
				if (value != this._docNo)
				{
				_docNo=value;
				NotifyChanged("DocNo");
				}
			}
		}
		public String DocType
		{
			get{return _docType;}
			set
			{
				if (value != this._docType)
				{
				_docType=value;
				NotifyChanged("DocType");
				}
			}
		}
		public String DocStatusCombo
		{
			get{return _docStatusCombo;}
			set
			{
				if (value != this._docStatusCombo)
				{
				_docStatusCombo=value;
				NotifyChanged("DocStatusCombo");
				}
			}
		}
		#endregion
	}
	#endregion
}