using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ViewObjectBalances
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ViewObjectBalancesInfo
	//Created Date:29 Tháng Mười Hai 2012
	//-----------------------------------------------------------
	
	public class ViewObjectBalancesInfo:BusinessObject
	{
		public ViewObjectBalancesInfo()
		{
		}
		#region Variables
		protected int _viewObjectBalanceID;
		protected int _viewObjectOpenBalanceID;
		protected int _fK_GLAccountID;
		protected double _debitAmt;
		protected double _creditAmt;
		#endregion

		#region Public properties
		public int ViewObjectBalanceID
		{
			get{return _viewObjectBalanceID;}
			set
			{
				if (value != this._viewObjectBalanceID)
				{
				_viewObjectBalanceID=value;
				NotifyChanged("ViewObjectBalanceID");
				}
			}
		}
		public int ViewObjectOpenBalanceID
		{
			get{return _viewObjectOpenBalanceID;}
			set
			{
				if (value != this._viewObjectOpenBalanceID)
				{
				_viewObjectOpenBalanceID=value;
				NotifyChanged("ViewObjectOpenBalanceID");
				}
			}
		}
		public int FK_GLAccountID
		{
			get{return _fK_GLAccountID;}
			set
			{
				if (value != this._fK_GLAccountID)
				{
				_fK_GLAccountID=value;
				NotifyChanged("FK_GLAccountID");
				}
			}
		}
		public double DebitAmt
		{
			get{return _debitAmt;}
			set
			{
				if (value != this._debitAmt)
				{
				_debitAmt=value;
				NotifyChanged("DebitAmt");
				}
			}
		}
		public double CreditAmt
		{
			get{return _creditAmt;}
			set
			{
				if (value != this._creditAmt)
				{
				_creditAmt=value;
				NotifyChanged("CreditAmt");
				}
			}
		}
		#endregion
	}
	#endregion
}