using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ICProductBOMs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ICProductBOMsController
	//Created Date:Tuesday, February 24, 2009
	//-----------------------------------------------------------
	
	public class ICProductBOMsController:BaseBusinessController
	{
		public ICProductBOMsController()
		{
			dal= new DALBaseProvider("ICProductBOMs",typeof(ICProductBOMsInfo));
		}
	}
	#endregion
}