using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ICTransferPostings
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:ICTransferPostingsInfo
	//Created Date:Wednesday, November 24, 2010
	//-----------------------------------------------------------
	
	public class ICTransferPostingsInfo:BusinessObject
	{
		public ICTransferPostingsInfo()
		{
		}
		#region Variables
		protected int _iCTransferPostingID;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected int _fK_ICTransferItemID;
		protected int _fK_ICTransferID;
		protected int _fK_ICProductID;
		protected int _fK_ICFromStockID;
		protected int _fK_ICToStockID;
		protected double _iCTransferItemQty;
		protected double _iCTransferItemStkQty;
		protected String _iCTransferItemStatus=DefaultStatus;
		protected String _iCTransferItemSerialNo=String.Empty;
		#endregion

		#region Public properties
		public int ICTransferPostingID
		{
			get{return _iCTransferPostingID;}
			set
			{
				if (value != this._iCTransferPostingID)
				{
				_iCTransferPostingID=value;
				NotifyChanged("ICTransferPostingID");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public int FK_ICTransferItemID
		{
			get{return _fK_ICTransferItemID;}
			set
			{
				if (value != this._fK_ICTransferItemID)
				{
				_fK_ICTransferItemID=value;
				NotifyChanged("FK_ICTransferItemID");
				}
			}
		}
		public int FK_ICTransferID
		{
			get{return _fK_ICTransferID;}
			set
			{
				if (value != this._fK_ICTransferID)
				{
				_fK_ICTransferID=value;
				NotifyChanged("FK_ICTransferID");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_ICFromStockID
		{
			get{return _fK_ICFromStockID;}
			set
			{
				if (value != this._fK_ICFromStockID)
				{
				_fK_ICFromStockID=value;
				NotifyChanged("FK_ICFromStockID");
				}
			}
		}
		public int FK_ICToStockID
		{
			get{return _fK_ICToStockID;}
			set
			{
				if (value != this._fK_ICToStockID)
				{
				_fK_ICToStockID=value;
				NotifyChanged("FK_ICToStockID");
				}
			}
		}
		public double ICTransferItemQty
		{
			get{return _iCTransferItemQty;}
			set
			{
				if (value != this._iCTransferItemQty)
				{
				_iCTransferItemQty=value;
				NotifyChanged("ICTransferItemQty");
				}
			}
		}
		public double ICTransferItemStkQty
		{
			get{return _iCTransferItemStkQty;}
			set
			{
				if (value != this._iCTransferItemStkQty)
				{
				_iCTransferItemStkQty=value;
				NotifyChanged("ICTransferItemStkQty");
				}
			}
		}
		public String ICTransferItemStatus
		{
			get{return _iCTransferItemStatus;}
			set
			{
				if (value != this._iCTransferItemStatus)
				{
				_iCTransferItemStatus=value;
				NotifyChanged("ICTransferItemStatus");
				}
			}
		}
		public String ICTransferItemSerialNo
		{
			get{return _iCTransferItemSerialNo;}
			set
			{
				if (value != this._iCTransferItemSerialNo)
				{
				_iCTransferItemSerialNo=value;
				NotifyChanged("ICTransferItemSerialNo");
				}
			}
		}
		#endregion
	}
	#endregion
}