using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPCostFactors
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:PPCostFactorsInfo
	//Created Date:Wednesday, January 7, 2015
	//-----------------------------------------------------------
	
	public class PPCostFactorsInfo:BusinessObject
	{
		public PPCostFactorsInfo()
		{
		}
		#region Variables
		protected int _pPCostFactorID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected String _pPCostFactorNo=String.Empty;
		protected String _pPCostFactorName=String.Empty;
		protected String _pPCostFactorDesc=String.Empty;
		protected String _pPCostFactorTypeCombo=String.Empty;
		#endregion

		#region Public properties
		public int PPCostFactorID
		{
			get{return _pPCostFactorID;}
			set
			{
				if (value != this._pPCostFactorID)
				{
				_pPCostFactorID=value;
				NotifyChanged("PPCostFactorID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public String PPCostFactorNo
		{
			get{return _pPCostFactorNo;}
			set
			{
				if (value != this._pPCostFactorNo)
				{
				_pPCostFactorNo=value;
				NotifyChanged("PPCostFactorNo");
				}
			}
		}
		public String PPCostFactorName
		{
			get{return _pPCostFactorName;}
			set
			{
				if (value != this._pPCostFactorName)
				{
				_pPCostFactorName=value;
				NotifyChanged("PPCostFactorName");
				}
			}
		}
		public String PPCostFactorDesc
		{
			get{return _pPCostFactorDesc;}
			set
			{
				if (value != this._pPCostFactorDesc)
				{
				_pPCostFactorDesc=value;
				NotifyChanged("PPCostFactorDesc");
				}
			}
		}
		public String PPCostFactorTypeCombo
		{
			get{return _pPCostFactorTypeCombo;}
			set
			{
				if (value != this._pPCostFactorTypeCombo)
				{
				_pPCostFactorTypeCombo=value;
				NotifyChanged("PPCostFactorTypeCombo");
				}
			}
		}
		#endregion
	}
	#endregion
}