using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPInComOverheads
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:PPInComOverheadsInfo
	//Created Date:Thursday, August 23, 2012
	//-----------------------------------------------------------
	
	public class PPInComOverheadsInfo:BusinessObject
	{
		public PPInComOverheadsInfo()
		{
		}
		#region Variables
		protected int _pPInComOverheadID;
		protected int _fK_ICProductID;
		protected int _fK_ICReceiptID;
		protected int _fK_ICReceiptItemID;
		protected int _fK_PPPhaseCfgID;
		protected double _pPInComFGQty;
		protected double _pPPhaseCfgFactor;
		protected double _pPInComFGUnitPrice;
		protected double _pPInComFGPhaseQty;
		protected double _pPInComAllocateFGQty;
		protected double _pPBeginInComOverheadCost;
		protected double _pPInComDirectOverheadCost;
		protected double _pPInComProductGroupOverheadCost;
		protected double _pPInComIndirectOverheadCost;
		protected double _pPPSOverheadCost;
		protected double _pPInComOverheadCost;
		protected int _pPPeriod;
		protected int _pPYear;
		#endregion

		#region Public properties
		public int PPInComOverheadID
		{
			get{return _pPInComOverheadID;}
			set
			{
				if (value != this._pPInComOverheadID)
				{
				_pPInComOverheadID=value;
				NotifyChanged("PPInComOverheadID");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_ICReceiptID
		{
			get{return _fK_ICReceiptID;}
			set
			{
				if (value != this._fK_ICReceiptID)
				{
				_fK_ICReceiptID=value;
				NotifyChanged("FK_ICReceiptID");
				}
			}
		}
		public int FK_ICReceiptItemID
		{
			get{return _fK_ICReceiptItemID;}
			set
			{
				if (value != this._fK_ICReceiptItemID)
				{
				_fK_ICReceiptItemID=value;
				NotifyChanged("FK_ICReceiptItemID");
				}
			}
		}
		public int FK_PPPhaseCfgID
		{
			get{return _fK_PPPhaseCfgID;}
			set
			{
				if (value != this._fK_PPPhaseCfgID)
				{
				_fK_PPPhaseCfgID=value;
				NotifyChanged("FK_PPPhaseCfgID");
				}
			}
		}
		public double PPInComFGQty
		{
			get{return _pPInComFGQty;}
			set
			{
				if (value != this._pPInComFGQty)
				{
				_pPInComFGQty=value;
				NotifyChanged("PPInComFGQty");
				}
			}
		}
		public double PPPhaseCfgFactor
		{
			get{return _pPPhaseCfgFactor;}
			set
			{
				if (value != this._pPPhaseCfgFactor)
				{
				_pPPhaseCfgFactor=value;
				NotifyChanged("PPPhaseCfgFactor");
				}
			}
		}
		public double PPInComFGUnitPrice
		{
			get{return _pPInComFGUnitPrice;}
			set
			{
				if (value != this._pPInComFGUnitPrice)
				{
				_pPInComFGUnitPrice=value;
				NotifyChanged("PPInComFGUnitPrice");
				}
			}
		}
		public double PPInComFGPhaseQty
		{
			get{return _pPInComFGPhaseQty;}
			set
			{
				if (value != this._pPInComFGPhaseQty)
				{
				_pPInComFGPhaseQty=value;
				NotifyChanged("PPInComFGPhaseQty");
				}
			}
		}
		public double PPInComAllocateFGQty
		{
			get{return _pPInComAllocateFGQty;}
			set
			{
				if (value != this._pPInComAllocateFGQty)
				{
				_pPInComAllocateFGQty=value;
				NotifyChanged("PPInComAllocateFGQty");
				}
			}
		}
		public double PPBeginInComOverheadCost
		{
			get{return _pPBeginInComOverheadCost;}
			set
			{
				if (value != this._pPBeginInComOverheadCost)
				{
				_pPBeginInComOverheadCost=value;
				NotifyChanged("PPBeginInComOverheadCost");
				}
			}
		}
		public double PPInComDirectOverheadCost
		{
			get{return _pPInComDirectOverheadCost;}
			set
			{
				if (value != this._pPInComDirectOverheadCost)
				{
				_pPInComDirectOverheadCost=value;
				NotifyChanged("PPInComDirectOverheadCost");
				}
			}
		}
		public double PPInComProductGroupOverheadCost
		{
			get{return _pPInComProductGroupOverheadCost;}
			set
			{
				if (value != this._pPInComProductGroupOverheadCost)
				{
				_pPInComProductGroupOverheadCost=value;
				NotifyChanged("PPInComProductGroupOverheadCost");
				}
			}
		}
		public double PPInComIndirectOverheadCost
		{
			get{return _pPInComIndirectOverheadCost;}
			set
			{
				if (value != this._pPInComIndirectOverheadCost)
				{
				_pPInComIndirectOverheadCost=value;
				NotifyChanged("PPInComIndirectOverheadCost");
				}
			}
		}
		public double PPPSOverheadCost
		{
			get{return _pPPSOverheadCost;}
			set
			{
				if (value != this._pPPSOverheadCost)
				{
				_pPPSOverheadCost=value;
				NotifyChanged("PPPSOverheadCost");
				}
			}
		}
		public double PPInComOverheadCost
		{
			get{return _pPInComOverheadCost;}
			set
			{
				if (value != this._pPInComOverheadCost)
				{
				_pPInComOverheadCost=value;
				NotifyChanged("PPInComOverheadCost");
				}
			}
		}
		public int PPPeriod
		{
			get{return _pPPeriod;}
			set
			{
				if (value != this._pPPeriod)
				{
				_pPPeriod=value;
				NotifyChanged("PPPeriod");
				}
			}
		}
		public int PPYear
		{
			get{return _pPYear;}
			set
			{
				if (value != this._pPYear)
				{
				_pPYear=value;
				NotifyChanged("PPYear");
				}
			}
		}
		#endregion
	}
	#endregion
}