using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPPeriodColorCfgs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPPeriodColorCfgsInfo
	//Created Date:27 Tháng Mười Một 2012
	//-----------------------------------------------------------
	
	public class PPPeriodColorCfgsInfo:BusinessObject
	{
		public PPPeriodColorCfgsInfo()
		{
		}
		#region Variables
		protected int _pPPeriodColorCfgID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected int _pPPeriodColorCfgPeriod1;
		protected int _pPPeriodColorCfgPeriod2;
		protected int _pPPeriodColorCfgPeriod3;
		protected int _pPPeriodColorCfgPeriod4;
		protected int _pPPeriodColorCfgPeriod5;
		protected int _pPPeriodColorCfgPeriod6;
		protected int _pPPeriodColorCfgPeriod7;
		protected int _pPPeriodColorCfgPeriod8;
		protected int _pPPeriodColorCfgPeriod9;
		protected int _pPPeriodColorCfgPeriod10;
		protected int _pPPeriodColorCfgPeriod11;
		protected int _pPPeriodColorCfgPeriod12;
		protected int _pPPeriodColorCfgPeriod13;
		protected int _pPPeriodColorCfgPeriod14;
		protected int _pPPeriodColorCfgPeriod15;
		protected String _aAStatus=DefaultAAStatus;
		#endregion

		#region Public properties
		public int PPPeriodColorCfgID
		{
			get{return _pPPeriodColorCfgID;}
			set
			{
				if (value != this._pPPeriodColorCfgID)
				{
				_pPPeriodColorCfgID=value;
				NotifyChanged("PPPeriodColorCfgID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public int PPPeriodColorCfgPeriod1
		{
			get{return _pPPeriodColorCfgPeriod1;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod1)
				{
				_pPPeriodColorCfgPeriod1=value;
				NotifyChanged("PPPeriodColorCfgPeriod1");
				}
			}
		}
		public int PPPeriodColorCfgPeriod2
		{
			get{return _pPPeriodColorCfgPeriod2;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod2)
				{
				_pPPeriodColorCfgPeriod2=value;
				NotifyChanged("PPPeriodColorCfgPeriod2");
				}
			}
		}
		public int PPPeriodColorCfgPeriod3
		{
			get{return _pPPeriodColorCfgPeriod3;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod3)
				{
				_pPPeriodColorCfgPeriod3=value;
				NotifyChanged("PPPeriodColorCfgPeriod3");
				}
			}
		}
		public int PPPeriodColorCfgPeriod4
		{
			get{return _pPPeriodColorCfgPeriod4;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod4)
				{
				_pPPeriodColorCfgPeriod4=value;
				NotifyChanged("PPPeriodColorCfgPeriod4");
				}
			}
		}
		public int PPPeriodColorCfgPeriod5
		{
			get{return _pPPeriodColorCfgPeriod5;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod5)
				{
				_pPPeriodColorCfgPeriod5=value;
				NotifyChanged("PPPeriodColorCfgPeriod5");
				}
			}
		}
		public int PPPeriodColorCfgPeriod6
		{
			get{return _pPPeriodColorCfgPeriod6;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod6)
				{
				_pPPeriodColorCfgPeriod6=value;
				NotifyChanged("PPPeriodColorCfgPeriod6");
				}
			}
		}
		public int PPPeriodColorCfgPeriod7
		{
			get{return _pPPeriodColorCfgPeriod7;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod7)
				{
				_pPPeriodColorCfgPeriod7=value;
				NotifyChanged("PPPeriodColorCfgPeriod7");
				}
			}
		}
		public int PPPeriodColorCfgPeriod8
		{
			get{return _pPPeriodColorCfgPeriod8;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod8)
				{
				_pPPeriodColorCfgPeriod8=value;
				NotifyChanged("PPPeriodColorCfgPeriod8");
				}
			}
		}
		public int PPPeriodColorCfgPeriod9
		{
			get{return _pPPeriodColorCfgPeriod9;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod9)
				{
				_pPPeriodColorCfgPeriod9=value;
				NotifyChanged("PPPeriodColorCfgPeriod9");
				}
			}
		}
		public int PPPeriodColorCfgPeriod10
		{
			get{return _pPPeriodColorCfgPeriod10;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod10)
				{
				_pPPeriodColorCfgPeriod10=value;
				NotifyChanged("PPPeriodColorCfgPeriod10");
				}
			}
		}
		public int PPPeriodColorCfgPeriod11
		{
			get{return _pPPeriodColorCfgPeriod11;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod11)
				{
				_pPPeriodColorCfgPeriod11=value;
				NotifyChanged("PPPeriodColorCfgPeriod11");
				}
			}
		}
		public int PPPeriodColorCfgPeriod12
		{
			get{return _pPPeriodColorCfgPeriod12;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod12)
				{
				_pPPeriodColorCfgPeriod12=value;
				NotifyChanged("PPPeriodColorCfgPeriod12");
				}
			}
		}
		public int PPPeriodColorCfgPeriod13
		{
			get{return _pPPeriodColorCfgPeriod13;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod13)
				{
				_pPPeriodColorCfgPeriod13=value;
				NotifyChanged("PPPeriodColorCfgPeriod13");
				}
			}
		}
		public int PPPeriodColorCfgPeriod14
		{
			get{return _pPPeriodColorCfgPeriod14;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod14)
				{
				_pPPeriodColorCfgPeriod14=value;
				NotifyChanged("PPPeriodColorCfgPeriod14");
				}
			}
		}
		public int PPPeriodColorCfgPeriod15
		{
			get{return _pPPeriodColorCfgPeriod15;}
			set
			{
				if (value != this._pPPeriodColorCfgPeriod15)
				{
				_pPPeriodColorCfgPeriod15=value;
				NotifyChanged("PPPeriodColorCfgPeriod15");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		#endregion
	}
	#endregion
}