using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPProductionSetups
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:PPProductionSetupsInfo
	//Created Date:21 Tháng Tám 2014
	//-----------------------------------------------------------
	
	public class PPProductionSetupsInfo:BusinessObject
	{
		public PPProductionSetupsInfo()
		{
		}
		#region Variables
		protected int _pPProductionSetupID;
		protected String _pPProductionSetupNo=String.Empty;
		protected String _pPProductionSetupName=String.Empty;
		protected String _pPProductionSetupDesc=String.Empty;
		protected int _fK_ICStockSemiProductID;
		protected int _fK_ICStockProductID;
		protected int _pPProductionSetupDayOfBeginPeriod;
		protected int _pPProductionSetupDayOfEndPeriod;
		protected String _aAStatus=DefaultAAStatus;
		protected String _aACreatedUser=String.Empty;
		protected String _aAUpdatedUser=String.Empty;
		protected Nullable<DateTime> _aACreatedDate;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected double _pPProductionSetupPriority;
		protected int _fK_ICStockSemiDetailProductID;
		protected bool _pPProductionSetupNoWithPhaseCfgCheck=true;
		protected bool _pPProductionSetupNoWithDateCheck=true;
		protected int _pPProductionSetupNoLength;
		protected String _pPProductionSetupNoSeparate=String.Empty;
		protected double _pPProductionSetupPkgContQty;
		protected int _fK_ICStockGetAllProductQtyByLotID;
		protected int _fK_ICStockGetAllProductQtyByLot1ID;
		protected int _fK_ICStockGetAllProductQtyByLot2ID;
		protected int _fK_ICStockFGProductID;
		protected int _fK_ICStockFGProduct1ID;
		protected int _pPProductionSetupOverLossPctColor;
		protected int _pPProductionSetupInLossPctColor;
		protected int _pPProductionSetupRequestOnSiteDay;
		protected int _pPProductionSetupPODueDay;
		protected int _pPProductionSetupETDDueDay;
		protected bool _pPProductionSetupCalMPSWOCheck=true;
		protected bool _pPProductionSetupCalMPSWSCheck=true;
		protected bool _pPProductionSetupCalMPSPOCheck=true;
		protected bool _pPProductionSetupCalMPSPRCheck=true;
		protected bool _pPProductionSetupCalMPSInvCheck=true;
		#endregion

		#region Public properties
		public int PPProductionSetupID
		{
			get{return _pPProductionSetupID;}
			set
			{
				if (value != this._pPProductionSetupID)
				{
				_pPProductionSetupID=value;
				NotifyChanged("PPProductionSetupID");
				}
			}
		}
		public String PPProductionSetupNo
		{
			get{return _pPProductionSetupNo;}
			set
			{
				if (value != this._pPProductionSetupNo)
				{
				_pPProductionSetupNo=value;
				NotifyChanged("PPProductionSetupNo");
				}
			}
		}
		public String PPProductionSetupName
		{
			get{return _pPProductionSetupName;}
			set
			{
				if (value != this._pPProductionSetupName)
				{
				_pPProductionSetupName=value;
				NotifyChanged("PPProductionSetupName");
				}
			}
		}
		public String PPProductionSetupDesc
		{
			get{return _pPProductionSetupDesc;}
			set
			{
				if (value != this._pPProductionSetupDesc)
				{
				_pPProductionSetupDesc=value;
				NotifyChanged("PPProductionSetupDesc");
				}
			}
		}
		public int FK_ICStockSemiProductID
		{
			get{return _fK_ICStockSemiProductID;}
			set
			{
				if (value != this._fK_ICStockSemiProductID)
				{
				_fK_ICStockSemiProductID=value;
				NotifyChanged("FK_ICStockSemiProductID");
				}
			}
		}
		public int FK_ICStockProductID
		{
			get{return _fK_ICStockProductID;}
			set
			{
				if (value != this._fK_ICStockProductID)
				{
				_fK_ICStockProductID=value;
				NotifyChanged("FK_ICStockProductID");
				}
			}
		}
		public int PPProductionSetupDayOfBeginPeriod
		{
			get{return _pPProductionSetupDayOfBeginPeriod;}
			set
			{
				if (value != this._pPProductionSetupDayOfBeginPeriod)
				{
				_pPProductionSetupDayOfBeginPeriod=value;
				NotifyChanged("PPProductionSetupDayOfBeginPeriod");
				}
			}
		}
		public int PPProductionSetupDayOfEndPeriod
		{
			get{return _pPProductionSetupDayOfEndPeriod;}
			set
			{
				if (value != this._pPProductionSetupDayOfEndPeriod)
				{
				_pPProductionSetupDayOfEndPeriod=value;
				NotifyChanged("PPProductionSetupDayOfEndPeriod");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public double PPProductionSetupPriority
		{
			get{return _pPProductionSetupPriority;}
			set
			{
				if (value != this._pPProductionSetupPriority)
				{
				_pPProductionSetupPriority=value;
				NotifyChanged("PPProductionSetupPriority");
				}
			}
		}
		public int FK_ICStockSemiDetailProductID
		{
			get{return _fK_ICStockSemiDetailProductID;}
			set
			{
				if (value != this._fK_ICStockSemiDetailProductID)
				{
				_fK_ICStockSemiDetailProductID=value;
				NotifyChanged("FK_ICStockSemiDetailProductID");
				}
			}
		}
		public bool PPProductionSetupNoWithPhaseCfgCheck
		{
			get{return _pPProductionSetupNoWithPhaseCfgCheck;}
			set
			{
				if (value != this._pPProductionSetupNoWithPhaseCfgCheck)
				{
				_pPProductionSetupNoWithPhaseCfgCheck=value;
				NotifyChanged("PPProductionSetupNoWithPhaseCfgCheck");
				}
			}
		}
		public bool PPProductionSetupNoWithDateCheck
		{
			get{return _pPProductionSetupNoWithDateCheck;}
			set
			{
				if (value != this._pPProductionSetupNoWithDateCheck)
				{
				_pPProductionSetupNoWithDateCheck=value;
				NotifyChanged("PPProductionSetupNoWithDateCheck");
				}
			}
		}
		public int PPProductionSetupNoLength
		{
			get{return _pPProductionSetupNoLength;}
			set
			{
				if (value != this._pPProductionSetupNoLength)
				{
				_pPProductionSetupNoLength=value;
				NotifyChanged("PPProductionSetupNoLength");
				}
			}
		}
		public String PPProductionSetupNoSeparate
		{
			get{return _pPProductionSetupNoSeparate;}
			set
			{
				if (value != this._pPProductionSetupNoSeparate)
				{
				_pPProductionSetupNoSeparate=value;
				NotifyChanged("PPProductionSetupNoSeparate");
				}
			}
		}
		public double PPProductionSetupPkgContQty
		{
			get{return _pPProductionSetupPkgContQty;}
			set
			{
				if (value != this._pPProductionSetupPkgContQty)
				{
				_pPProductionSetupPkgContQty=value;
				NotifyChanged("PPProductionSetupPkgContQty");
				}
			}
		}
		public int FK_ICStockGetAllProductQtyByLotID
		{
			get{return _fK_ICStockGetAllProductQtyByLotID;}
			set
			{
				if (value != this._fK_ICStockGetAllProductQtyByLotID)
				{
				_fK_ICStockGetAllProductQtyByLotID=value;
				NotifyChanged("FK_ICStockGetAllProductQtyByLotID");
				}
			}
		}
		public int FK_ICStockGetAllProductQtyByLot1ID
		{
			get{return _fK_ICStockGetAllProductQtyByLot1ID;}
			set
			{
				if (value != this._fK_ICStockGetAllProductQtyByLot1ID)
				{
				_fK_ICStockGetAllProductQtyByLot1ID=value;
				NotifyChanged("FK_ICStockGetAllProductQtyByLot1ID");
				}
			}
		}
		public int FK_ICStockGetAllProductQtyByLot2ID
		{
			get{return _fK_ICStockGetAllProductQtyByLot2ID;}
			set
			{
				if (value != this._fK_ICStockGetAllProductQtyByLot2ID)
				{
				_fK_ICStockGetAllProductQtyByLot2ID=value;
				NotifyChanged("FK_ICStockGetAllProductQtyByLot2ID");
				}
			}
		}
		public int FK_ICStockFGProductID
		{
			get{return _fK_ICStockFGProductID;}
			set
			{
				if (value != this._fK_ICStockFGProductID)
				{
				_fK_ICStockFGProductID=value;
				NotifyChanged("FK_ICStockFGProductID");
				}
			}
		}
		public int FK_ICStockFGProduct1ID
		{
			get{return _fK_ICStockFGProduct1ID;}
			set
			{
				if (value != this._fK_ICStockFGProduct1ID)
				{
				_fK_ICStockFGProduct1ID=value;
				NotifyChanged("FK_ICStockFGProduct1ID");
				}
			}
		}
		public int PPProductionSetupOverLossPctColor
		{
			get{return _pPProductionSetupOverLossPctColor;}
			set
			{
				if (value != this._pPProductionSetupOverLossPctColor)
				{
				_pPProductionSetupOverLossPctColor=value;
				NotifyChanged("PPProductionSetupOverLossPctColor");
				}
			}
		}
		public int PPProductionSetupInLossPctColor
		{
			get{return _pPProductionSetupInLossPctColor;}
			set
			{
				if (value != this._pPProductionSetupInLossPctColor)
				{
				_pPProductionSetupInLossPctColor=value;
				NotifyChanged("PPProductionSetupInLossPctColor");
				}
			}
		}
		public int PPProductionSetupRequestOnSiteDay
		{
			get{return _pPProductionSetupRequestOnSiteDay;}
			set
			{
				if (value != this._pPProductionSetupRequestOnSiteDay)
				{
				_pPProductionSetupRequestOnSiteDay=value;
				NotifyChanged("PPProductionSetupRequestOnSiteDay");
				}
			}
		}
		public int PPProductionSetupPODueDay
		{
			get{return _pPProductionSetupPODueDay;}
			set
			{
				if (value != this._pPProductionSetupPODueDay)
				{
				_pPProductionSetupPODueDay=value;
				NotifyChanged("PPProductionSetupPODueDay");
				}
			}
		}
		public int PPProductionSetupETDDueDay
		{
			get{return _pPProductionSetupETDDueDay;}
			set
			{
				if (value != this._pPProductionSetupETDDueDay)
				{
				_pPProductionSetupETDDueDay=value;
				NotifyChanged("PPProductionSetupETDDueDay");
				}
			}
		}
		public bool PPProductionSetupCalMPSWOCheck
		{
			get{return _pPProductionSetupCalMPSWOCheck;}
			set
			{
				if (value != this._pPProductionSetupCalMPSWOCheck)
				{
				_pPProductionSetupCalMPSWOCheck=value;
				NotifyChanged("PPProductionSetupCalMPSWOCheck");
				}
			}
		}
		public bool PPProductionSetupCalMPSWSCheck
		{
			get{return _pPProductionSetupCalMPSWSCheck;}
			set
			{
				if (value != this._pPProductionSetupCalMPSWSCheck)
				{
				_pPProductionSetupCalMPSWSCheck=value;
				NotifyChanged("PPProductionSetupCalMPSWSCheck");
				}
			}
		}
		public bool PPProductionSetupCalMPSPOCheck
		{
			get{return _pPProductionSetupCalMPSPOCheck;}
			set
			{
				if (value != this._pPProductionSetupCalMPSPOCheck)
				{
				_pPProductionSetupCalMPSPOCheck=value;
				NotifyChanged("PPProductionSetupCalMPSPOCheck");
				}
			}
		}
		public bool PPProductionSetupCalMPSPRCheck
		{
			get{return _pPProductionSetupCalMPSPRCheck;}
			set
			{
				if (value != this._pPProductionSetupCalMPSPRCheck)
				{
				_pPProductionSetupCalMPSPRCheck=value;
				NotifyChanged("PPProductionSetupCalMPSPRCheck");
				}
			}
		}
		public bool PPProductionSetupCalMPSInvCheck
		{
			get{return _pPProductionSetupCalMPSInvCheck;}
			set
			{
				if (value != this._pPProductionSetupCalMPSInvCheck)
				{
				_pPProductionSetupCalMPSInvCheck=value;
				NotifyChanged("PPProductionSetupCalMPSInvCheck");
				}
			}
		}
		#endregion
	}
	#endregion
}