using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region PPProductionCostInCompletes
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:PPProductionCostInCompletesInfo
	//Created Date:Wednesday, January 7, 2015
	//-----------------------------------------------------------
	
	public class PPProductionCostInCompletesInfo:BusinessObject
	{
		public PPProductionCostInCompletesInfo()
		{
		}
		#region Variables
		protected int _pPProductionCostInCompleteID;
		protected int _fK_PPProductionCostCenterID;
		protected int _fK_PPCostCenterID;
		protected int _fK_ICProductID;
		protected int _fK_PPPhaseCfgID;
		protected int _fK_PPInCompleteStatisticItemID;
		protected double _pPProductionCostInCompleteQty;
		protected double _pPProductionCostInCompleteNVLPct;
		protected double _pPProductionCostInCompleteNCPct;
		protected double _pPProductionCostInCompleteSXCPct;
		protected int _pPYear;
		protected int _pPPeriod;
		#endregion

		#region Public properties
		public int PPProductionCostInCompleteID
		{
			get{return _pPProductionCostInCompleteID;}
			set
			{
				if (value != this._pPProductionCostInCompleteID)
				{
				_pPProductionCostInCompleteID=value;
				NotifyChanged("PPProductionCostInCompleteID");
				}
			}
		}
		public int FK_PPProductionCostCenterID
		{
			get{return _fK_PPProductionCostCenterID;}
			set
			{
				if (value != this._fK_PPProductionCostCenterID)
				{
				_fK_PPProductionCostCenterID=value;
				NotifyChanged("FK_PPProductionCostCenterID");
				}
			}
		}
		public int FK_PPCostCenterID
		{
			get{return _fK_PPCostCenterID;}
			set
			{
				if (value != this._fK_PPCostCenterID)
				{
				_fK_PPCostCenterID=value;
				NotifyChanged("FK_PPCostCenterID");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_PPPhaseCfgID
		{
			get{return _fK_PPPhaseCfgID;}
			set
			{
				if (value != this._fK_PPPhaseCfgID)
				{
				_fK_PPPhaseCfgID=value;
				NotifyChanged("FK_PPPhaseCfgID");
				}
			}
		}
		public int FK_PPInCompleteStatisticItemID
		{
			get{return _fK_PPInCompleteStatisticItemID;}
			set
			{
				if (value != this._fK_PPInCompleteStatisticItemID)
				{
				_fK_PPInCompleteStatisticItemID=value;
				NotifyChanged("FK_PPInCompleteStatisticItemID");
				}
			}
		}
		public double PPProductionCostInCompleteQty
		{
			get{return _pPProductionCostInCompleteQty;}
			set
			{
				if (value != this._pPProductionCostInCompleteQty)
				{
				_pPProductionCostInCompleteQty=value;
				NotifyChanged("PPProductionCostInCompleteQty");
				}
			}
		}
		public double PPProductionCostInCompleteNVLPct
		{
			get{return _pPProductionCostInCompleteNVLPct;}
			set
			{
				if (value != this._pPProductionCostInCompleteNVLPct)
				{
				_pPProductionCostInCompleteNVLPct=value;
				NotifyChanged("PPProductionCostInCompleteNVLPct");
				}
			}
		}
		public double PPProductionCostInCompleteNCPct
		{
			get{return _pPProductionCostInCompleteNCPct;}
			set
			{
				if (value != this._pPProductionCostInCompleteNCPct)
				{
				_pPProductionCostInCompleteNCPct=value;
				NotifyChanged("PPProductionCostInCompleteNCPct");
				}
			}
		}
		public double PPProductionCostInCompleteSXCPct
		{
			get{return _pPProductionCostInCompleteSXCPct;}
			set
			{
				if (value != this._pPProductionCostInCompleteSXCPct)
				{
				_pPProductionCostInCompleteSXCPct=value;
				NotifyChanged("PPProductionCostInCompleteSXCPct");
				}
			}
		}
		public int PPYear
		{
			get{return _pPYear;}
			set
			{
				if (value != this._pPYear)
				{
				_pPYear=value;
				NotifyChanged("PPYear");
				}
			}
		}
		public int PPPeriod
		{
			get{return _pPPeriod;}
			set
			{
				if (value != this._pPPeriod)
				{
				_pPPeriod=value;
				NotifyChanged("PPPeriod");
				}
			}
		}
		#endregion
	}
	#endregion
}