using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region CMMailRecipients
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:CMMailRecipientsController
	//Created Date:Wednesday, April 29, 2009
	//-----------------------------------------------------------
	
	public class CMMailRecipientsController:BaseBusinessController
	{
        private readonly static string spGetMailRecipientByMailAndRecipientUserName = "CMMailRecipients_SelectByMailAndRecipientUserName";

		public CMMailRecipientsController()
		{
			dal= new DALBaseProvider("CMMailRecipients",typeof(CMMailRecipientsInfo));
		}

        public CMMailRecipientsInfo GetMailRecipientByMailAndRecipientUserName(int iCMMailID, String strCMMailRecipientUserName)
        {
            return (CMMailRecipientsInfo)dal.GetDataObject(spGetMailRecipientByMailAndRecipientUserName, iCMMailID, strCMMailRecipientUserName);
        }
	}
	#endregion
}