using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region FAAssetInitJournals
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:FAAssetInitJournalsController
	//Created Date:Thursday, March 19, 2015
	//-----------------------------------------------------------
	
	public class FAAssetInitJournalsController:BaseBusinessController
	{
		public FAAssetInitJournalsController()
		{
			dal= new DALBaseProvider("FAAssetInitJournals",typeof(FAAssetInitJournalsInfo));
		}
        public void DeleteInitJournalByAssetID(int iAssetID)
        {
            string strSQL = string.Format(@"
UPDATE FAAssetInitJournals 
    SET FK_GLJournalID = null
    WHERE FK_FAAssetID = {0} AND AAStatus <> 'Alive'"
                , iAssetID);
            dal.RunQuery(strSQL);
        }
	}
	#endregion
}