using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRDiligentCfgs
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:HRDiligentCfgsInfo
	//Created Date:26 Tháng Chín 2013
	//-----------------------------------------------------------
	
	public class HRDiligentCfgsInfo:BusinessObject
	{
		public HRDiligentCfgsInfo()
		{
		}
		#region Variables
		protected int _hRDiligentCfgID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected double _hRDiligentCfgLeaveCnt;
		protected double _hRDiligentCfgUnauthorizedLeaveCnt;
		protected double _hRDiligentCfgAbsenceOTCnt;
		protected double _hRDiligentCfgRate;
		protected double _hRDiligentCfgLateInTime;
		protected double _hRDiligentCfgEarlyOutTime;
		protected String _aAOrgDocNo=String.Empty;
		#endregion

		#region Public properties
		public int HRDiligentCfgID
		{
			get{return _hRDiligentCfgID;}
			set
			{
				if (value != this._hRDiligentCfgID)
				{
				_hRDiligentCfgID=value;
				NotifyChanged("HRDiligentCfgID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public double HRDiligentCfgLeaveCnt
		{
			get{return _hRDiligentCfgLeaveCnt;}
			set
			{
				if (value != this._hRDiligentCfgLeaveCnt)
				{
				_hRDiligentCfgLeaveCnt=value;
				NotifyChanged("HRDiligentCfgLeaveCnt");
				}
			}
		}
		public double HRDiligentCfgUnauthorizedLeaveCnt
		{
			get{return _hRDiligentCfgUnauthorizedLeaveCnt;}
			set
			{
				if (value != this._hRDiligentCfgUnauthorizedLeaveCnt)
				{
				_hRDiligentCfgUnauthorizedLeaveCnt=value;
				NotifyChanged("HRDiligentCfgUnauthorizedLeaveCnt");
				}
			}
		}
		public double HRDiligentCfgAbsenceOTCnt
		{
			get{return _hRDiligentCfgAbsenceOTCnt;}
			set
			{
				if (value != this._hRDiligentCfgAbsenceOTCnt)
				{
				_hRDiligentCfgAbsenceOTCnt=value;
				NotifyChanged("HRDiligentCfgAbsenceOTCnt");
				}
			}
		}
		public double HRDiligentCfgRate
		{
			get{return _hRDiligentCfgRate;}
			set
			{
				if (value != this._hRDiligentCfgRate)
				{
				_hRDiligentCfgRate=value;
				NotifyChanged("HRDiligentCfgRate");
				}
			}
		}
		public double HRDiligentCfgLateInTime
		{
			get{return _hRDiligentCfgLateInTime;}
			set
			{
				if (value != this._hRDiligentCfgLateInTime)
				{
				_hRDiligentCfgLateInTime=value;
				NotifyChanged("HRDiligentCfgLateInTime");
				}
			}
		}
		public double HRDiligentCfgEarlyOutTime
		{
			get{return _hRDiligentCfgEarlyOutTime;}
			set
			{
				if (value != this._hRDiligentCfgEarlyOutTime)
				{
				_hRDiligentCfgEarlyOutTime=value;
				NotifyChanged("HRDiligentCfgEarlyOutTime");
				}
			}
		}
		public String AAOrgDocNo
		{
			get{return _aAOrgDocNo;}
			set
			{
				if (value != this._aAOrgDocNo)
				{
				_aAOrgDocNo=value;
				NotifyChanged("AAOrgDocNo");
				}
			}
		}
		#endregion
	}
	#endregion
}