using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HREmployeeDisciplineTypes
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HREmployeeDisciplineTypesInfo
	//Created Date:Thursday, February 16, 2017
	//-----------------------------------------------------------
	
	public class HREmployeeDisciplineTypesInfo:BusinessObject
	{
		public HREmployeeDisciplineTypesInfo()
		{
		}
		#region Variables
		protected int _hREmployeeDisciplineTypeID;
		protected String _hREmployeeDisciplineTypeNo=String.Empty;
		protected String _hREmployeeDisciplineTypeName=String.Empty;
		protected Nullable<DateTime> _hREmployeeDisciplineTypeDate;
		protected String _hREmployeeDisciplineTypeDesc=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected bool _aASelected=true;
		#endregion

		#region Public properties
		public int HREmployeeDisciplineTypeID
		{
			get{return _hREmployeeDisciplineTypeID;}
			set
			{
				if (value != this._hREmployeeDisciplineTypeID)
				{
				_hREmployeeDisciplineTypeID=value;
				NotifyChanged("HREmployeeDisciplineTypeID");
				}
			}
		}
		public String HREmployeeDisciplineTypeNo
		{
			get{return _hREmployeeDisciplineTypeNo;}
			set
			{
				if (value != this._hREmployeeDisciplineTypeNo)
				{
				_hREmployeeDisciplineTypeNo=value;
				NotifyChanged("HREmployeeDisciplineTypeNo");
				}
			}
		}
		public String HREmployeeDisciplineTypeName
		{
			get{return _hREmployeeDisciplineTypeName;}
			set
			{
				if (value != this._hREmployeeDisciplineTypeName)
				{
				_hREmployeeDisciplineTypeName=value;
				NotifyChanged("HREmployeeDisciplineTypeName");
				}
			}
		}
		public Nullable<DateTime> HREmployeeDisciplineTypeDate
		{
			get{return _hREmployeeDisciplineTypeDate;}
			set
			{
				if (value != this._hREmployeeDisciplineTypeDate)
				{
				_hREmployeeDisciplineTypeDate=value;
				NotifyChanged("HREmployeeDisciplineTypeDate");
				}
			}
		}
		public String HREmployeeDisciplineTypeDesc
		{
			get{return _hREmployeeDisciplineTypeDesc;}
			set
			{
				if (value != this._hREmployeeDisciplineTypeDesc)
				{
				_hREmployeeDisciplineTypeDesc=value;
				NotifyChanged("HREmployeeDisciplineTypeDesc");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		#endregion
	}
	#endregion
}