using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRObjects
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HRObjectsInfo
	//Created Date:Tuesday, December 12, 2017
	//-----------------------------------------------------------
	
	public class HRObjectsInfo:BusinessObject
	{
		public HRObjectsInfo()
		{
		}
		#region Variables
		protected int _hRObjectID;
		protected String _hRObjectNo=String.Empty;
		protected String _hRObjectName=String.Empty;
		protected Nullable<DateTime> _hRObjectDate;
		protected String _hRObjectDesc=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected bool _aASelected=true;
		protected String _hRObjectDataSource=String.Empty;
		protected String _hRObjectDisplayMember=String.Empty;
		protected String _hRObjectValueMember=String.Empty;
		#endregion

		#region Public properties
		public int HRObjectID
		{
			get{return _hRObjectID;}
			set
			{
				if (value != this._hRObjectID)
				{
				_hRObjectID=value;
				NotifyChanged("HRObjectID");
				}
			}
		}
		public String HRObjectNo
		{
			get{return _hRObjectNo;}
			set
			{
				if (value != this._hRObjectNo)
				{
				_hRObjectNo=value;
				NotifyChanged("HRObjectNo");
				}
			}
		}
		public String HRObjectName
		{
			get{return _hRObjectName;}
			set
			{
				if (value != this._hRObjectName)
				{
				_hRObjectName=value;
				NotifyChanged("HRObjectName");
				}
			}
		}
		public Nullable<DateTime> HRObjectDate
		{
			get{return _hRObjectDate;}
			set
			{
				if (value != this._hRObjectDate)
				{
				_hRObjectDate=value;
				NotifyChanged("HRObjectDate");
				}
			}
		}
		public String HRObjectDesc
		{
			get{return _hRObjectDesc;}
			set
			{
				if (value != this._hRObjectDesc)
				{
				_hRObjectDesc=value;
				NotifyChanged("HRObjectDesc");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public String HRObjectDataSource
		{
			get{return _hRObjectDataSource;}
			set
			{
				if (value != this._hRObjectDataSource)
				{
				_hRObjectDataSource=value;
				NotifyChanged("HRObjectDataSource");
				}
			}
		}
		public String HRObjectDisplayMember
		{
			get{return _hRObjectDisplayMember;}
			set
			{
				if (value != this._hRObjectDisplayMember)
				{
				_hRObjectDisplayMember=value;
				NotifyChanged("HRObjectDisplayMember");
				}
			}
		}
		public String HRObjectValueMember
		{
			get{return _hRObjectValueMember;}
			set
			{
				if (value != this._hRObjectValueMember)
				{
				_hRObjectValueMember=value;
				NotifyChanged("HRObjectValueMember");
				}
			}
		}
		#endregion
	}
	#endregion
}