using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRRecruitPlns
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:HRRecruitPlnsInfo
	//Created Date:24 Tháng Chín 2013
	//-----------------------------------------------------------
	
	public class HRRecruitPlnsInfo:BusinessObject
	{
		public HRRecruitPlnsInfo()
		{
		}
		#region Variables
		protected int _hRRecruitPlnID;
		protected String _aAStatus=DefaultAAStatus;
		protected String _aACreatedUser=String.Empty;
		protected String _aAUpdatedUser=String.Empty;
		protected Nullable<DateTime> _aACreatedDate;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _hRRecruitPlnNo=String.Empty;
		protected String _hRRecruitPlnName=String.Empty;
		protected Nullable<DateTime> _hRRecruitPlnDate;
		protected String _hRRecruitPlnDesc=String.Empty;
		protected String _hRRecruitPlnStatusCombo=DefaultStatus;
		protected Nullable<DateTime> _hRRecruitPlnFromDate;
		protected Nullable<DateTime> _hRRecruitPlnToDate;
		protected String _hRRecruitPlnQuarterCombo=String.Empty;
		protected int _hRRecruitPlnYear;
		protected double _hRRecruitPlnEstAmtTot;
		protected double _hRRecruitPlnAmtTot;
		protected String _approvalStatusCombo=DefaultStatus;
		#endregion

		#region Public properties
		public int HRRecruitPlnID
		{
			get{return _hRRecruitPlnID;}
			set
			{
				if (value != this._hRRecruitPlnID)
				{
				_hRRecruitPlnID=value;
				NotifyChanged("HRRecruitPlnID");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String HRRecruitPlnNo
		{
			get{return _hRRecruitPlnNo;}
			set
			{
				if (value != this._hRRecruitPlnNo)
				{
				_hRRecruitPlnNo=value;
				NotifyChanged("HRRecruitPlnNo");
				}
			}
		}
		public String HRRecruitPlnName
		{
			get{return _hRRecruitPlnName;}
			set
			{
				if (value != this._hRRecruitPlnName)
				{
				_hRRecruitPlnName=value;
				NotifyChanged("HRRecruitPlnName");
				}
			}
		}
		public Nullable<DateTime> HRRecruitPlnDate
		{
			get{return _hRRecruitPlnDate;}
			set
			{
				if (value != this._hRRecruitPlnDate)
				{
				_hRRecruitPlnDate=value;
				NotifyChanged("HRRecruitPlnDate");
				}
			}
		}
		public String HRRecruitPlnDesc
		{
			get{return _hRRecruitPlnDesc;}
			set
			{
				if (value != this._hRRecruitPlnDesc)
				{
				_hRRecruitPlnDesc=value;
				NotifyChanged("HRRecruitPlnDesc");
				}
			}
		}
		public String HRRecruitPlnStatusCombo
		{
			get{return _hRRecruitPlnStatusCombo;}
			set
			{
				if (value != this._hRRecruitPlnStatusCombo)
				{
				_hRRecruitPlnStatusCombo=value;
				NotifyChanged("HRRecruitPlnStatusCombo");
				}
			}
		}
		public Nullable<DateTime> HRRecruitPlnFromDate
		{
			get{return _hRRecruitPlnFromDate;}
			set
			{
				if (value != this._hRRecruitPlnFromDate)
				{
				_hRRecruitPlnFromDate=value;
				NotifyChanged("HRRecruitPlnFromDate");
				}
			}
		}
		public Nullable<DateTime> HRRecruitPlnToDate
		{
			get{return _hRRecruitPlnToDate;}
			set
			{
				if (value != this._hRRecruitPlnToDate)
				{
				_hRRecruitPlnToDate=value;
				NotifyChanged("HRRecruitPlnToDate");
				}
			}
		}
		public String HRRecruitPlnQuarterCombo
		{
			get{return _hRRecruitPlnQuarterCombo;}
			set
			{
				if (value != this._hRRecruitPlnQuarterCombo)
				{
				_hRRecruitPlnQuarterCombo=value;
				NotifyChanged("HRRecruitPlnQuarterCombo");
				}
			}
		}
		public int HRRecruitPlnYear
		{
			get{return _hRRecruitPlnYear;}
			set
			{
				if (value != this._hRRecruitPlnYear)
				{
				_hRRecruitPlnYear=value;
				NotifyChanged("HRRecruitPlnYear");
				}
			}
		}
		public double HRRecruitPlnEstAmtTot
		{
			get{return _hRRecruitPlnEstAmtTot;}
			set
			{
				if (value != this._hRRecruitPlnEstAmtTot)
				{
				_hRRecruitPlnEstAmtTot=value;
				NotifyChanged("HRRecruitPlnEstAmtTot");
				}
			}
		}
		public double HRRecruitPlnAmtTot
		{
			get{return _hRRecruitPlnAmtTot;}
			set
			{
				if (value != this._hRRecruitPlnAmtTot)
				{
				_hRRecruitPlnAmtTot=value;
				NotifyChanged("HRRecruitPlnAmtTot");
				}
			}
		}
		public String ApprovalStatusCombo
		{
			get{return _approvalStatusCombo;}
			set
			{
				if (value != this._approvalStatusCombo)
				{
				_approvalStatusCombo=value;
				NotifyChanged("ApprovalStatusCombo");
				}
			}
		}
		#endregion
	}
	#endregion
}