using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRTimeKeepingSymbols
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HRTimeKeepingSymbolsInfo
	//Created Date:Friday, December 15, 2017
	//-----------------------------------------------------------
	
	public class HRTimeKeepingSymbolsInfo:BusinessObject
	{
		public HRTimeKeepingSymbolsInfo()
		{
		}
		#region Variables
		protected int _hRTimeKeepingSymbolID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected String _hRTimeKeepingSymbolNo=String.Empty;
		protected String _hRTimeKeepingSymbolName=String.Empty;
		protected String _hRTimeKeepingSymbolDesc=String.Empty;
		protected String _hRTimeKeepingSymbolFormula=String.Empty;
		#endregion

		#region Public properties
		public int HRTimeKeepingSymbolID
		{
			get{return _hRTimeKeepingSymbolID;}
			set
			{
				if (value != this._hRTimeKeepingSymbolID)
				{
				_hRTimeKeepingSymbolID=value;
				NotifyChanged("HRTimeKeepingSymbolID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public String HRTimeKeepingSymbolNo
		{
			get{return _hRTimeKeepingSymbolNo;}
			set
			{
				if (value != this._hRTimeKeepingSymbolNo)
				{
				_hRTimeKeepingSymbolNo=value;
				NotifyChanged("HRTimeKeepingSymbolNo");
				}
			}
		}
		public String HRTimeKeepingSymbolName
		{
			get{return _hRTimeKeepingSymbolName;}
			set
			{
				if (value != this._hRTimeKeepingSymbolName)
				{
				_hRTimeKeepingSymbolName=value;
				NotifyChanged("HRTimeKeepingSymbolName");
				}
			}
		}
		public String HRTimeKeepingSymbolDesc
		{
			get{return _hRTimeKeepingSymbolDesc;}
			set
			{
				if (value != this._hRTimeKeepingSymbolDesc)
				{
				_hRTimeKeepingSymbolDesc=value;
				NotifyChanged("HRTimeKeepingSymbolDesc");
				}
			}
		}
		public String HRTimeKeepingSymbolFormula
		{
			get{return _hRTimeKeepingSymbolFormula;}
			set
			{
				if (value != this._hRTimeKeepingSymbolFormula)
				{
				_hRTimeKeepingSymbolFormula=value;
				NotifyChanged("HRTimeKeepingSymbolFormula");
				}
			}
		}
		#endregion
	}
	#endregion
}