using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;


namespace ExpertERP.BusinessEntities
{
    #region APPurchaseOrders
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:APPurchaseOrdersController
    //Created Date:Friday, April 18, 2008
    //-----------------------------------------------------------

    public class APPurchaseOrdersController : BaseBusinessController
    {
        public APPurchaseOrdersController()
        {
            dal = new DALBaseProvider("APPurchaseOrders", typeof(APPurchaseOrdersInfo));
        }
    }
    #endregion
}