using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region APAccountSets
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:APAccountSetsController
	//Created Date:Friday, May 13, 2011
	//-----------------------------------------------------------
	
	public class APAccountSetsController:BaseBusinessController
	{
		public APAccountSetsController()
		{
			dal= new DALBaseProvider("APAccountSets",typeof(APAccountSetsInfo));
		}

        public APAccountSetsInfo GetDefault()
        {
            String strQuery = String.Format(@"SELECT * FROM APAccountSets WHERE AADefault = 'true'");

            DataSet ds = dal.GetDataSet(strQuery);

            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                return (APAccountSetsInfo)dal.GetObjectFromDataRow(ds.Tables[0].Rows[0]);

            return null;
        }
	}
	#endregion
}