using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region GLTranCfgGroupChecks
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:GLTranCfgGroupChecksController
	//Created Date:Saturday, August 23, 2014
	//-----------------------------------------------------------
	
	public class GLTranCfgGroupChecksController:BaseBusinessController
	{
		public GLTranCfgGroupChecksController()
		{
			dal= new DALBaseProvider("GLTranCfgGroupChecks",typeof(GLTranCfgGroupChecksInfo));
		}
        public DataSet GetDataByTranCfgGroupID(int piTranCfgGroupID, string psNotINID = "")
        {
            String strQuery = String.Format(@"SELECT * FROM dbo.GLTranCfgGroupChecks 
                            WHERE FK_GLTranCfgGroupID = {0} OR FK_GLTranCfgGroupID = 0", piTranCfgGroupID);
            if (psNotINID != "")
                strQuery += String.Format(@"
                            AND GLTranCfgGroupCheckID NOT IN ({0})", psNotINID);
            return dal.GetDataSet(strQuery);
        }
	}
	#endregion
}