using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region GLVoucherComments
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:GLVoucherCommentsController
	//Created Date:Thursday, November 8, 2012
	//-----------------------------------------------------------
	
	public class GLVoucherCommentsController:BaseBusinessController
	{
		public GLVoucherCommentsController()
		{
			dal= new DALBaseProvider("GLVoucherComments",typeof(GLVoucherCommentsInfo));
		}
	}
	#endregion
}