using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
    #region ARPartners
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:ARPartnersInfo
    //Created Date:Wednesday, May 23, 2012
    //-----------------------------------------------------------

    public class ARPartnersInfo : BusinessObject
    {
        public ARPartnersInfo()
        {
        }
        #region Variables
        protected int _aRPartnerID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aRPartnerNo = String.Empty;
        protected String _aRPartnerName = String.Empty;
        protected String _aRPartnerDesc = String.Empty;
        protected double _aRPartnerCommPct;
        protected String _aRPartnerLevelCombo = String.Empty;
        #endregion

        #region Public properties
        public int ARPartnerID
        {
            get { return _aRPartnerID; }
            set
            {
                if (value != this._aRPartnerID)
                {
                    _aRPartnerID = value;
                    NotifyChanged("ARPartnerID");
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String ARPartnerNo
        {
            get { return _aRPartnerNo; }
            set
            {
                if (value != this._aRPartnerNo)
                {
                    _aRPartnerNo = value;
                    NotifyChanged("ARPartnerNo");
                }
            }
        }
        public String ARPartnerName
        {
            get { return _aRPartnerName; }
            set
            {
                if (value != this._aRPartnerName)
                {
                    _aRPartnerName = value;
                    NotifyChanged("ARPartnerName");
                }
            }
        }
        public String ARPartnerDesc
        {
            get { return _aRPartnerDesc; }
            set
            {
                if (value != this._aRPartnerDesc)
                {
                    _aRPartnerDesc = value;
                    NotifyChanged("ARPartnerDesc");
                }
            }
        }
        public double ARPartnerCommPct
        {
            get { return _aRPartnerCommPct; }
            set
            {
                if (value != this._aRPartnerCommPct)
                {
                    _aRPartnerCommPct = value;
                    NotifyChanged("ARPartnerCommPct");
                }
            }
        }
        public String ARPartnerLevelCombo
        {
            get { return _aRPartnerLevelCombo; }
            set
            {
                if (value != this._aRPartnerLevelCombo)
                {
                    _aRPartnerLevelCombo = value;
                    NotifyChanged("ARPartnerLevelCombo");
                }
            }
        }
        #endregion
    }
    #endregion
}