using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ICReceiptRequestReceipts
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ICReceiptRequestReceiptsInfo
	//Created Date:Friday, January 23, 2015
	//-----------------------------------------------------------
	
	public class ICReceiptRequestReceiptsInfo:BusinessObject
	{
		public ICReceiptRequestReceiptsInfo()
		{
		}
		#region Variables
		protected int _iCReceiptRequestReceiptID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected int _fK_ICReceiptID;
		protected int _fK_ICRequestReceiptID;
		#endregion

		#region Public properties
		public int ICReceiptRequestReceiptID
		{
			get{return _iCReceiptRequestReceiptID;}
			set
			{
				if (value != this._iCReceiptRequestReceiptID)
				{
				_iCReceiptRequestReceiptID=value;
				NotifyChanged("ICReceiptRequestReceiptID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public int FK_ICReceiptID
		{
			get{return _fK_ICReceiptID;}
			set
			{
				if (value != this._fK_ICReceiptID)
				{
				_fK_ICReceiptID=value;
				NotifyChanged("FK_ICReceiptID");
				}
			}
		}
		public int FK_ICRequestReceiptID
		{
			get{return _fK_ICRequestReceiptID;}
			set
			{
				if (value != this._fK_ICRequestReceiptID)
				{
				_fK_ICRequestReceiptID=value;
				NotifyChanged("FK_ICRequestReceiptID");
				}
			}
		}
		#endregion
	}
	#endregion
}