using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ACCostSimulationRMPriceLists
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ACCostSimulationRMPriceListsController
	//Created Date:21 Tháng Bảy 2014
	//-----------------------------------------------------------
	
	public class ACCostSimulationRMPriceListsController:BaseBusinessController
	{
		public ACCostSimulationRMPriceListsController()
		{
			dal= new DALBaseProvider("ACCostSimulationRMPriceLists",typeof(ACCostSimulationRMPriceListsInfo));
		}
	}
	#endregion
}