using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ARCustomerStats
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:ARCustomerStatsController
	//Created Date:Wednesday, February 24, 2010
	//-----------------------------------------------------------
	
	public class ARCustomerStatsController:BaseBusinessController
	{
		public ARCustomerStatsController()
		{
			dal= new DALBaseProvider("ARCustomerStats",typeof(ARCustomerStatsInfo));
		}
	}
	#endregion
}