using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region APPurchaseReturnReceipts
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:APPurchaseReturnReceiptsController
	//Created Date:04 Tháng Chín 2012
	//-----------------------------------------------------------
	
	public class APPurchaseReturnReceiptsController:BaseBusinessController
	{
		public APPurchaseReturnReceiptsController()
		{
			dal= new DALBaseProvider("APPurchaseReturnReceipts",typeof(APPurchaseReturnReceiptsInfo));
		}
	}
	#endregion
}