using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
    #region BRGVouchers
    //-----------------------------------------------------------
    //Generated By: Expert Studio
    //Class:BRGVouchersInfo
    //Created Date:Thursday, March 25, 2010
    //-----------------------------------------------------------

    public class BRGVouchersInfo : BusinessObject
    {
        public BRGVouchersInfo()
        {
        }
        #region Variables
        protected int _bRGVoucherID;
        protected DateTime _aACreatedDate = DateTime.Now;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.Now;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected String _bRGVoucherNo = String.Empty;
        protected double _bRGVoucherGiftAmt;
        protected double _bRGVoucherAmtTot;
        protected double _bRGVoucherItmAmtTot;
        protected DateTime _bRGVoucherDate;
        protected DateTime _bRGVoucherExpireDate;
        protected int _fK_HREmployeeID;
        protected int _fK_GELanguageID;
        protected int _fK_GECurrencyID;
        protected String _bRGVoucherDesc = String.Empty;
        protected String _bRGVoucherTxNo = String.Empty;
        protected String _bRGVoucherCustomerName = String.Empty;
        protected String _bRGVoucherCustomerDesc = String.Empty;
        protected String _bRGVoucherBTConName = String.Empty;
        protected String _bRGVoucherBTConFName = String.Empty;
        protected String _bRGVoucherBTConLName = String.Empty;
        protected String _bRGVoucherBTConTitle = String.Empty;
        protected String _bRGVoucherBTConHLet = String.Empty;
        protected String _bRGVoucherBTConHMsg = String.Empty;
        protected String _bRGVoucherBTConEmail = String.Empty;
        protected String _bRGVoucherBTConEmail1 = String.Empty;
        protected String _bRGVoucherBTConPhone = String.Empty;
        protected String _bRGVoucherBTConCPhone = String.Empty;
        protected String _bRGVoucherBTConFax = String.Empty;
        protected String _bRGVoucherBTConInfo = String.Empty;
        protected String _bRGVoucherBTConDept = String.Empty;
        protected String _bRGVoucherBTConRoom = String.Empty;
        protected String _bRGVoucherBTAddL1 = String.Empty;
        protected String _bRGVoucherBTAddL2 = String.Empty;
        protected String _bRGVoucherBTAddL3 = String.Empty;
        protected String _bRGVoucherBTAddStr = String.Empty;
        protected String _bRGVoucherBTAddCity = String.Empty;
        protected String _bRGVoucherBTAddPCode = String.Empty;
        protected String _bRGVoucherBTAddStProv = String.Empty;
        protected String _bRGVoucherBTAddZCode = String.Empty;
        protected String _bRGVoucherBTAddCountry = String.Empty;
        protected String _bRGVoucherSTConName = String.Empty;
        protected Nullable<DateTime> _bRGVoucherSTConBday;
        protected String _bRGVoucherSTConFName = String.Empty;
        protected String _bRGVoucherSTConLName = String.Empty;
        protected String _bRGVoucherSTConTitle = String.Empty;
        protected String _bRGVoucherSTConHLet = String.Empty;
        protected String _bRGVoucherSTConHMsg = String.Empty;
        protected String _bRGVoucherSTConEmail = String.Empty;
        protected String _bRGVoucherSTConEmail1 = String.Empty;
        protected String _bRGVoucherSTConPhone = String.Empty;
        protected String _bRGVoucherSTConCPhone = String.Empty;
        protected String _bRGVoucherSTConFax = String.Empty;
        protected String _bRGVoucherSTConInfo = String.Empty;
        protected String _bRGVoucherSTConDept = String.Empty;
        protected String _bRGVoucherSTConRoom = String.Empty;
        protected String _bRGVoucherSTAddL1 = String.Empty;
        protected String _bRGVoucherSTAddL2 = String.Empty;
        protected String _bRGVoucherSTAddL3 = String.Empty;
        protected String _bRGVoucherSTAddStr = String.Empty;
        protected String _bRGVoucherSTAddCity = String.Empty;
        protected String _bRGVoucherSTAddPCode = String.Empty;
        protected String _bRGVoucherSTAddStProv = String.Empty;
        protected String _bRGVoucherSTAddZCode = String.Empty;
        protected String _bRGVoucherSTAddCountry = String.Empty;
        #endregion

        #region Public properties
        public int BRGVoucherID
        {
            get { return _bRGVoucherID; }
            set
            {
                if (value != this._bRGVoucherID)
                {
                    _bRGVoucherID = value;
                    NotifyChanged("BRGVoucherID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String BRGVoucherNo
        {
            get { return _bRGVoucherNo; }
            set
            {
                if (value != this._bRGVoucherNo)
                {
                    _bRGVoucherNo = value;
                    NotifyChanged("BRGVoucherNo");
                }
            }
        }
        public double BRGVoucherGiftAmt
        {
            get { return _bRGVoucherGiftAmt; }
            set
            {
                if (value != this._bRGVoucherGiftAmt)
                {
                    _bRGVoucherGiftAmt = value;
                    NotifyChanged("BRGVoucherGiftAmt");
                }
            }
        }
        public double BRGVoucherAmtTot
        {
            get { return _bRGVoucherAmtTot; }
            set
            {
                if (value != this._bRGVoucherAmtTot)
                {
                    _bRGVoucherAmtTot = value;
                    NotifyChanged("BRGVoucherAmtTot");
                }
            }
        }
        public double BRGVoucherItmAmtTot
        {
            get { return _bRGVoucherItmAmtTot; }
            set
            {
                if (value != this._bRGVoucherItmAmtTot)
                {
                    _bRGVoucherItmAmtTot = value;
                    NotifyChanged("BRGVoucherItmAmtTot");
                }
            }
        }
        public DateTime BRGVoucherDate
        {
            get { return _bRGVoucherDate; }
            set
            {
                if (value != this._bRGVoucherDate)
                {
                    _bRGVoucherDate = value;
                    NotifyChanged("BRGVoucherDate");
                }
            }
        }
        public DateTime BRGVoucherExpireDate
        {
            get { return _bRGVoucherExpireDate; }
            set
            {
                if (value != this._bRGVoucherExpireDate)
                {
                    _bRGVoucherExpireDate = value;
                    NotifyChanged("BRGVoucherExpireDate");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_GELanguageID
        {
            get { return _fK_GELanguageID; }
            set
            {
                if (value != this._fK_GELanguageID)
                {
                    _fK_GELanguageID = value;
                    NotifyChanged("FK_GELanguageID");
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                    NotifyChanged("FK_GECurrencyID");
                }
            }
        }
        public String BRGVoucherDesc
        {
            get { return _bRGVoucherDesc; }
            set
            {
                if (value != this._bRGVoucherDesc)
                {
                    _bRGVoucherDesc = value;
                    NotifyChanged("BRGVoucherDesc");
                }
            }
        }
        public String BRGVoucherTxNo
        {
            get { return _bRGVoucherTxNo; }
            set
            {
                if (value != this._bRGVoucherTxNo)
                {
                    _bRGVoucherTxNo = value;
                    NotifyChanged("BRGVoucherTxNo");
                }
            }
        }
        public String BRGVoucherCustomerName
        {
            get { return _bRGVoucherCustomerName; }
            set
            {
                if (value != this._bRGVoucherCustomerName)
                {
                    _bRGVoucherCustomerName = value;
                    NotifyChanged("BRGVoucherCustomerName");
                }
            }
        }
        public String BRGVoucherCustomerDesc
        {
            get { return _bRGVoucherCustomerDesc; }
            set
            {
                if (value != this._bRGVoucherCustomerDesc)
                {
                    _bRGVoucherCustomerDesc = value;
                    NotifyChanged("BRGVoucherCustomerDesc");
                }
            }
        }
        public String BRGVoucherBTConName
        {
            get { return _bRGVoucherBTConName; }
            set
            {
                if (value != this._bRGVoucherBTConName)
                {
                    _bRGVoucherBTConName = value;
                    NotifyChanged("BRGVoucherBTConName");
                }
            }
        }
        public String BRGVoucherBTConFName
        {
            get { return _bRGVoucherBTConFName; }
            set
            {
                if (value != this._bRGVoucherBTConFName)
                {
                    _bRGVoucherBTConFName = value;
                    NotifyChanged("BRGVoucherBTConFName");
                }
            }
        }
        public String BRGVoucherBTConLName
        {
            get { return _bRGVoucherBTConLName; }
            set
            {
                if (value != this._bRGVoucherBTConLName)
                {
                    _bRGVoucherBTConLName = value;
                    NotifyChanged("BRGVoucherBTConLName");
                }
            }
        }
        public String BRGVoucherBTConTitle
        {
            get { return _bRGVoucherBTConTitle; }
            set
            {
                if (value != this._bRGVoucherBTConTitle)
                {
                    _bRGVoucherBTConTitle = value;
                    NotifyChanged("BRGVoucherBTConTitle");
                }
            }
        }
        public String BRGVoucherBTConHLet
        {
            get { return _bRGVoucherBTConHLet; }
            set
            {
                if (value != this._bRGVoucherBTConHLet)
                {
                    _bRGVoucherBTConHLet = value;
                    NotifyChanged("BRGVoucherBTConHLet");
                }
            }
        }
        public String BRGVoucherBTConHMsg
        {
            get { return _bRGVoucherBTConHMsg; }
            set
            {
                if (value != this._bRGVoucherBTConHMsg)
                {
                    _bRGVoucherBTConHMsg = value;
                    NotifyChanged("BRGVoucherBTConHMsg");
                }
            }
        }
        public String BRGVoucherBTConEmail
        {
            get { return _bRGVoucherBTConEmail; }
            set
            {
                if (value != this._bRGVoucherBTConEmail)
                {
                    _bRGVoucherBTConEmail = value;
                    NotifyChanged("BRGVoucherBTConEmail");
                }
            }
        }
        public String BRGVoucherBTConEmail1
        {
            get { return _bRGVoucherBTConEmail1; }
            set
            {
                if (value != this._bRGVoucherBTConEmail1)
                {
                    _bRGVoucherBTConEmail1 = value;
                    NotifyChanged("BRGVoucherBTConEmail1");
                }
            }
        }
        public String BRGVoucherBTConPhone
        {
            get { return _bRGVoucherBTConPhone; }
            set
            {
                if (value != this._bRGVoucherBTConPhone)
                {
                    _bRGVoucherBTConPhone = value;
                    NotifyChanged("BRGVoucherBTConPhone");
                }
            }
        }
        public String BRGVoucherBTConCPhone
        {
            get { return _bRGVoucherBTConCPhone; }
            set
            {
                if (value != this._bRGVoucherBTConCPhone)
                {
                    _bRGVoucherBTConCPhone = value;
                    NotifyChanged("BRGVoucherBTConCPhone");
                }
            }
        }
        public String BRGVoucherBTConFax
        {
            get { return _bRGVoucherBTConFax; }
            set
            {
                if (value != this._bRGVoucherBTConFax)
                {
                    _bRGVoucherBTConFax = value;
                    NotifyChanged("BRGVoucherBTConFax");
                }
            }
        }
        public String BRGVoucherBTConInfo
        {
            get { return _bRGVoucherBTConInfo; }
            set
            {
                if (value != this._bRGVoucherBTConInfo)
                {
                    _bRGVoucherBTConInfo = value;
                    NotifyChanged("BRGVoucherBTConInfo");
                }
            }
        }
        public String BRGVoucherBTConDept
        {
            get { return _bRGVoucherBTConDept; }
            set
            {
                if (value != this._bRGVoucherBTConDept)
                {
                    _bRGVoucherBTConDept = value;
                    NotifyChanged("BRGVoucherBTConDept");
                }
            }
        }
        public String BRGVoucherBTConRoom
        {
            get { return _bRGVoucherBTConRoom; }
            set
            {
                if (value != this._bRGVoucherBTConRoom)
                {
                    _bRGVoucherBTConRoom = value;
                    NotifyChanged("BRGVoucherBTConRoom");
                }
            }
        }
        public String BRGVoucherBTAddL1
        {
            get { return _bRGVoucherBTAddL1; }
            set
            {
                if (value != this._bRGVoucherBTAddL1)
                {
                    _bRGVoucherBTAddL1 = value;
                    NotifyChanged("BRGVoucherBTAddL1");
                }
            }
        }
        public String BRGVoucherBTAddL2
        {
            get { return _bRGVoucherBTAddL2; }
            set
            {
                if (value != this._bRGVoucherBTAddL2)
                {
                    _bRGVoucherBTAddL2 = value;
                    NotifyChanged("BRGVoucherBTAddL2");
                }
            }
        }
        public String BRGVoucherBTAddL3
        {
            get { return _bRGVoucherBTAddL3; }
            set
            {
                if (value != this._bRGVoucherBTAddL3)
                {
                    _bRGVoucherBTAddL3 = value;
                    NotifyChanged("BRGVoucherBTAddL3");
                }
            }
        }
        public String BRGVoucherBTAddStr
        {
            get { return _bRGVoucherBTAddStr; }
            set
            {
                if (value != this._bRGVoucherBTAddStr)
                {
                    _bRGVoucherBTAddStr = value;
                    NotifyChanged("BRGVoucherBTAddStr");
                }
            }
        }
        public String BRGVoucherBTAddCity
        {
            get { return _bRGVoucherBTAddCity; }
            set
            {
                if (value != this._bRGVoucherBTAddCity)
                {
                    _bRGVoucherBTAddCity = value;
                    NotifyChanged("BRGVoucherBTAddCity");
                }
            }
        }
        public String BRGVoucherBTAddPCode
        {
            get { return _bRGVoucherBTAddPCode; }
            set
            {
                if (value != this._bRGVoucherBTAddPCode)
                {
                    _bRGVoucherBTAddPCode = value;
                    NotifyChanged("BRGVoucherBTAddPCode");
                }
            }
        }
        public String BRGVoucherBTAddStProv
        {
            get { return _bRGVoucherBTAddStProv; }
            set
            {
                if (value != this._bRGVoucherBTAddStProv)
                {
                    _bRGVoucherBTAddStProv = value;
                    NotifyChanged("BRGVoucherBTAddStProv");
                }
            }
        }
        public String BRGVoucherBTAddZCode
        {
            get { return _bRGVoucherBTAddZCode; }
            set
            {
                if (value != this._bRGVoucherBTAddZCode)
                {
                    _bRGVoucherBTAddZCode = value;
                    NotifyChanged("BRGVoucherBTAddZCode");
                }
            }
        }
        public String BRGVoucherBTAddCountry
        {
            get { return _bRGVoucherBTAddCountry; }
            set
            {
                if (value != this._bRGVoucherBTAddCountry)
                {
                    _bRGVoucherBTAddCountry = value;
                    NotifyChanged("BRGVoucherBTAddCountry");
                }
            }
        }
        public String BRGVoucherSTConName
        {
            get { return _bRGVoucherSTConName; }
            set
            {
                if (value != this._bRGVoucherSTConName)
                {
                    _bRGVoucherSTConName = value;
                    NotifyChanged("BRGVoucherSTConName");
                }
            }
        }
        public Nullable<DateTime> BRGVoucherSTConBday
        {
            get { return _bRGVoucherSTConBday; }
            set
            {
                if (value != this._bRGVoucherSTConBday)
                {
                    _bRGVoucherSTConBday = value;
                    NotifyChanged("BRGVoucherSTConBday");
                }
            }
        }
        public String BRGVoucherSTConFName
        {
            get { return _bRGVoucherSTConFName; }
            set
            {
                if (value != this._bRGVoucherSTConFName)
                {
                    _bRGVoucherSTConFName = value;
                    NotifyChanged("BRGVoucherSTConFName");
                }
            }
        }
        public String BRGVoucherSTConLName
        {
            get { return _bRGVoucherSTConLName; }
            set
            {
                if (value != this._bRGVoucherSTConLName)
                {
                    _bRGVoucherSTConLName = value;
                    NotifyChanged("BRGVoucherSTConLName");
                }
            }
        }
        public String BRGVoucherSTConTitle
        {
            get { return _bRGVoucherSTConTitle; }
            set
            {
                if (value != this._bRGVoucherSTConTitle)
                {
                    _bRGVoucherSTConTitle = value;
                    NotifyChanged("BRGVoucherSTConTitle");
                }
            }
        }
        public String BRGVoucherSTConHLet
        {
            get { return _bRGVoucherSTConHLet; }
            set
            {
                if (value != this._bRGVoucherSTConHLet)
                {
                    _bRGVoucherSTConHLet = value;
                    NotifyChanged("BRGVoucherSTConHLet");
                }
            }
        }
        public String BRGVoucherSTConHMsg
        {
            get { return _bRGVoucherSTConHMsg; }
            set
            {
                if (value != this._bRGVoucherSTConHMsg)
                {
                    _bRGVoucherSTConHMsg = value;
                    NotifyChanged("BRGVoucherSTConHMsg");
                }
            }
        }
        public String BRGVoucherSTConEmail
        {
            get { return _bRGVoucherSTConEmail; }
            set
            {
                if (value != this._bRGVoucherSTConEmail)
                {
                    _bRGVoucherSTConEmail = value;
                    NotifyChanged("BRGVoucherSTConEmail");
                }
            }
        }
        public String BRGVoucherSTConEmail1
        {
            get { return _bRGVoucherSTConEmail1; }
            set
            {
                if (value != this._bRGVoucherSTConEmail1)
                {
                    _bRGVoucherSTConEmail1 = value;
                    NotifyChanged("BRGVoucherSTConEmail1");
                }
            }
        }
        public String BRGVoucherSTConPhone
        {
            get { return _bRGVoucherSTConPhone; }
            set
            {
                if (value != this._bRGVoucherSTConPhone)
                {
                    _bRGVoucherSTConPhone = value;
                    NotifyChanged("BRGVoucherSTConPhone");
                }
            }
        }
        public String BRGVoucherSTConCPhone
        {
            get { return _bRGVoucherSTConCPhone; }
            set
            {
                if (value != this._bRGVoucherSTConCPhone)
                {
                    _bRGVoucherSTConCPhone = value;
                    NotifyChanged("BRGVoucherSTConCPhone");
                }
            }
        }
        public String BRGVoucherSTConFax
        {
            get { return _bRGVoucherSTConFax; }
            set
            {
                if (value != this._bRGVoucherSTConFax)
                {
                    _bRGVoucherSTConFax = value;
                    NotifyChanged("BRGVoucherSTConFax");
                }
            }
        }
        public String BRGVoucherSTConInfo
        {
            get { return _bRGVoucherSTConInfo; }
            set
            {
                if (value != this._bRGVoucherSTConInfo)
                {
                    _bRGVoucherSTConInfo = value;
                    NotifyChanged("BRGVoucherSTConInfo");
                }
            }
        }
        public String BRGVoucherSTConDept
        {
            get { return _bRGVoucherSTConDept; }
            set
            {
                if (value != this._bRGVoucherSTConDept)
                {
                    _bRGVoucherSTConDept = value;
                    NotifyChanged("BRGVoucherSTConDept");
                }
            }
        }
        public String BRGVoucherSTConRoom
        {
            get { return _bRGVoucherSTConRoom; }
            set
            {
                if (value != this._bRGVoucherSTConRoom)
                {
                    _bRGVoucherSTConRoom = value;
                    NotifyChanged("BRGVoucherSTConRoom");
                }
            }
        }
        public String BRGVoucherSTAddL1
        {
            get { return _bRGVoucherSTAddL1; }
            set
            {
                if (value != this._bRGVoucherSTAddL1)
                {
                    _bRGVoucherSTAddL1 = value;
                    NotifyChanged("BRGVoucherSTAddL1");
                }
            }
        }
        public String BRGVoucherSTAddL2
        {
            get { return _bRGVoucherSTAddL2; }
            set
            {
                if (value != this._bRGVoucherSTAddL2)
                {
                    _bRGVoucherSTAddL2 = value;
                    NotifyChanged("BRGVoucherSTAddL2");
                }
            }
        }
        public String BRGVoucherSTAddL3
        {
            get { return _bRGVoucherSTAddL3; }
            set
            {
                if (value != this._bRGVoucherSTAddL3)
                {
                    _bRGVoucherSTAddL3 = value;
                    NotifyChanged("BRGVoucherSTAddL3");
                }
            }
        }
        public String BRGVoucherSTAddStr
        {
            get { return _bRGVoucherSTAddStr; }
            set
            {
                if (value != this._bRGVoucherSTAddStr)
                {
                    _bRGVoucherSTAddStr = value;
                    NotifyChanged("BRGVoucherSTAddStr");
                }
            }
        }
        public String BRGVoucherSTAddCity
        {
            get { return _bRGVoucherSTAddCity; }
            set
            {
                if (value != this._bRGVoucherSTAddCity)
                {
                    _bRGVoucherSTAddCity = value;
                    NotifyChanged("BRGVoucherSTAddCity");
                }
            }
        }
        public String BRGVoucherSTAddPCode
        {
            get { return _bRGVoucherSTAddPCode; }
            set
            {
                if (value != this._bRGVoucherSTAddPCode)
                {
                    _bRGVoucherSTAddPCode = value;
                    NotifyChanged("BRGVoucherSTAddPCode");
                }
            }
        }
        public String BRGVoucherSTAddStProv
        {
            get { return _bRGVoucherSTAddStProv; }
            set
            {
                if (value != this._bRGVoucherSTAddStProv)
                {
                    _bRGVoucherSTAddStProv = value;
                    NotifyChanged("BRGVoucherSTAddStProv");
                }
            }
        }
        public String BRGVoucherSTAddZCode
        {
            get { return _bRGVoucherSTAddZCode; }
            set
            {
                if (value != this._bRGVoucherSTAddZCode)
                {
                    _bRGVoucherSTAddZCode = value;
                    NotifyChanged("BRGVoucherSTAddZCode");
                }
            }
        }
        public String BRGVoucherSTAddCountry
        {
            get { return _bRGVoucherSTAddCountry; }
            set
            {
                if (value != this._bRGVoucherSTAddCountry)
                {
                    _bRGVoucherSTAddCountry = value;
                    NotifyChanged("BRGVoucherSTAddCountry");
                }
            }
        }
        #endregion
    }
    #endregion
}