using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region CMCorrespondenceDocs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:CMCorrespondenceDocsInfo
	//Created Date:Tuesday, June 09, 2009
	//-----------------------------------------------------------
	
	public class CMCorrespondenceDocsInfo:BusinessObject
	{
		public CMCorrespondenceDocsInfo()
		{
		}
		#region Variables
		protected int _cMCorrespondenceDocID;
		protected String _aAStatus=DefaultAAStatus;
		protected String _cMCorrespondenceDocNo=String.Empty;
		protected String _cMCorrespondenceDocName=String.Empty;
		protected int _fK_CMCorrespondenceID;
		protected String _cMCorrespondenceDocDesc=String.Empty;
		protected String _cMCorrespondenceDocLink=String.Empty;
		protected String _cMCorrespondenceDocFileName=String.Empty;
		protected String _cMCorrespondenceDocLocalPath=String.Empty;
		protected String _cMCorrespondenceDocServerPath=String.Empty;
		protected String _cMCorrespondenceDocStatusCombo=DefaultStatus;
		protected DateTime _cMCorrespondenceDocApprovedDate=DateTime.MaxValue;
		protected String _cMCorrespondenceDocApprovedBy=String.Empty;
		protected String _cMCorrespondenceDocReviewBy=String.Empty;
		protected String _aACreatedUser=String.Empty;
		protected String _aAUpdatedUser=String.Empty;
		protected DateTime _aACreatedDate=DateTime.MaxValue;
		protected DateTime _aAUpdatedDate=DateTime.MaxValue;
		#endregion

		#region Public properties
		public int CMCorrespondenceDocID
		{
			get{return _cMCorrespondenceDocID;}
			set
			{
				if (value != this._cMCorrespondenceDocID)
				{
				_cMCorrespondenceDocID=value;
				NotifyChanged("CMCorrespondenceDocID");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public String CMCorrespondenceDocNo
		{
			get{return _cMCorrespondenceDocNo;}
			set
			{
				if (value != this._cMCorrespondenceDocNo)
				{
				_cMCorrespondenceDocNo=value;
				NotifyChanged("CMCorrespondenceDocNo");
				}
			}
		}
		public String CMCorrespondenceDocName
		{
			get{return _cMCorrespondenceDocName;}
			set
			{
				if (value != this._cMCorrespondenceDocName)
				{
				_cMCorrespondenceDocName=value;
				NotifyChanged("CMCorrespondenceDocName");
				}
			}
		}
		public int FK_CMCorrespondenceID
		{
			get{return _fK_CMCorrespondenceID;}
			set
			{
				if (value != this._fK_CMCorrespondenceID)
				{
				_fK_CMCorrespondenceID=value;
				NotifyChanged("FK_CMCorrespondenceID");
				}
			}
		}
		public String CMCorrespondenceDocDesc
		{
			get{return _cMCorrespondenceDocDesc;}
			set
			{
				if (value != this._cMCorrespondenceDocDesc)
				{
				_cMCorrespondenceDocDesc=value;
				NotifyChanged("CMCorrespondenceDocDesc");
				}
			}
		}
		public String CMCorrespondenceDocLink
		{
			get{return _cMCorrespondenceDocLink;}
			set
			{
				if (value != this._cMCorrespondenceDocLink)
				{
				_cMCorrespondenceDocLink=value;
				NotifyChanged("CMCorrespondenceDocLink");
				}
			}
		}
		public String CMCorrespondenceDocFileName
		{
			get{return _cMCorrespondenceDocFileName;}
			set
			{
				if (value != this._cMCorrespondenceDocFileName)
				{
				_cMCorrespondenceDocFileName=value;
				NotifyChanged("CMCorrespondenceDocFileName");
				}
			}
		}
		public String CMCorrespondenceDocLocalPath
		{
			get{return _cMCorrespondenceDocLocalPath;}
			set
			{
				if (value != this._cMCorrespondenceDocLocalPath)
				{
				_cMCorrespondenceDocLocalPath=value;
				NotifyChanged("CMCorrespondenceDocLocalPath");
				}
			}
		}
		public String CMCorrespondenceDocServerPath
		{
			get{return _cMCorrespondenceDocServerPath;}
			set
			{
				if (value != this._cMCorrespondenceDocServerPath)
				{
				_cMCorrespondenceDocServerPath=value;
				NotifyChanged("CMCorrespondenceDocServerPath");
				}
			}
		}
		public String CMCorrespondenceDocStatusCombo
		{
			get{return _cMCorrespondenceDocStatusCombo;}
			set
			{
				if (value != this._cMCorrespondenceDocStatusCombo)
				{
				_cMCorrespondenceDocStatusCombo=value;
				NotifyChanged("CMCorrespondenceDocStatusCombo");
				}
			}
		}
		public DateTime CMCorrespondenceDocApprovedDate
		{
			get{return _cMCorrespondenceDocApprovedDate;}
			set
			{
				if (value != this._cMCorrespondenceDocApprovedDate)
				{
				_cMCorrespondenceDocApprovedDate=value;
				NotifyChanged("CMCorrespondenceDocApprovedDate");
				}
			}
		}
		public String CMCorrespondenceDocApprovedBy
		{
			get{return _cMCorrespondenceDocApprovedBy;}
			set
			{
				if (value != this._cMCorrespondenceDocApprovedBy)
				{
				_cMCorrespondenceDocApprovedBy=value;
				NotifyChanged("CMCorrespondenceDocApprovedBy");
				}
			}
		}
		public String CMCorrespondenceDocReviewBy
		{
			get{return _cMCorrespondenceDocReviewBy;}
			set
			{
				if (value != this._cMCorrespondenceDocReviewBy)
				{
				_cMCorrespondenceDocReviewBy=value;
				NotifyChanged("CMCorrespondenceDocReviewBy");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public DateTime AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public DateTime AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		#endregion
	}
	#endregion
}