using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region CMLeads
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:CMLeadsInfo
	//Created Date:07 Tháng Tám 2012
	//-----------------------------------------------------------
	
	public class CMLeadsInfo:BusinessObject
	{
		public CMLeadsInfo()
		{
		}
		#region Variables
		protected int _cMLeadID;
		protected Nullable<DateTime> _aACreatedDate;
		protected String _aACreatedUser=String.Empty;
		protected Nullable<DateTime> _aAUpdatedDate;
		protected String _aAUpdatedUser=String.Empty;
		protected String _aAStatus=DefaultAAStatus;
		protected bool _aASelected=true;
		protected String _cMLeadNo=String.Empty;
		protected String _cMLeadVocative=String.Empty;
		protected String _cMLeadLastName=String.Empty;
		protected String _cMLeadFirstName=String.Empty;
		protected String _cMLeadName=String.Empty;
		protected Nullable<DateTime> _cMLeadDate;
		protected String _cMLeadCompany=String.Empty;
		protected int _fK_CMPositionID;
		protected int _fK_CMSpecialityID;
		protected String _cMLeadOfficePhone=String.Empty;
		protected String _cMLeadHomePhone=String.Empty;
		protected String _cMLeadOtherPhone=String.Empty;
		protected String _cMLeadMobile=String.Empty;
		protected String _cMLeadOtherMobile=String.Empty;
		protected String _cMLeadAgencyAddress=String.Empty;
		protected String _cMLeadHomeAddress=String.Empty;
		protected String _cMLeadFax=String.Empty;
		protected String _cMLeadEmail=String.Empty;
		protected String _cMLeadOfficeEmail=String.Empty;
		protected byte[] _cMLeadPicture;
		protected String _cMLeadWebsite=String.Empty;
		protected int _fK_CMIndustryID;
		protected int _fK_CMDepartmentID;
		protected int _fK_CMCompanySizeID;
		protected int _fK_CMRevenueSizeID;
		protected int _fK_CMOriginID;
		protected int _fK_CMStateID;
		protected String _cMLeadRatingCombo=String.Empty;
		protected int _fK_CMClassificationID;
		protected String _cMLeadDesc=String.Empty;
		protected int _fK_HREmployeeID;
		protected bool _cMLeadIsPublic=true;
		protected int _fK_CMContactID;
		protected int _fK_CMCampaignID;
		protected bool _cMLeadIsActived=true;
		protected int _fK_ARSellerID;
		protected Nullable<DateTime> _cMLeadAssignDate;
		protected Nullable<DateTime> _cMLeadBDate;
		protected String _cMLeadSkype=String.Empty;
		protected String _cMLeadYahoo=String.Empty;
		protected String _cMLeadFacebook=String.Empty;
		protected String _cMLeadShippingAddress=String.Empty;
		protected String _cMLeadBillingAddress=String.Empty;
		protected int _fK_CMRegionID;
		protected double _cMLeadCostAmt;
		protected bool _cMLeadIsConverted=true;
		protected int _fK_ARCustomerID;
		#endregion

		#region Public properties
		public int CMLeadID
		{
			get{return _cMLeadID;}
			set
			{
				if (value != this._cMLeadID)
				{
				_cMLeadID=value;
				NotifyChanged("CMLeadID");
				}
			}
		}
		public Nullable<DateTime> AACreatedDate
		{
			get{return _aACreatedDate;}
			set
			{
				if (value != this._aACreatedDate)
				{
				_aACreatedDate=value;
				NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AACreatedUser
		{
			get{return _aACreatedUser;}
			set
			{
				if (value != this._aACreatedUser)
				{
				_aACreatedUser=value;
				NotifyChanged("AACreatedUser");
				}
			}
		}
		public Nullable<DateTime> AAUpdatedDate
		{
			get{return _aAUpdatedDate;}
			set
			{
				if (value != this._aAUpdatedDate)
				{
				_aAUpdatedDate=value;
				NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get{return _aAUpdatedUser;}
			set
			{
				if (value != this._aAUpdatedUser)
				{
				_aAUpdatedUser=value;
				NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public bool AASelected
		{
			get{return _aASelected;}
			set
			{
				if (value != this._aASelected)
				{
				_aASelected=value;
				NotifyChanged("AASelected");
				}
			}
		}
		public String CMLeadNo
		{
			get{return _cMLeadNo;}
			set
			{
				if (value != this._cMLeadNo)
				{
				_cMLeadNo=value;
				NotifyChanged("CMLeadNo");
				}
			}
		}
		public String CMLeadVocative
		{
			get{return _cMLeadVocative;}
			set
			{
				if (value != this._cMLeadVocative)
				{
				_cMLeadVocative=value;
				NotifyChanged("CMLeadVocative");
				}
			}
		}
		public String CMLeadLastName
		{
			get{return _cMLeadLastName;}
			set
			{
				if (value != this._cMLeadLastName)
				{
				_cMLeadLastName=value;
				NotifyChanged("CMLeadLastName");
				}
			}
		}
		public String CMLeadFirstName
		{
			get{return _cMLeadFirstName;}
			set
			{
				if (value != this._cMLeadFirstName)
				{
				_cMLeadFirstName=value;
				NotifyChanged("CMLeadFirstName");
				}
			}
		}
		public String CMLeadName
		{
			get{return _cMLeadName;}
			set
			{
				if (value != this._cMLeadName)
				{
				_cMLeadName=value;
				NotifyChanged("CMLeadName");
				}
			}
		}
		public Nullable<DateTime> CMLeadDate
		{
			get{return _cMLeadDate;}
			set
			{
				if (value != this._cMLeadDate)
				{
				_cMLeadDate=value;
				NotifyChanged("CMLeadDate");
				}
			}
		}
		public String CMLeadCompany
		{
			get{return _cMLeadCompany;}
			set
			{
				if (value != this._cMLeadCompany)
				{
				_cMLeadCompany=value;
				NotifyChanged("CMLeadCompany");
				}
			}
		}
		public int FK_CMPositionID
		{
			get{return _fK_CMPositionID;}
			set
			{
				if (value != this._fK_CMPositionID)
				{
				_fK_CMPositionID=value;
				NotifyChanged("FK_CMPositionID");
				}
			}
		}
		public int FK_CMSpecialityID
		{
			get{return _fK_CMSpecialityID;}
			set
			{
				if (value != this._fK_CMSpecialityID)
				{
				_fK_CMSpecialityID=value;
				NotifyChanged("FK_CMSpecialityID");
				}
			}
		}
		public String CMLeadOfficePhone
		{
			get{return _cMLeadOfficePhone;}
			set
			{
				if (value != this._cMLeadOfficePhone)
				{
				_cMLeadOfficePhone=value;
				NotifyChanged("CMLeadOfficePhone");
				}
			}
		}
		public String CMLeadHomePhone
		{
			get{return _cMLeadHomePhone;}
			set
			{
				if (value != this._cMLeadHomePhone)
				{
				_cMLeadHomePhone=value;
				NotifyChanged("CMLeadHomePhone");
				}
			}
		}
		public String CMLeadOtherPhone
		{
			get{return _cMLeadOtherPhone;}
			set
			{
				if (value != this._cMLeadOtherPhone)
				{
				_cMLeadOtherPhone=value;
				NotifyChanged("CMLeadOtherPhone");
				}
			}
		}
		public String CMLeadMobile
		{
			get{return _cMLeadMobile;}
			set
			{
				if (value != this._cMLeadMobile)
				{
				_cMLeadMobile=value;
				NotifyChanged("CMLeadMobile");
				}
			}
		}
		public String CMLeadOtherMobile
		{
			get{return _cMLeadOtherMobile;}
			set
			{
				if (value != this._cMLeadOtherMobile)
				{
				_cMLeadOtherMobile=value;
				NotifyChanged("CMLeadOtherMobile");
				}
			}
		}
		public String CMLeadAgencyAddress
		{
			get{return _cMLeadAgencyAddress;}
			set
			{
				if (value != this._cMLeadAgencyAddress)
				{
				_cMLeadAgencyAddress=value;
				NotifyChanged("CMLeadAgencyAddress");
				}
			}
		}
		public String CMLeadHomeAddress
		{
			get{return _cMLeadHomeAddress;}
			set
			{
				if (value != this._cMLeadHomeAddress)
				{
				_cMLeadHomeAddress=value;
				NotifyChanged("CMLeadHomeAddress");
				}
			}
		}
		public String CMLeadFax
		{
			get{return _cMLeadFax;}
			set
			{
				if (value != this._cMLeadFax)
				{
				_cMLeadFax=value;
				NotifyChanged("CMLeadFax");
				}
			}
		}
		public String CMLeadEmail
		{
			get{return _cMLeadEmail;}
			set
			{
				if (value != this._cMLeadEmail)
				{
				_cMLeadEmail=value;
				NotifyChanged("CMLeadEmail");
				}
			}
		}
		public String CMLeadOfficeEmail
		{
			get{return _cMLeadOfficeEmail;}
			set
			{
				if (value != this._cMLeadOfficeEmail)
				{
				_cMLeadOfficeEmail=value;
				NotifyChanged("CMLeadOfficeEmail");
				}
			}
		}
		public byte[] CMLeadPicture
		{
			get{return _cMLeadPicture;}
			set
			{
				if (value != this._cMLeadPicture)
				{
				_cMLeadPicture=value;
				NotifyChanged("CMLeadPicture");
				}
			}
		}
		public String CMLeadWebsite
		{
			get{return _cMLeadWebsite;}
			set
			{
				if (value != this._cMLeadWebsite)
				{
				_cMLeadWebsite=value;
				NotifyChanged("CMLeadWebsite");
				}
			}
		}
		public int FK_CMIndustryID
		{
			get{return _fK_CMIndustryID;}
			set
			{
				if (value != this._fK_CMIndustryID)
				{
				_fK_CMIndustryID=value;
				NotifyChanged("FK_CMIndustryID");
				}
			}
		}
		public int FK_CMDepartmentID
		{
			get{return _fK_CMDepartmentID;}
			set
			{
				if (value != this._fK_CMDepartmentID)
				{
				_fK_CMDepartmentID=value;
				NotifyChanged("FK_CMDepartmentID");
				}
			}
		}
		public int FK_CMCompanySizeID
		{
			get{return _fK_CMCompanySizeID;}
			set
			{
				if (value != this._fK_CMCompanySizeID)
				{
				_fK_CMCompanySizeID=value;
				NotifyChanged("FK_CMCompanySizeID");
				}
			}
		}
		public int FK_CMRevenueSizeID
		{
			get{return _fK_CMRevenueSizeID;}
			set
			{
				if (value != this._fK_CMRevenueSizeID)
				{
				_fK_CMRevenueSizeID=value;
				NotifyChanged("FK_CMRevenueSizeID");
				}
			}
		}
		public int FK_CMOriginID
		{
			get{return _fK_CMOriginID;}
			set
			{
				if (value != this._fK_CMOriginID)
				{
				_fK_CMOriginID=value;
				NotifyChanged("FK_CMOriginID");
				}
			}
		}
		public int FK_CMStateID
		{
			get{return _fK_CMStateID;}
			set
			{
				if (value != this._fK_CMStateID)
				{
				_fK_CMStateID=value;
				NotifyChanged("FK_CMStateID");
				}
			}
		}
		public String CMLeadRatingCombo
		{
			get{return _cMLeadRatingCombo;}
			set
			{
				if (value != this._cMLeadRatingCombo)
				{
				_cMLeadRatingCombo=value;
				NotifyChanged("CMLeadRatingCombo");
				}
			}
		}
		public int FK_CMClassificationID
		{
			get{return _fK_CMClassificationID;}
			set
			{
				if (value != this._fK_CMClassificationID)
				{
				_fK_CMClassificationID=value;
				NotifyChanged("FK_CMClassificationID");
				}
			}
		}
		public String CMLeadDesc
		{
			get{return _cMLeadDesc;}
			set
			{
				if (value != this._cMLeadDesc)
				{
				_cMLeadDesc=value;
				NotifyChanged("CMLeadDesc");
				}
			}
		}
		public int FK_HREmployeeID
		{
			get{return _fK_HREmployeeID;}
			set
			{
				if (value != this._fK_HREmployeeID)
				{
				_fK_HREmployeeID=value;
				NotifyChanged("FK_HREmployeeID");
				}
			}
		}
		public bool CMLeadIsPublic
		{
			get{return _cMLeadIsPublic;}
			set
			{
				if (value != this._cMLeadIsPublic)
				{
				_cMLeadIsPublic=value;
				NotifyChanged("CMLeadIsPublic");
				}
			}
		}
		public int FK_CMContactID
		{
			get{return _fK_CMContactID;}
			set
			{
				if (value != this._fK_CMContactID)
				{
				_fK_CMContactID=value;
				NotifyChanged("FK_CMContactID");
				}
			}
		}
		public int FK_CMCampaignID
		{
			get{return _fK_CMCampaignID;}
			set
			{
				if (value != this._fK_CMCampaignID)
				{
				_fK_CMCampaignID=value;
				NotifyChanged("FK_CMCampaignID");
				}
			}
		}
		public bool CMLeadIsActived
		{
			get{return _cMLeadIsActived;}
			set
			{
				if (value != this._cMLeadIsActived)
				{
				_cMLeadIsActived=value;
				NotifyChanged("CMLeadIsActived");
				}
			}
		}
		public int FK_ARSellerID
		{
			get{return _fK_ARSellerID;}
			set
			{
				if (value != this._fK_ARSellerID)
				{
				_fK_ARSellerID=value;
				NotifyChanged("FK_ARSellerID");
				}
			}
		}
		public Nullable<DateTime> CMLeadAssignDate
		{
			get{return _cMLeadAssignDate;}
			set
			{
				if (value != this._cMLeadAssignDate)
				{
				_cMLeadAssignDate=value;
				NotifyChanged("CMLeadAssignDate");
				}
			}
		}
		public Nullable<DateTime> CMLeadBDate
		{
			get{return _cMLeadBDate;}
			set
			{
				if (value != this._cMLeadBDate)
				{
				_cMLeadBDate=value;
				NotifyChanged("CMLeadBDate");
				}
			}
		}
		public String CMLeadSkype
		{
			get{return _cMLeadSkype;}
			set
			{
				if (value != this._cMLeadSkype)
				{
				_cMLeadSkype=value;
				NotifyChanged("CMLeadSkype");
				}
			}
		}
		public String CMLeadYahoo
		{
			get{return _cMLeadYahoo;}
			set
			{
				if (value != this._cMLeadYahoo)
				{
				_cMLeadYahoo=value;
				NotifyChanged("CMLeadYahoo");
				}
			}
		}
		public String CMLeadFacebook
		{
			get{return _cMLeadFacebook;}
			set
			{
				if (value != this._cMLeadFacebook)
				{
				_cMLeadFacebook=value;
				NotifyChanged("CMLeadFacebook");
				}
			}
		}
		public String CMLeadShippingAddress
		{
			get{return _cMLeadShippingAddress;}
			set
			{
				if (value != this._cMLeadShippingAddress)
				{
				_cMLeadShippingAddress=value;
				NotifyChanged("CMLeadShippingAddress");
				}
			}
		}
		public String CMLeadBillingAddress
		{
			get{return _cMLeadBillingAddress;}
			set
			{
				if (value != this._cMLeadBillingAddress)
				{
				_cMLeadBillingAddress=value;
				NotifyChanged("CMLeadBillingAddress");
				}
			}
		}
		public int FK_CMRegionID
		{
			get{return _fK_CMRegionID;}
			set
			{
				if (value != this._fK_CMRegionID)
				{
				_fK_CMRegionID=value;
				NotifyChanged("FK_CMRegionID");
				}
			}
		}
		public double CMLeadCostAmt
		{
			get{return _cMLeadCostAmt;}
			set
			{
				if (value != this._cMLeadCostAmt)
				{
				_cMLeadCostAmt=value;
				NotifyChanged("CMLeadCostAmt");
				}
			}
		}
		public bool CMLeadIsConverted
		{
			get{return _cMLeadIsConverted;}
			set
			{
				if (value != this._cMLeadIsConverted)
				{
				_cMLeadIsConverted=value;
				NotifyChanged("CMLeadIsConverted");
				}
			}
		}
		public int FK_ARCustomerID
		{
			get{return _fK_ARCustomerID;}
			set
			{
				if (value != this._fK_ARCustomerID)
				{
				_fK_ARCustomerID=value;
				NotifyChanged("FK_ARCustomerID");
				}
			}
		}
		#endregion
	}
	#endregion
}