using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
    #region CMWarantyHistoryActions
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:CMWarantyHistoryActionsInfo
    //Created Date:Saturday, July 02, 2011
    //-----------------------------------------------------------

    public class CMWarantyHistoryActionsInfo : BusinessObject
    {
        public CMWarantyHistoryActionsInfo()
        {
        }

        #region Variables
        protected int _cMWarantyHistoryActionID;
        protected Nullable<DateTime> _aACreatedDate;
        protected String _aACreatedUser = String.Empty;
        protected Nullable<DateTime> _aAUpdatedDate;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected bool _aASelected = true;
        protected int _fK_CMWarantyHistoryID;
        protected int _fK_ICProductID;
        protected int _fK_ICStockID;
        protected double _cMWarantyHistoryActionQty;
        protected String _cMWarantyHistoryActionSerial = String.Empty;
        protected String _cMWarantyHistoryActionReason = String.Empty;
        protected String _cMWarantyHistoryActionType = String.Empty;
        protected String _cMWarantyHistoryActionStatus = DefaultStatus;
        protected double _cMWarantyHistoryActionReturnAmt;
        protected double _cMWarantyHistoryActionCostAmt;
        protected Nullable<DateTime> _cMWarantyHistoryActionDate;
        #endregion

        #region Public properties
        public int CMWarantyHistoryActionID
        {
            get { return _cMWarantyHistoryActionID; }
            set
            {
                if (value != this._cMWarantyHistoryActionID)
                {
                    _cMWarantyHistoryActionID = value;
                    NotifyChanged("CMWarantyHistoryActionID");
                }
            }
        }
        public Nullable<DateTime> AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public Nullable<DateTime> AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public bool AASelected
        {
            get { return _aASelected; }
            set
            {
                if (value != this._aASelected)
                {
                    _aASelected = value;
                    NotifyChanged("AASelected");
                }
            }
        }
        public int FK_CMWarantyHistoryID
        {
            get { return _fK_CMWarantyHistoryID; }
            set
            {
                if (value != this._fK_CMWarantyHistoryID)
                {
                    _fK_CMWarantyHistoryID = value;
                    NotifyChanged("FK_CMWarantyHistoryID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public double CMWarantyHistoryActionQty
        {
            get { return _cMWarantyHistoryActionQty; }
            set
            {
                if (value != this._cMWarantyHistoryActionQty)
                {
                    _cMWarantyHistoryActionQty = value;
                    NotifyChanged("CMWarantyHistoryActionQty");
                }
            }
        }
        public String CMWarantyHistoryActionSerial
        {
            get { return _cMWarantyHistoryActionSerial; }
            set
            {
                if (value != this._cMWarantyHistoryActionSerial)
                {
                    _cMWarantyHistoryActionSerial = value;
                    NotifyChanged("CMWarantyHistoryActionSerial");
                }
            }
        }
        public String CMWarantyHistoryActionReason
        {
            get { return _cMWarantyHistoryActionReason; }
            set
            {
                if (value != this._cMWarantyHistoryActionReason)
                {
                    _cMWarantyHistoryActionReason = value;
                    NotifyChanged("CMWarantyHistoryActionReason");
                }
            }
        }
        public String CMWarantyHistoryActionType
        {
            get { return _cMWarantyHistoryActionType; }
            set
            {
                if (value != this._cMWarantyHistoryActionType)
                {
                    _cMWarantyHistoryActionType = value;
                    NotifyChanged("CMWarantyHistoryActionType");
                }
            }
        }
        public String CMWarantyHistoryActionStatus
        {
            get { return _cMWarantyHistoryActionStatus; }
            set
            {
                if (value != this._cMWarantyHistoryActionStatus)
                {
                    _cMWarantyHistoryActionStatus = value;
                    NotifyChanged("CMWarantyHistoryActionStatus");
                }
            }
        }
        public double CMWarantyHistoryActionReturnAmt
        {
            get { return _cMWarantyHistoryActionReturnAmt; }
            set
            {
                if (value != this._cMWarantyHistoryActionReturnAmt)
                {
                    _cMWarantyHistoryActionReturnAmt = value;
                    NotifyChanged("CMWarantyHistoryActionReturnAmt");
                }
            }
        }
        public double CMWarantyHistoryActionCostAmt
        {
            get { return _cMWarantyHistoryActionCostAmt; }
            set
            {
                if (value != this._cMWarantyHistoryActionCostAmt)
                {
                    _cMWarantyHistoryActionCostAmt = value;
                    NotifyChanged("CMWarantyHistoryActionCostAmt");
                }
            }
        }
        public Nullable<DateTime> CMWarantyHistoryActionDate
        {
            get { return _cMWarantyHistoryActionDate; }
            set
            {
                if (value != this._cMWarantyHistoryActionDate)
                {
                    _cMWarantyHistoryActionDate = value;
                    NotifyChanged("CMWarantyHistoryActionDate");
                }
            }
        }
        #endregion
    }
    #endregion
}