using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region ICInventoryStockLotNos
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:ICInventoryStockLotNosInfo
	//Created Date:Tuesday, January 6, 2015
	//-----------------------------------------------------------
	
	public class ICInventoryStockLotNosInfo:BusinessObject
	{
		public ICInventoryStockLotNosInfo()
		{
		}
		#region Variables
		protected int _iCInventoryStockLotNoID;
		protected String _aAStatus=DefaultAAStatus;
		protected int _fK_ICProductID;
		protected int _fK_ICStockID;
		protected String _iCInventoryStockLotNoProductLotNo=String.Empty;
		protected double _iCInventoryStockLotNoQuantity;
		protected double _iCInventoryStockLotNoProposalQuantity;
		protected double _iCInventoryStockLotNoSaleOrderQuantity;
		protected double _iCInventoryStockLotNoPurchaseOrderQuantity;
		protected Nullable<DateTime> _iCInventoryStockLotNoExpireDate;
		#endregion

		#region Public properties
		public int ICInventoryStockLotNoID
		{
			get{return _iCInventoryStockLotNoID;}
			set
			{
				if (value != this._iCInventoryStockLotNoID)
				{
				_iCInventoryStockLotNoID=value;
				NotifyChanged("ICInventoryStockLotNoID");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_ICStockID
		{
			get{return _fK_ICStockID;}
			set
			{
				if (value != this._fK_ICStockID)
				{
				_fK_ICStockID=value;
				NotifyChanged("FK_ICStockID");
				}
			}
		}
		public String ICInventoryStockLotNoProductLotNo
		{
			get{return _iCInventoryStockLotNoProductLotNo;}
			set
			{
				if (value != this._iCInventoryStockLotNoProductLotNo)
				{
				_iCInventoryStockLotNoProductLotNo=value;
				NotifyChanged("ICInventoryStockLotNoProductLotNo");
				}
			}
		}
		public double ICInventoryStockLotNoQuantity
		{
			get{return _iCInventoryStockLotNoQuantity;}
			set
			{
				if (value != this._iCInventoryStockLotNoQuantity)
				{
				_iCInventoryStockLotNoQuantity=value;
				NotifyChanged("ICInventoryStockLotNoQuantity");
				}
			}
		}
		public double ICInventoryStockLotNoProposalQuantity
		{
			get{return _iCInventoryStockLotNoProposalQuantity;}
			set
			{
				if (value != this._iCInventoryStockLotNoProposalQuantity)
				{
				_iCInventoryStockLotNoProposalQuantity=value;
				NotifyChanged("ICInventoryStockLotNoProposalQuantity");
				}
			}
		}
		public double ICInventoryStockLotNoSaleOrderQuantity
		{
			get{return _iCInventoryStockLotNoSaleOrderQuantity;}
			set
			{
				if (value != this._iCInventoryStockLotNoSaleOrderQuantity)
				{
				_iCInventoryStockLotNoSaleOrderQuantity=value;
				NotifyChanged("ICInventoryStockLotNoSaleOrderQuantity");
				}
			}
		}
		public double ICInventoryStockLotNoPurchaseOrderQuantity
		{
			get{return _iCInventoryStockLotNoPurchaseOrderQuantity;}
			set
			{
				if (value != this._iCInventoryStockLotNoPurchaseOrderQuantity)
				{
				_iCInventoryStockLotNoPurchaseOrderQuantity=value;
				NotifyChanged("ICInventoryStockLotNoPurchaseOrderQuantity");
				}
			}
		}
		public Nullable<DateTime> ICInventoryStockLotNoExpireDate
		{
			get{return _iCInventoryStockLotNoExpireDate;}
			set
			{
				if (value != this._iCInventoryStockLotNoExpireDate)
				{
				_iCInventoryStockLotNoExpireDate=value;
				NotifyChanged("ICInventoryStockLotNoExpireDate");
				}
			}
		}
		#endregion
	}
	#endregion
}