using System;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
    #region ICItemHistorys
    //-----------------------------------------------------------
    //Generated By: GMC Studio
    //Class:ICItemHistorysInfo
    //Created Date:Wednesday, March 03, 2010
    //-----------------------------------------------------------

    public class ICItemHistorysInfo : BusinessObject
    {
        public ICItemHistorysInfo()
        {
        }
        #region Variables
        protected int _iCItemHistoryID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICStockID;
        protected DateTime _iCItemHistoryFromDate = DateTime.Now;
        protected DateTime _iCItemHistoryToDate = DateTime.Now;
        protected double _iCItemHistoryRemainStockQty;
        protected double _iCItemHistoryReceiptQty;
        protected double _iCItemHistoryShipmentQty;
        protected double _iCItemHistoryTransferReceiptQty;
        protected double _iCItemHistoryTransferShipmentQty;
        #endregion

        #region Public properties
        public int ICItemHistoryID
        {
            get { return _iCItemHistoryID; }
            set
            {
                if (value != this._iCItemHistoryID)
                {
                    _iCItemHistoryID = value;
                    NotifyChanged("ICItemHistoryID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public DateTime ICItemHistoryFromDate
        {
            get { return _iCItemHistoryFromDate; }
            set
            {
                if (value != this._iCItemHistoryFromDate)
                {
                    _iCItemHistoryFromDate = value;
                    NotifyChanged("ICItemHistoryFromDate");
                }
            }
        }
        public DateTime ICItemHistoryToDate
        {
            get { return _iCItemHistoryToDate; }
            set
            {
                if (value != this._iCItemHistoryToDate)
                {
                    _iCItemHistoryToDate = value;
                    NotifyChanged("ICItemHistoryToDate");
                }
            }
        }
        public double ICItemHistoryRemainStockQty
        {
            get { return _iCItemHistoryRemainStockQty; }
            set
            {
                if (value != this._iCItemHistoryRemainStockQty)
                {
                    _iCItemHistoryRemainStockQty = value;
                    NotifyChanged("ICItemHistoryRemainStockQty");
                }
            }
        }
        public double ICItemHistoryReceiptQty
        {
            get { return _iCItemHistoryReceiptQty; }
            set
            {
                if (value != this._iCItemHistoryReceiptQty)
                {
                    _iCItemHistoryReceiptQty = value;
                    NotifyChanged("ICItemHistoryReceiptQty");
                }
            }
        }
        public double ICItemHistoryShipmentQty
        {
            get { return _iCItemHistoryShipmentQty; }
            set
            {
                if (value != this._iCItemHistoryShipmentQty)
                {
                    _iCItemHistoryShipmentQty = value;
                    NotifyChanged("ICItemHistoryShipmentQty");
                }
            }
        }
        public double ICItemHistoryTransferReceiptQty
        {
            get { return _iCItemHistoryTransferReceiptQty; }
            set
            {
                if (value != this._iCItemHistoryTransferReceiptQty)
                {
                    _iCItemHistoryTransferReceiptQty = value;
                    NotifyChanged("ICItemHistoryTransferReceiptQty");
                }
            }
        }
        public double ICItemHistoryTransferShipmentQty
        {
            get { return _iCItemHistoryTransferShipmentQty; }
            set
            {
                if (value != this._iCItemHistoryTransferShipmentQty)
                {
                    _iCItemHistoryTransferShipmentQty = value;
                    NotifyChanged("ICItemHistoryTransferShipmentQty");
                }
            }
        }
        #endregion
    }
    #endregion
}