using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRAllowanceRates
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HRAllowanceRatesController
	//Created Date:Wednesday, April 08, 2009
	//-----------------------------------------------------------
	
	public class HRAllowanceRatesController:BaseBusinessController
	{
		public HRAllowanceRatesController()
		{
			dal= new DALBaseProvider("HRAllowanceRates",typeof(HRAllowanceRatesInfo));
		}
	}
	#endregion
}