using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HREmployees
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HREmployeesController
	//Created Date:Wednesday, April 08, 2009
	//-----------------------------------------------------------
    
	public class HREmployeesController:BaseBusinessController
	{
        private static readonly string spGetEmployeeByUserName = "HREmployees_SelectByUserName";

        private static readonly string spGetEmployeesEndWorkingDateLessThanDate = "HREmployees_SelectEndWorkingDateLessThanDate";

		public HREmployeesController()
		{
			dal= new DALBaseProvider("HREmployees",typeof(HREmployeesInfo));
		}
        public double GetTotalEmployeeByDepartmentSectionAndStatus(int iDepartmentID, int iSectionID, string strStatusCombo)
        {
            String str = String.Format(@"   SELECT count(*) FROM dbo.HREmployees
                                            WHERE AAStatus='Alive'
                                            AND (FK_HRDepartmentID = {0} OR {0} = 0)
                                            AND (FK_HRSectionID = {1} OR {1} = 0)
                                          AND HREmployeeStatusCombo = '{2}'", iDepartmentID, iSectionID, strStatusCombo);
            DataSet ds = dal.GetDataSet(str);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return Convert.ToDouble(ds.Tables[0].Rows[0][0]);
            return 0;

        }
       public DataSet GetAllEmployeeByDepartmentSectionAndStatus(int iDepartmentID, int iSectionID, string strStatusCombo)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                            WHERE AAStatus='Alive'
                                            AND (FK_HRDepartmentID = {0} OR {0} = 0)
                                            AND (FK_HRSectionID = {1} OR {1} = 0)
                                          AND HREmployeeStatusCombo = '{2}'", iDepartmentID, iSectionID, strStatusCombo);
            return dal.GetDataSet(str);
        }
        public HREmployeesInfo GetEmployeeByUserName(String strUserName)
        {
            return (HREmployeesInfo)dal.GetDataObject(spGetEmployeeByUserName, strUserName);
        }

        public DataSet GetEmployeesWhichEndWorkingDateLessThanDate(DateTime dtDate)
        {
            return (DataSet)dal.GetDataSet(spGetEmployeesEndWorkingDateLessThanDate, dtDate);
        }

        #region Copy From PS --Vinh --10/01/2013

        public HREmployeesInfo GetObjectByCardNumber(String cardNumber)
        {

            DataSet ds = dal.GetDataSet("HREmployees_SelectByCardNumber", cardNumber);
            if (ds != null && ds.Tables[0].Rows.Count > 0)
                return (HREmployeesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return null;

        }

        #endregion

        #region GetAllEmployeeByType

        public DataSet GetAllEmployeeBySalaryCalcType(String strType)
        {
            String str = String.Format(@"SELECT * FROM HREmployees WHERE AAStatus='Alive' AND HREmployeeSalaryCalcTypeCombo='{0}'", strType);

            return dal.GetDataSet(str);
        }

        #endregion

        #region Lấy tất cả nhân viên theo Phòng ban, bộ phận, chuyền nhóm, khu vực -- Vinh --23/05/2013

        public DataSet GetAllEmployeeByDepartmentSectionGroupStockType(int iDepartmentID, int iSectionID, int iGroupID, int iStockTypeID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                            WHERE AAStatus='Alive'
                                            AND (FK_HRDepartmentID = {0} OR {0} = 0)
                                            AND (FK_HRSectionID = {1} OR {1} = 0)
                                            AND (FK_HRGroupID = {2} OR {2} = 0)
                                            AND (FK_ICStockTypeID = {3} OR {3} = 0)", iDepartmentID, iSectionID, iGroupID, iStockTypeID);
            return dal.GetDataSet(str);
        }

        #endregion

        public DataSet GetAllDataByDepartmentAndZone(int iDepartmentID, int iZoneID)
        {
            string strQuery = string.Format(@"Select * from HREmployees where AAStatus='Alive' AND (FK_HRDepartmentID={0} or {0}=0)
                                                    AND (FK_ARZoneID={1} or {1}=0)", iDepartmentID, iZoneID);
            return dal.GetDataSet(strQuery);
        }
        public DataSet GetAllEmployeeByZone(int iZoneID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                            WHERE AAStatus = 'Alive'
                                            AND (FK_ARZoneID = {0} OR {0} = 0)", iZoneID);

            return dal.GetDataSet(str);
        }

        public int GetTotalEmployeeInDeliveryZone(int iZoneID)
        {
            string strQuery = string.Format(@"Select Count(*) from HREmployees where AAStatus='Alive' AND (FK_ARZoneID={0} or {0}=0)
                                                  AND FK_HRDepartmentID in (select FK_HRDeliveryDepartmentID from ARSetups where AAStatus='Alive')"
                                                , iZoneID);
            DataSet ds = dal.GetDataSet(strQuery);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return Convert.ToInt32(ds.Tables[0].Rows[0][0]);
            return 0;
        }

        public HREmployeesInfo GetObjectByUser(string strUserName)
        {
            string strQuery = String.Format(@"SELECT * FROM ADUsers WHERE AAStatus = 'Alive' AND ADUserName = '{0}'", strUserName);
            DataSet ds = new ADUsersController().GetDataSet(strQuery);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
               ADUsersInfo CurrentUser = (ADUsersInfo)new ADUsersController().GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                if (CurrentUser != null)
                {
                    strQuery = String.Format(@"SELECT * FROM HREmployees WHERE AAStatus = 'Alive' AND FK_ADUserID = '{0}'", CurrentUser.ADUserID);
                    DataSet dsEmployee = new HREmployeesController().GetDataSet(strQuery);
                    if (dsEmployee != null && dsEmployee.Tables.Count > 0 && dsEmployee.Tables[0].Rows.Count > 0)
                        return (HREmployeesInfo)new HREmployeesController().GetObjectFromDataRow(dsEmployee.Tables[0].Rows[0]);
                }
            }
            return null;
        }

        public DataSet GetAllEmployeeByDepartmentSectionGroupStockTypeAndNo(int iDepartmentID, int iSectionID, int iGroupID, int iStockTypeID, String strNo)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                            WHERE AAStatus='Alive'
                                            AND (FK_HRDepartmentID = {0} OR {0} = 0)
                                            AND (FK_HRSectionID = {1} OR {1} = 0)
                                            AND (FK_HRGroupID = {2} OR {2} = 0)
                                            AND (FK_ICStockTypeID = {3} OR {3} = 0)
AND HREmployeeNo LIKE '%{4}%'", iDepartmentID, iSectionID, iGroupID, iStockTypeID, strNo);
            return dal.GetDataSet(str);
        }

        public DataSet GetAllEmployeeByEmployeeTCSlrType(String strHREmployeeTCSlrTypeCombo)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                            WHERE AAStatus = 'Alive'
                                            AND (HREmployeeTCSlrTypeCombo LIKE '{0}' OR '{0}' = '')", strHREmployeeTCSlrTypeCombo);
            return dal.GetDataSet(str);
        }

        public DataSet GetAllEmployeeByInsAdjType(string type, int iInsuranceStageID)
        {
            String str = String.Format(@"SELECT * 
                                        FROM dbo.HREmployees 
                                        WHERE AAStatus = 'Alive'
                                        AND HREmployeeID IN (
                                                                SELECT FK_HREmployeeID 
		                                                        FROM dbo.HRInsAdjs
		                                                        WHERE AAStatus = 'Alive'
				                                                AND HRInsAdjTypeCombo LIKE N'%{0}%' AND FK_HRInsuranceStageID = {1}  
                                                            )", type, iInsuranceStageID);
            return dal.GetDataSet(str);
        }

        public DataSet GetAllEmployeeByInsAdj()// lay ds nhan vien dang tham gia bao hiểm
        {
            String str = String.Format(@"SELECT * 
                                        FROM dbo.HREmployees 
                                        WHERE AAStatus = 'Alive'
                                        AND HREmployeeID IN (
                                                                SELECT FK_HREmployeeID 
		                                                        FROM dbo.HREmployeeInsurances
		                                                        WHERE AAStatus = 'Alive' AND HREmployeeInsuranceStatusCombo LIKE 'InDeclaration'
                                                            )");
            return dal.GetDataSet(str);
        }
        public DataSet GetAllEmployeeByInsurancebyNotInDeclaration()// ds nhan vien chưa tham gia hoặc tạm ngưng tham gia
        {
            String str = String.Format(@"SELECT * 
                                        FROM dbo.HREmployees 
                                        WHERE AAStatus = 'Alive'
	                                    AND HREmployeeID IN(
                                                                SELECT FK_HREmployeeID 
		                                                        FROM dbo.HREmployeeInsurances
		                                                        WHERE AAStatus='Alive'AND (HREmployeeInsuranceStatusCombo LIKE 'NotDeclaration' OR HREmployeeInsuranceStatusCombo LIKE 'StopNotDeclaration')
                                                            )");
            return dal.GetDataSet(str);
        }

        public bool CheckIsExistSlrAdj(int iEmployeeID, DateTime dtEffectDate)
        {
            String strDate = DALUtil.GennerateCondition("PRSlrAdjEffectDate", CompareType.LessEqualThan, dtEffectDate);
            String str = String.Format(@"SELECT  *
                                        FROM    dbo.PRSlrAdjItems
                                        WHERE   AAStatus = 'Alive'
                                                AND FK_PRSlrAdjID IN ( SELECT   PRSlrAdjID
                                                                       FROM     dbo.PRSlrAdjs
                                                                       WHERE    AAStatus = 'Alive' AND {1})
                                                AND PRSlrAdjItemStatusCombo='New'                                         
                                                AND FK_HREmployeeID = {0} ", iEmployeeID, strDate);
            DataSet ds = dal.GetDataSet(str);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                return true;

            return false;
        }

        public DataSet GetAllEmployeeByResource(int iResourceID)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployees
                                                WHERE AAStatus = 'Alive' 
                                                AND FK_HRDepartmentID in (select FK_HRDepartmentID from PPResources where AAStatus='Alive' AND ( PPResourceID={0} or {0}=0))
                                                AND 
		                                            (FK_HRSectionID in (select FK_HRSectionID from PPResources where AAStatus='Alive' and ( PPResourceID={0} or {0}=0))
		                                            or 0 in (select FK_HRSectionID from PPResources where AAStatus='Alive' and ( PPResourceID={0} or {0}=0))
		                                            )", iResourceID);

            return dal.GetDataSet(str);
        }
        public DataSet GetEmployeeByCondition(string strCondition, DateTime dtFDate, DateTime dtTDate)
        {
            if (!string.IsNullOrEmpty(strCondition))
                strCondition = " AND " + strCondition;

            String str = String.Format(@"SELECT * FROM dbo.HREmployees
                                         JOIN HREmpActivitys ON (HREmpActivitys.FK_HREmployeeID = HREmployees.HREmployeeID AND HREmpActivitys.AAStatus=HREmployees.AAStatus)
                                            WHERE HREmployees.AAStatus='Alive' AND (HREmpActivitys.HREmployeeStatusCombo LIKE 'Working' OR HREmpActivitys.HREmployeeStatusCombo LIKE 'Trying')
                                            AND ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{2}'
                                            AND HREmpActivityEndDate IS NULL
                                          )
                                          OR ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{1}'
                                                 AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{1}'
                                               )
                                               OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{2}'
                                                    AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{2}'
                                                  )
                                               OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) >= '{1}'
                                                    AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) <= '{2}'
                                                  )
                                             )
                                        ) {0}", strCondition, dtFDate.ToString("yyyyMMdd"), dtTDate.ToString("yyyyMMdd"));
            return GetDataSet(str);
        }
        public DataSet GetEmployeeBySellerANDCondition(string strCondition)
        {
            if (!string.IsNullOrEmpty(strCondition))
                strCondition = " AND " + strCondition;

            String str = String.Format(@"SELECT * FROM dbo.HREmployees WHERE AAStatus = 'Alive' AND HREmployeeID IN 
                                        (SELECT FK_HREmployeeID FROM dbo.ARSellers
			                            WHERE AAStatus = 'Alive' {0})", strCondition);

            return GetDataSet(str);
        }
        public DataSet GetAllEmployeeByConditionCalculateSalary(string strEmployeeNo, int iDepartmentID, int iSectionID, DateTime dtFrom, DateTime dtTo)
        {
            String str = String.Format(@"SELECT *
                                        FROM dbo.HREmployees
                                        LEFT JOIN dbo.HRDepartments ON (HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID AND HRDepartments.AAStatus = HREmployees.AAStatus)
                                        LEFT JOIN dbo.HRSections ON (HRSections.HRSectionID = HREmployees.FK_HRSectionID AND HRSections.AAStatus = HREmployees.AAStatus)
                                        JOIN HREmpActivitys ON (HREmpActivitys.FK_HREmployeeID = HREmployees.HREmployeeID AND HREmpActivitys.AAStatus=HREmployees.AAStatus)
                                        WHERE HREmployees.AAStatus='Alive' AND (HREmpActivitys.HREmployeeStatusCombo LIKE 'Working' OR HREmpActivitys.HREmployeeStatusCombo LIKE 'Trying')
                                        AND ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{4}'
                                            AND HREmpActivityEndDate IS NULL
                                          )
                                          OR ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{3}'
                                                 AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{3}'
                                               )
                                               OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{4}'
                                                    AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{4}'
                                                  )
                                               OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) >= '{3}'
                                                    AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) <= '{4}'
                                                  )
                                             )
                                        )
                                        AND  HREmployees.HREmployeeNo LIKE '%{0}%'
                                        AND (HREmployees.FK_HRDepartmentID ={1} OR  0={1})
                                        AND (HREmployees.FK_HRSectionID ={2} OR  0={2})
                                        ", strEmployeeNo, iDepartmentID, iSectionID, dtFrom.ToString("yyyyMMdd"), dtTo.ToString("yyyyMMdd"));
            return dal.GetDataSet(str);
        }
        public DataSet GetAllDataByConditionSalaryQuery(string strEmployeeNo, int iDepartmentID, int iSectionID, DateTime dtFrom, DateTime dtTo)
        {
            //+hiện các nv ko có làm việc nhưng có trong biến động tiền lương sẽ hiện lên
            String str = String.Format(@"( SELECT HREmployeeID ,
                                            HREmployeeNo ,
                                            HREmployeeCode01 ,
                                            HREmployeeFullName ,
                                            CONVERT(VARCHAR(10), HREmployeeStartWorkingDate, 103) HREmployeeStartWorkingDate ,
                                            CONVERT(VARCHAR(10), HREmployeeEndWorkingDate, 103) HREmployeeEndWorkingDate ,
                                            HREmployeeWorkingPlace ,
                                            HREmployeeBankAccount1 ,
                                            HREmployeeBankBranch ,
                                            HREmployeeBankCode ,
                                            HREmployeeBankName ,
                                            HRDepartmentName ,
                                            HRSectionName ,
                                            HRPositionName ,
                                            HRDivisionName ,
                                            BRBranchName ,
                                            HRLevName ,
                                            HRContractTypeName
                                    FROM      dbo.HREmployees
                                            LEFT JOIN dbo.HRDivisions ON ( HRDivisions.HRDivisionID = HREmployees.FK_HRDivisionID
                                                                            AND HRDivisions.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.HRDepartments ON ( HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID
                                                                                AND HRDepartments.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.HRSections ON ( HRSections.HRSectionID = HREmployees.FK_HRSectionID
                                                                            AND HRSections.AAStatus = HREmployees.AAStatus
                                                                        )
                                            LEFT JOIN dbo.HRPositions ON ( HRPositions.HRPositionID = HREmployees.FK_HRPositionID
                                                                            AND HRPositions.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.BRBranchs ON ( BRBranchs.BRBranchID = HREmployees.FK_BRBranchID
                                                                            AND BRBranchs.AAStatus = HREmployees.AAStatus
                                                                        )
                                            LEFT JOIN dbo.HRLevs ON ( HRLevs.HRLevID = HREmployees.FK_HRLevID
                                                                        AND HRLevs.AAStatus = HREmployees.AAStatus
                                                                    )
                                            LEFT JOIN dbo.HRContractTypes ON ( HRContractTypes.HRContractTypeID = HREmployees.FK_HRContractTypeID
                                                                                AND HRContractTypes.AAStatus = HREmployees.AAStatus
                                                                                )
                                            JOIN HREmpActivitys ON ( HREmpActivitys.FK_HREmployeeID = HREmployees.HREmployeeID
                                                                        AND HREmpActivitys.AAStatus = HREmployees.AAStatus
                                                                    )
                                    WHERE     HREmployees.AAStatus = 'Alive'
                                            AND ( HREmpActivitys.HREmployeeStatusCombo LIKE 'Working'
                                                    OR HREmpActivitys.HREmployeeStatusCombo LIKE 'Trying'
                                                )
                                            AND ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{4}'
                                                    AND HREmpActivityEndDate IS NULL
                                                    )
                                                    OR ( ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{3}'
                                                            AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{3}'
                                                        )
                                                        OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) <= '{4}'
                                                            AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) >= '{4}'
                                                            )
                                                        OR ( CONVERT(NVARCHAR(10), HREmpActivityStartDate, 112) >= '{3}'
                                                            AND CONVERT(NVARCHAR(10), HREmpActivityEndDate, 112) <= '{4}'
                                                            )
                                                        )
                                                )
                                            AND HREmployees.HREmployeeNo LIKE '%{0}%'
                                            AND ( HREmployees.FK_HRDepartmentID = {1}
                                                    OR 0 = {1}
                                                )
                                            AND ( HREmployees.FK_HRSectionID = {2}
                                                    OR 0 = {2}
                                                )
                                )
                                UNION
                                ( SELECT    HREmployeeID ,
                                            HREmployeeNo ,
                                            HREmployeeCode01 ,
                                            HREmployeeFullName ,
                                            CONVERT(VARCHAR(10), HREmployeeStartWorkingDate, 103) HREmployeeStartWorkingDate ,
                                            CONVERT(VARCHAR(10), HREmployeeEndWorkingDate, 103) HREmployeeEndWorkingDate ,
                                            HREmployeeWorkingPlace ,
                                            HREmployeeBankAccount1 ,
                                            HREmployeeBankBranch ,
                                            HREmployeeBankCode ,
                                            HREmployeeBankName ,
                                            HRDepartmentName ,
                                            HRSectionName ,
                                            HRPositionName ,
                                            HRDivisionName ,
                                            BRBranchName ,
                                            HRLevName ,
                                            HRContractTypeName
                                    FROM      dbo.HREmployees
                                            LEFT JOIN dbo.HRDivisions ON ( HRDivisions.HRDivisionID = HREmployees.FK_HRDivisionID
                                                                            AND HRDivisions.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.HRDepartments ON ( HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID
                                                                                AND HRDepartments.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.HRSections ON ( HRSections.HRSectionID = HREmployees.FK_HRSectionID
                                                                            AND HRSections.AAStatus = HREmployees.AAStatus
                                                                        )
                                            LEFT JOIN dbo.HRPositions ON ( HRPositions.HRPositionID = HREmployees.FK_HRPositionID
                                                                            AND HRPositions.AAStatus = HREmployees.AAStatus
                                                                            )
                                            LEFT JOIN dbo.BRBranchs ON ( BRBranchs.BRBranchID = HREmployees.FK_BRBranchID
                                                                            AND BRBranchs.AAStatus = HREmployees.AAStatus
                                                                        )
                                            LEFT JOIN dbo.HRLevs ON ( HRLevs.HRLevID = HREmployees.FK_HRLevID
                                                                        AND HRLevs.AAStatus = HREmployees.AAStatus
                                                                    )
                                            LEFT JOIN dbo.HRContractTypes ON ( HRContractTypes.HRContractTypeID = HREmployees.FK_HRContractTypeID
                                                                                AND HRContractTypes.AAStatus = HREmployees.AAStatus
                                                                                )
                                            JOIN dbo.HRBonusAllowanceItems ON ( HRBonusAllowanceItems.FK_HREmployeeID = HREmployees.HREmployeeID
                                                                                AND HRBonusAllowanceItems.AAStatus = HREmployees.AAStatus
                                                                                )
                                            JOIN dbo.HRBonusAllowances ON ( HRBonusAllowances.HRBonusAllowanceID = HRBonusAllowanceItems.FK_HRBonusAllowanceID
                                                                            AND HRBonusAllowances.AAStatus = HRBonusAllowanceItems.AAStatus
                                                                            )
                                    WHERE     HREmployees.AAStatus = 'Alive'
                                            AND HREmployees.HREmployeeNo LIKE '%{0}%'
                                            AND ( HREmployees.FK_HRDepartmentID = {1}
                                                    OR 0 = {1}
                                                )
                                            AND ( HREmployees.FK_HRSectionID = {2}
                                                    OR 0 = {2}
                                                )
                                            AND HRBonusAllowances.HRBonusAllowanceMonth = MONTH('{4}')
                                            AND HRBonusAllowances.HRBonusAllowanceYear = YEAR('{4}')
                                )", strEmployeeNo, iDepartmentID, iSectionID, dtFrom.ToString("yyyyMMdd"), dtTo.ToString("yyyyMMdd"));
            return dal.GetDataSet(str);
        }
        public DataSet GetAllEmployeeByCondition(string strEmployeeNo, int iDepartmentID, int iSectionID, DateTime dtFdate, DateTime dtTDate)
        {
            String str = String.Format(@"SELECT  ROW_NUMBER() OVER ( ORDER BY HREmployeeID ) STT ,
                                                HREmployeeID ,
                                                HREmployeeCode02 ,
                                                HREmployeeNo ,
                                                HREmployeeFullName ,
                                                HRDepartmentName ,
                                                HRSectionName ,
                                                HRPositionName ,
                                                HREmployeeBankBranch,
                                                HRAreaName ,
                                                BRBranchName ,
                                                HREmployeeWorkingPlace ,
                                                CONVERT(VARCHAR(10), HREmployeeStartWorkingDate, 103) HREmployeeStartWorkingDate ,
                                                CONVERT(VARCHAR(10), HREmployeeEndWorkingDate, 103) ,
                                                HREmployeeBankCode ,
                                                HREmployeeBankName ,
                                                HREmployeeBankAccount1
                                        FROM    dbo.HREmployees
                                                LEFT JOIN dbo.HRDepartments ON ( HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID
                                                                                 AND HRDepartments.AAStatus = HREmployees.AAStatus
                                                                               )
                                                LEFT JOIN dbo.HRSections ON ( HRSections.HRSectionID = HREmployees.FK_HRSectionID
                                                                              AND HRSections.AAStatus = HREmployees.AAStatus
                                                                            )
                                                LEFT JOIN dbo.HRPositions ON ( HRPositions.HRPositionID = HREmployees.FK_HRPositionID
                                                                               AND HRPositions.AAStatus = HREmployees.AAStatus
                                                                             )
                                                LEFT JOIN dbo.HRAreas ON ( HRAreas.HRAreaID = HREmployees.FK_HRAreaID
                                                                           AND HRAreas.AAStatus = HREmployees.AAStatus
                                                                         )
                                                LEFT JOIN dbo.BRBranchs ON ( BRBranchs.BRBranchID = HREmployees.FK_BRBranchID
                                                                             AND BRBranchs.AAStatus = HREmployees.AAStatus
                                                                           )
                                                JOIN ( SELECT DISTINCT FK_HREmployeeID
                                                       FROM     dbo.HRWorkSheetItems
                                                       WHERE    CONVERT(NVARCHAR(10), HRWorkSheetItemDate, 112) >= CONVERT(NVARCHAR(10), '{3}', 112)
                                                                AND CONVERT(NVARCHAR(10), HRWorkSheetItemDate, 112) <= CONVERT(NVARCHAR(10), '{4}', 112)
                                                     ) AS temp ON ( temp.FK_HREmployeeID = HREmployees.HREmployeeID )
                                        WHERE   HREmployees.AAStatus = 'Alive'
                                                AND HREmployees.HREmployeeNo LIKE '%{0}%'
                                                AND ( HREmployees.FK_HRDepartmentID = {1}
                                                      OR 0 = {1}
                                                    )
                                                AND ( HREmployees.FK_HRSectionID = {2}
                                                      OR 0 = {2}
                                                    )
                                                               ", strEmployeeNo, iDepartmentID, iSectionID, dtFdate.ToString("yyyyMMdd"),dtTDate.ToString("yyyyMMdd"));
            return dal.GetDataSet(str);
        }
        public DataSet GetAllDataByConditionEmployeeLeaveQuery(string strEmployeeNo, string strCardnumber, int iDepartmentID, int iSectionID, int iYear)
        {
            String str = String.Format(@"SELECT 
                                            HREmployeeID as 'ID',
                                            {4} as 'Năm',
                                            HRDepartmentName AS 'Phòng ban',
                                            HRSectionName AS 'Bộ phận',
                                            HREmployeeNo AS 'Mã NV',
                                            HREmployeeCardNumber AS 'Mã chấm công',
                                            HREmployeeFullName AS 'Tên NV',
                                            HREmployeeStartWorkingDate AS 'Ngày làm việc',
                                            HREmployeeEndWorkingDate AS 'Ngày kết thúc làm việc'
                                            FROM dbo.HREmployees
                                            JOIN HREmpActivitys ON (HREmpActivitys.FK_HREmployeeID = HREmployees.HREmployeeID AND HREmpActivitys.AAStatus=HREmployees.AAStatus)
                                            LEFT JOIN dbo.HRDepartments ON (HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID AND HRDepartments.AAStatus = HREmployees.AAStatus)
                                            LEFT JOIN dbo.HRSections ON (HRSections.HRSectionID = HREmployees.FK_HRSectionID AND HRSections.AAStatus = HREmployees.AAStatus)
                                            WHERE HREmployees.AAStatus='Alive' AND (HREmpActivitys.HREmployeeStatusCombo LIKE 'Working' OR HREmpActivitys.HREmployeeStatusCombo LIKE 'Trying')
                                            AND
                                            (
	                                            (
			                                            YEAR(HREmpActivityStartDate)<= {4}
			                                            AND HREmpActivityEndDate IS NULL
		                                            )
		                                            OR
		                                            (
			                                            YEAR(HREmpActivityStartDate)<= {4}
			                                            AND
			                                            YEAR(HREmpActivityEndDate)>= {4}
		                                            )
                                            )
                                            AND  HREmployees.HREmployeeNo LIKE '%{0}%'
                                            AND HREmployees.HREmployeeCardNumber LIKE '%{1}%'
                                            AND (HREmployees.FK_HRDepartmentID ={2} OR  0={2})
                                            AND (HREmployees.FK_HRSectionID ={3} OR  0={3})", strEmployeeNo, strCardnumber, iDepartmentID, iSectionID, iYear);
            return dal.GetDataSet(str);
        }
        public DataSet GetAllEmployeeByConditionInsuranceQuery(string strEmployeeNo, int iPositionID, int iAreaID, int iBranchID)
        {
            String str = String.Format(@"SELECT  ROW_NUMBER() OVER ( ORDER BY HREmployeeID ) STT ,
                                                HREmployeeNo ,
                                                HREmployeeFullName ,
                                                HRPositionName ,
                                                HRAreaName ,
                                                HREmployeeWorkingPlace,
                                                BRBranchName ,
                                                CONVERT (varchar(10), HREmployeeDob, 103) AS HREmployeeDob ,
                                                ISNULL(Gender.ADConfigText, '') AS HREmployeeGenderCombo ,
                                                HREmployeeNation ,
                                                HREmployeePermanentAddressCountry ,
                                                HREmployeeIDNumber ,
                                                CONVERT (varchar(10), HREmployeeIDCardDate, 103) AS HREmployeeIDCardDate ,
                                                HREmployeeIDCardPlace ,
                                                HREmployeeBirthCertificatePlace ,
                                                HREmployeePermanentAddressLine1 ,
                                                HREmployeeTemporaryAddressLine1 ,
                                                HREmployeeMedicalFirstPlace ,
                                                HREmployeeMedicalApartmentName ,
                                                CONVERT (varchar(10), HREmployeeMedicalApartmentDob, 103) AS HREmployeeMedicalApartmentDob ,
                                                HREmployeeMedicalApartmentAddress ,
                                                HREmployeeFamilyHKNo ,
                                                HREmployeeFamilyRelation ,
                                                CASE WHEN ISNULL(HREmployeeInsuranceCheck, 0) = 1 THEN N'Có'
                                                        ELSE N'Không'
                                                END AS HREmployeeInsuranceCheck ,
                                                HREmployeeInsuranceNo ,
                                                HREmployeeFamilyNo ,
                                                HREmployeeContractSalaryAmount ,
                                                HREmployeeInsuranceSttTypeCombo ,
                                                InsuranceHold.ADConfigText AS HREmployeeInsuranceHoldTypeCombo ,
                                                CASE WHEN ISNULL(HREmployeeInsuranceXHPaidCheck, 0) = 1 THEN N'Đã trả'
                                                        ELSE N'Chưa'
                                                END AS HREmployeeInsuranceXHPaidCheck ,
                                                CONVERT (varchar(10), HREmployeeInsuranceXHPaidDate, 103) AS HREmployeeInsuranceXHPaidDate ,
                                                CASE WHEN ISNULL(HREmployeeInsuranceYTPaidCheck, 0) = 1
                                                        THEN N'Đã phát'
                                                        ELSE N'Chưa'
                                                END AS HREmployeeInsuranceYTPaidCheck ,
                                                CONVERT (varchar(10), HREmployeeInsuranceYTPaidDate, 103) AS HREmployeeInsuranceYTPaidDate
                                        FROM    dbo.HREmployees
                                                LEFT JOIN dbo.HRDepartments ON ( HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID
                                                                                    AND HRDepartments.AAStatus = HREmployees.AAStatus
                                                                                )
                                                LEFT JOIN dbo.HRSections ON ( HRSections.HRSectionID = HREmployees.FK_HRSectionID
                                                                                AND HRSections.AAStatus = HREmployees.AAStatus
                                                                            )
                                                LEFT JOIN dbo.HRPositions ON ( HRPositions.HRPositionID = HREmployees.FK_HRPositionID
                                                                                AND HRPositions.AAStatus = HREmployees.AAStatus
                                                                                )
                                                LEFT JOIN dbo.HRAreas ON ( HRAreas.HRAreaID = HREmployees.FK_HRAreaID
                                                                            AND HRAreas.AAStatus = HREmployees.AAStatus
                                                                            )
                                                LEFT JOIN dbo.BRBranchs ON ( BRBranchs.BRBranchID = HREmployees.FK_BRBranchID
                                                                                AND BRBranchs.AAStatus = HREmployees.AAStatus
                                                                            )
                                                LEFT JOIN ( SELECT  ADConfigKeyValue ,
                                                                    ADConfigText
                                                            FROM    dbo.ADConfigValues
                                                            WHERE   ADConfigKeyGroup = 'EmployeeGender'
                                                            ) AS Gender ON Gender.ADConfigKeyValue = HREmployees.HREmployeeGenderCombo
                                                LEFT JOIN ( SELECT  ADConfigKeyValue ,
                                                                    ADConfigText
                                                            FROM    dbo.ADConfigValues
                                                            WHERE   ADConfigKeyGroup = 'EmployeeInsuranceHoldType'
                                                            ) AS InsuranceHold ON InsuranceHold.ADConfigKeyValue = HREmployees.HREmployeeInsuranceHoldTypeCombo
                                        WHERE   HREmployees.AAStatus = 'Alive' AND (HREmployeeStatusCombo='Working' OR HREmployeeStatusCombo='Trying')
                                            AND HREmployees.HREmployeeNo LIKE '%{0}%'
                                                AND ( HRPositions.HRPositionID = {1}
                                                        OR 0 = {1}
                                                    )
                                                AND ( HREmployees.FK_HRAreaID = {2}
                                                        OR 0 = {2}
                                                    )
			                                            AND ( HREmployees.FK_BRBranchID = {3}
                                                        OR 0 = {3}
                                                    )
                                           ", strEmployeeNo, iPositionID, iAreaID, iBranchID);
            return dal.GetDataSet(str);
        }
        public DataSet GetAllEmployeeByConditionInsuranceQuery(string strCondition)
        {
            String str = String.Format(@"SELECT  ROW_NUMBER() OVER ( ORDER BY HREmployeeID ) STT ,
                                                    HREmployeeNo ,
                                                    HREmployeeFullName ,
                                                    HRPositionName ,
                                                    HRAreaName ,
                                                    HREmployeeWorkingPlace,
                                                    BRBranchName ,
                                                    CONVERT (varchar(10), HREmployeeInsuranceDate, 103) AS HREmployeeInsuranceDate,
                                                    CONVERT (varchar(10), HREmployeeInsuranceEndDate, 103) AS HREmployeeInsuranceEndDate,
                                                    CONVERT (varchar(10), HREmployeeDob, 103) AS HREmployeeDob ,
                                                    ISNULL(Gender.ADConfigText, '') AS HREmployeeGenderCombo ,
                                                    HREmployeeNation ,
                                                    HREmployeePermanentAddressCountry ,
                                                    HREmployeeIDNumber ,
                                                    CONVERT (varchar(10), HREmployeeIDCardDate, 103) AS HREmployeeIDCardDate ,
                                                    HREmployeeIDCardPlace ,
                                                    HREmployeeBirthCertificatePlace ,
                                                    HREmployeePermanentAddressLine1 ,
                                                    HREmployeeTemporaryAddressLine1 ,
                                                    HREmployeeMedicalFirstPlace ,
                                                    HREmployeeMedicalApartmentName ,
                                                    CONVERT (varchar(10), HREmployeeMedicalApartmentDob, 103) AS HREmployeeMedicalApartmentDob ,
                                                    HREmployeeMedicalApartmentAddress ,
                                                    HREmployeeFamilyHKNo ,
                                                    HREmployeeFamilyRelation ,
                                                    CASE WHEN ISNULL(HREmployeeInsuranceCheck, 0) = 1 THEN N'Có'
                                                            ELSE N'Không'
                                                    END AS HREmployeeInsuranceCheck ,
                                                    HREmployeeInsuranceNo ,
                                                    HREmployeeFamilyNo ,
                                                    HREmployeeContractSalaryAmount ,
                                                    EmployeeInsuranceSttType .ADConfigText HREmployeeInsuranceSttTypeCombo ,
                                                    InsuranceHold.ADConfigText AS HREmployeeInsuranceHoldTypeCombo ,
                                                    CASE WHEN ISNULL(HREmployeeInsuranceXHPaidCheck, 0) = 1 THEN N'Đã trả'
                                                            ELSE N'Chưa'
                                                    END AS HREmployeeInsuranceXHPaidCheck ,
                                                    CONVERT (varchar(10), HREmployeeInsuranceXHPaidDate, 103) AS HREmployeeInsuranceXHPaidDate ,
                                                    CASE WHEN ISNULL(HREmployeeInsuranceYTPaidCheck, 0) = 1
                                                            THEN N'Đã phát'
                                                            ELSE N'Chưa'
                                                    END AS HREmployeeInsuranceYTPaidCheck ,
                                                    CONVERT (varchar(10), HREmployeeInsuranceYTPaidDate, 103) AS HREmployeeInsuranceYTPaidDate
                                                    FROM    dbo.HREmployees
                                                    LEFT JOIN dbo.HRDepartments ON ( HRDepartments.HRDepartmentID = HREmployees.FK_HRDepartmentID
                                                                                        AND HRDepartments.AAStatus = HREmployees.AAStatus
                                                                                    )
                                                    LEFT JOIN dbo.HRSections ON ( HRSections.HRSectionID = HREmployees.FK_HRSectionID
                                                                                    AND HRSections.AAStatus = HREmployees.AAStatus
                                                                                )
                                                    LEFT JOIN dbo.HRPositions ON ( HRPositions.HRPositionID = HREmployees.FK_HRPositionID
                                                                                    AND HRPositions.AAStatus = HREmployees.AAStatus
                                                                                    )
                                                    LEFT JOIN dbo.HRAreas ON ( HRAreas.HRAreaID = HREmployees.FK_HRAreaID
                                                                                AND HRAreas.AAStatus = HREmployees.AAStatus
                                                                                )
                                                    LEFT JOIN dbo.BRBranchs ON ( BRBranchs.BRBranchID = HREmployees.FK_BRBranchID
                                                                                    AND BRBranchs.AAStatus = HREmployees.AAStatus
                                                                                )
                                                    LEFT JOIN ( SELECT  ADConfigKeyValue ,
                                                                        ADConfigText
                                                                FROM    dbo.ADConfigValues
                                                                WHERE   ADConfigKeyGroup = 'EmployeeGender'
                                                                ) AS Gender ON Gender.ADConfigKeyValue = HREmployees.HREmployeeGenderCombo
                                                    LEFT JOIN ( SELECT  ADConfigKeyValue ,
                                                                        ADConfigText
                                                                FROM    dbo.ADConfigValues
                                                                WHERE   ADConfigKeyGroup = 'EmployeeInsuranceHoldType'
                                                                ) AS InsuranceHold ON InsuranceHold.ADConfigKeyValue = HREmployees.HREmployeeInsuranceHoldTypeCombo
                                                    LEFT JOIN ( SELECT  ADConfigKeyValue ,
                                                                        ADConfigText
                                                                FROM    dbo.ADConfigValues
                                                                WHERE   ADConfigKeyGroup = 'EmployeeInsuranceSttType'
                                                                ) AS EmployeeInsuranceSttType ON EmployeeInsuranceSttType.ADConfigKeyValue = HREmployees.HREmployeeInsuranceSttTypeCombo
                                                    WHERE   HREmployees.AAStatus = 'Alive' AND (HREmployeeStatusCombo='Working' OR HREmployeeStatusCombo='Trying')
                                                AND HREmployeeID IN ({0})
                                           ", strCondition);
            return dal.GetDataSet(str);
        }
        public int GetTotalEmployeeByCondition(int iDivisonID,int iDepartmentID,int iBranchID, int iPositionID, int iLevID)
        {
            string strQuery = string.Format(@"SELECT  COUNT(HREmployeeID)
                                                FROM    dbo.HREmployees
                                                WHERE   AAStatus = 'Alive'
                                                        AND ( HREmployeeStatusCombo = 'Working'
                                                              OR HREmployeeStatusCombo = 'Trying'
                                                            )
                                                        AND ( FK_HRDivisionID = {0}
                                                              OR {0} = 0
                                                            )
                                                        AND ( FK_HRDepartmentID = {1}
                                                              OR {1} = 0
                                                            )
                                                        AND ( FK_BRBranchID = {2}
                                                              OR {2} = 0
                                                            )
                                                        AND ( FK_HRPositionID = {3}
                                                              OR {3} = 0
                                                            )
                                                        AND ( FK_HRLevID = {4}
                                                              OR {4} = 0
                                                            )"
                                                , iDivisonID,iDepartmentID,iBranchID,iPositionID,iLevID);
            DataSet ds = dal.GetDataSet(strQuery);
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0 && ds.Tables[0].Rows[0][0] != DBNull.Value)
                return Convert.ToInt32(ds.Tables[0].Rows[0][0]);
            return 0;
        }
    }
	#endregion
}