using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HREmployeeTCSrlOverTimes
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HREmployeeTCSrlOverTimesController
	//Created Date:Monday, June 16, 2014
	//-----------------------------------------------------------
	
	public class HREmployeeTCSrlOverTimesController:BaseBusinessController
	{
		public HREmployeeTCSrlOverTimesController()
		{
			dal= new DALBaseProvider("HREmployeeTCSrlOverTimes",typeof(HREmployeeTCSrlOverTimesInfo));
		}

        public void XoaTangCa(int iHREmployeeID, DateTime dtDayFirstMonth)
        {
            string strQry = string.Format(@"DELETE dbo.HREmployeeTCSrlOverTimes
                                          WHERE FK_HREmployeeID = {0} 
                                          AND YEAR(HREmployeeTCSrlOverTimeDate) = {1}
                                          AND MONTH(HREmployeeTCSrlOverTimeDate) = {2}",
                                          iHREmployeeID, dtDayFirstMonth.Year, dtDayFirstMonth.Month);
            dal.GetDataSet(strQry);
        }

        public DataSet LayThongTinTangCaCuaNhanVien(int iHREmployeeID, DateTime dtFrom, DateTime dtTo)
        {
            String str = String.Format(@"   SELECT * FROM dbo.HREmployeeTCSrlOverTimes
                                            WHERE AAStatus='Alive'
                                            AND (FK_HREmployeeID = {0} OR {0} = 0)
                                            AND CONVERT(NVARCHAR(10),HREmployeeTCSrlOverTimeDate, 112) >= '{1}'
                                            AND CONVERT(NVARCHAR(10),HREmployeeTCSrlOverTimeDate, 112) <= '{2}'", iHREmployeeID, dtFrom.ToString("yyyyMMdd"), dtTo.ToString("yyyyMMdd"));
            return dal.GetDataSet(str);
        }
	}
	#endregion
}