using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HROvertimeBatchItems
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HROvertimeBatchItemsController
	//Created Date:Saturday, May 23, 2009
	//-----------------------------------------------------------
	
	public class HROvertimeBatchItemsController:BaseBusinessController
	{
		public HROvertimeBatchItemsController()
		{
			dal= new DALBaseProvider("HROvertimeBatchItems",typeof(HROvertimeBatchItemsInfo));
		}
	}
	#endregion
}