using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertWebLib;
namespace ExpertERP.BusinessEntities
{
	#region HRVacancyLevelReqs
	//-----------------------------------------------------------
	//Generated By: GMC Studio
	//Class:HRVacancyLevelReqsController
	//Created Date:28 Tháng Năm 2013
	//-----------------------------------------------------------
	
	public class HRVacancyLevelReqsController:BaseBusinessController
	{
		public HRVacancyLevelReqsController()
		{
			dal= new DALBaseProvider("HRVacancyLevelReqs",typeof(HRVacancyLevelReqsInfo));
		}
	}
	#endregion
}